package a75f.io.domain.cutover

/**
 * Provides a displayName-domainName mapping of all the BuildingEquip entites for
 * cutover migration.
 *
 * Only points that are part of current local DB are to be included in the list and considered for
 * migration.
 */
object BuildingEquipCutOverMapping {
    val entries = mapOf(
        "BuildingTuner-zoneTemperatureDeadLeeway" to "zoneTemperatureDeadLeeway",
        "BuildingTuner-heartBeatsToSkip" to "heartBeatsToSkip",
        "BuildingTuner-humidityCompensationOffset" to "humidityCompensationOffset",
        "BuildingTuner-clockUpdateInterval" to "clockUpdateInterval",
        //"BuildingTuner-buildingLimitMax" to "buildingLimitMax", //TODO- doing this may create duplicate point as new models dont have this point.
        "BuildingTuner-perDegreeHumidityFactor" to "perDegreeHumidityFactor",
        "BuildingTuner-ccuAlarmVolumeLevel" to "ccuAlarmVolumeLevel",
        //"BuildingTuner-heatingUserLimitMin" to "heatingUserLimitMin",
        //"BuildingTuner-buildingLimitMin" to "buildingLimitMin",
        //"BuildingTuner-coolingUserLimitMax" to "coolingUserLimitMax",
        //"BuildingTuner-heatingUserLimitMax" to "heatingUserLimitMax",
        //"BuildingTuner-buildingToZoneDifferential" to "buildingToZoneDifferential",
        "BuildingTuner-userLimitSpread" to "userLimitSpread",
        //"BuildingTuner-unoccupiedZoneSetback" to "unoccupiedZoneSetback",
        //"BuildingTuner-coolingUserLimitMin" to "coolingUserLimitMin",

        "BuildingTuner-proportionalKFactor" to "proportionalKFactor",
        "BuildingTuner-integralKFactor" to "integralKFactor",
        "BuildingTuner-pidIntegralTime" to "pidIntegralTime",

        "BuildingTuner-rebalanceHoldTime" to "rebalanceHoldTime",
        "BuildingTuner-airflowSampleWaitTime" to "airflowSampleWaitTime",
        "BuildingTuner-buildingLimitAlertTimer" to "buildingLimitAlertTimer",
        "BuildingTuner-constantTempAlertTime" to "constantTempAlertTime",
        "BuildingTuner-abnormalCurTempRiseTrigger" to "abnormalCurTempRiseTrigger",
        "BuildingTuner-heatingAirflowTemp" to "heatingAirflowTemp",
        "BuildingTuner-adrHeatingDeadband" to "adrHeatingDeadband",
        "BuildingTuner-adrCoolingDeadband" to "adrCoolingDeadband",
        "BuildingTuner-coolingAirflowTemp" to "coolingAirflowTemp",
        "BuildingTuner-autoAwayTime" to "autoAwayTime",
        "BuildingTuner-cmResetCommandTimer" to "cmResetCommandTimer",
        "BuildingTuner-forcedOccupiedTime" to "forcedOccupiedTime",
        "BuildingTuner-zoneDeadTime" to "zoneDeadTime",
        "BuildingTuner-displayUnit" to "displayUnit",
        "BuildingTuner-coolingPreconditioningRate" to "coolingPreconditioningRate",
        "BuildingTuner-cmHeartBeatInterval" to "cmHeartBeatInterval",
        "BuildingTuner-autoAwaySetback" to "autoAwaySetback",
        "BuildingTuner-heatingPreconditioningRate" to "heatingPreconditioningRate",
        "BuildingTuner-cmTempPercentDeadZonesAllowed" to "cmTempPercentDeadZonesAllowed",
        "BuildingTuner-ccuNetworkWatchdogTimeout" to "ccuNetworkWatchdogTimeout",
        "BuildingTuner-auxHeating1Activate" to "auxHeating1Activate",
        "BuildingTuner-auxHeating2Activate" to "auxHeating2Activate",
        "BuildingTuner-waterValveSamplingWaitTime" to "waterValveSamplingWaitTime",
        "BuildingTuner-waterValveSamplingOnTime" to "waterValveSamplingOnTime",
        "BuildingTuner-waterValveSamplingLoopDeadbandOnTime" to "waterValveSamplingLoopDeadbandOnTime",
        "BuildingTuner-waterValveSamplingLoopDeadbandWaitTime" to "waterValveSamplingLoopDeadbandWaitTime",

        "BuildingTuner-VAV-zonePrioritySpread" to "vavZonePrioritySpread",
        "BuildingTuner-VAV-zonePriorityMultiplier" to "vavZonePriorityMultiplier",
        "BuildingTuner-VAV-integralKFactor" to "vavIntegralKfactor",
        "BuildingTuner-VAV-zoneVOCTarget" to "vavZoneVocTarget",
        "BuildingTuner-VAV-zoneCO2Threshold" to "vavZoneCo2Threshold",
        "BuildingTuner-VAV-zoneCO2Target" to "vavZoneCo2Target",
        "BuildingTuner-VAV-coolingDeadband" to "vavCoolingDeadband",
        "BuildingTuner-VAV-heatingDeadband" to "vavHeatingDeadband",
        "BuildingTuner-VAV-zoneVOCThreshold" to "vavZoneVOCThreshold",
        "BuildingTuner-VAV-temperatureProportionalRange" to "vavTemperatureProportionalRange",
        "BuildingTuner-VAV-proportionalKFactor" to "vavProportionalKFactor",
        "BuildingTuner-VAV-valveActuationStartDamperPosDuringSysHeating" to "valveActuationStartDamperPosDuringSysHeating",
        "BuildingTuner-VAV-heatingDeadbandMultiplier" to "vavHeatingDeadbandMultiplier",
        "BuildingTuner-VAV-coolingDeadbandMultiplier" to "vavCoolingDeadbandMultiplier",
        "BuildingTuner-VAV-stageDownTimerCounter" to "vavStageDownTimerCounter",
        "BuildingTuner-VAV-outsideTempCoolingLockout" to "vavOutsideTempCoolingLockout",
        "BuildingTuner-VAV-relayDeactivationHysteresis" to "vavRelayDeactivationHysteresis",
        "BuildingTuner-VAV-fanControlOnFixedTimeDelay" to "fanControlOnFixedTimeDelay",
        "BuildingTuner-VAV-analogFanSpeedMultiplier" to "vavAnalogFanSpeedMultiplier",
        "BuildingTuner-VAV-targetCumulativeDamper" to "vavTargetCumulativeDamper",
        "BuildingTuner-VAV-outsideTempHeatingLockout" to "vavOutsideTempHeatingLockout",
        "BuildingTuner-VAV-humidityHysteresis" to "vavHumidityHysteresis",
        "BuildingTuner-VAV-reheatZoneMaxDischargeTemp" to "reheatZoneMaxDischargeTemp",
        "BuildingTuner-VAV-stageUpTimerCounter" to "vavStageUpTimerCounter",
        "BuildingTuner-VAV-reheatZoneToDATMinDifferential" to "reheatZoneToDATMinDifferential",
        "BuildingTuner-VAV-reheatZoneDischargeTempOffset" to "reheatZoneDischargeTempOffset",
        "BuildingTuner-VAV-modeChangeOverHysteresis" to "vavModeChangeOverHysteresis",
        "BuildingTuner-VAV-temperatureIntegralTime" to "vavTemperatureIntegralTime",

        "BuildingTuner-co2SPTrim" to "co2SPTrim",
        "BuildingTuner-co2SPMax" to "co2SPMax",
        "BuildingTuner-co2IgnoreRequest" to "co2IgnoreRequest",
        "BuildingTuner-co2SPRes" to "co2SPRes",
        "BuildingTuner-co2TimeDelay" to "co2TimeDelay",
        "BuildingTuner-co2SPInit" to "co2SPInit",
        "BuildingTuner-co2SPMin" to "co2SPMin",
        "BuildingTuner-co2SPMin" to "co2SPMin",
        "BuildingTuner-co2TimeInterval" to "co2TimeInterval",
        "BuildingTuner-co2SPResMax" to "co2SPResMax",

        "BuildingTuner-satIgnoreRequest" to "satIgnoreRequest",
        "BuildingTuner-satSPMax" to "satSPMax",
        "BuildingTuner-satSPMin" to "satSPMin",
        "BuildingTuner-satSPInit" to "satSPInit",
        "BuildingTuner-satTimeDelay" to "satTimeDelay",
        "BuildingTuner-satSPTrim" to "satSPTrim",
        "BuildingTuner-satSPResMax" to "satSPResMax",
        "BuildingTuner-satTimeInterval" to "satTimeInterval",
        "BuildingTuner-satSPRes" to "satSPRes",

        "BuildingTuner-staticPressureSPMin" to "staticPressureSPMin",
        "BuildingTuner-staticPressureSPRes" to "staticPressureSPRes",
        "BuildingTuner-staticPressureSPMax" to "staticPressureSPMax",
        "BuildingTuner-staticPressureSPInit" to "staticPressureSPInit",
        "BuildingTuner-staticPressureTimeDelay" to "staticPressureTimeDelay",
        "BuildingTuner-staticPressureTimeInterval" to "staticPressureTimeInterval",
        "BuildingTuner-staticPressureSPResMax" to "staticPressureSPResMax",
        "BuildingTuner-staticPressureSPTrim" to "staticPressureSPTrim",
        "BuildingTuner-staticPressureIgnoreRequest" to "staticPressureIgnoreRequest",

        "BuildingTuner-airflowCFMIntegralKFactor" to "vavAirflowCFMIntegralKFactor",
        "BuildingTuner-airflowCFMProportionalKFactor" to "vavAirflowCFMProportionalKFactor",
        "BuildingTuner-airflowCFMIntegralTime" to "vavAirflowCFMIntegralTime",
        "BuildingTuner-airflowCFMProportionalRange" to "vavAirflowCFMProportionalRange",

        "BuildingTuner-standaloneCoolingDeadband" to "standaloneCoolingDeadband",
        "BuildingTuner-standaloneStage2CoolingLowerOffset" to "standaloneStage2CoolingLowerOffset",
        "BuildingTuner-standaloneStage1HeatingUpperOffset" to "standaloneStage1HeatingUpperOffset",
        "BuildingTuner-standaloneStage1HeatingLowerOffset" to "standaloneStage1HeatingLowerOffset",
        "BuildingTuner-standaloneVOCThreshold" to "standaloneVOCThreshold",
        "BuildingTuner-standaloneCoolingPreconditioningRate" to "standaloneCoolingPreconditioningRate",
        "BuildingTuner-standaloneHeatingDeadband" to "standaloneHeatingDeadband",
        "BuildingTuner-standaloneHeatingPreconditioningRate" to "standaloneHeatingPreconditioningRate",
        "BuildingTuner-standaloneStage1CoolingUpperOffset" to "standaloneStage1CoolingUpperOffset",
        "BuildingTuner-standaloneCO2Target" to "standaloneCO2Target",
        "BuildingTuner-standaloneAirflowSampleWaitTime" to "standaloneAirflowSampleWaitTime",
        "BuildingTuner-standaloneStage1Hysteresis" to "standaloneStage1Hysteresis",
        "BuildingTuner-standaloneStage1CoolingLowerOffset" to "standaloneStage1CoolingLowerOffset",
        "BuildingTuner-standaloneCO2Threshold" to "standaloneCO2Threshold",
        "BuildingTuner-standaloneVOCTarget" to "standaloneVOCTarget",
        "BuildingTuner-standaloneStage1Hysteresis" to "standaloneStage1Hysteresis",
        "BuildingTuner-standaloneHeatingDeadbandMultiplier" to "standaloneHeatingDeadbandMultiplier",
        "BuildingTuner-standaloneStage2HeatingLowerOffset" to "standaloneStage2HeatingLowerOffset",
        "BuildingTuner-standaloneStage2CoolingUpperOffset" to "standaloneStage2CoolingUpperOffset",
        "BuildingTuner-standaloneTemperatureProportionalRange" to "standaloneTemperatureProportionalRange",
        "BuildingTuner-standaloneProportionalKFactor" to "standaloneProportionalKFactor",
        "BuildingTuner-standaloneIntegralKFactor" to "standaloneIntegralKFactor",
        "BuildingTuner-standaloneRelayActivationHysteresis" to "standaloneRelayActivationHysteresis",
        "BuildingTuner-standaloneCoolingDeadbandMultiplier" to "standaloneCoolingDeadbandMultiplier",
        "BuildingTuner-standaloneHumidityHysteresis" to "standaloneHumidityHysteresis",
        "BuildingTuner-standaloneTemperatureIntegralTime" to "standaloneTemperatureIntegralTime",
        "BuildingTuner-standaloneAnalogFanSpeedMultiplier" to "standaloneAnalogFanSpeedMultiplier",
        "BuildingTuner-standaloneStage2HeatingUpperOffset" to "standaloneStage2HeatingUpperOffset",

        "BuildingTuner-DAB-stageDownTimerCounter" to "dabStageDownTimerCounter",
        "BuildingTuner-DAB-integralKFactor" to "dabIntegralKFactor",
        "BuildingTuner-DAB-modeChangeoverHysteresis" to "dabModeChangeoverHysteresis",
        "BuildingTuner-DAB-analogFanSpeedMultiplier" to "dabAnalogFanSpeedMultiplier",
        "BuildingTuner-DAB-zonePrioritySpread" to "dabZonePrioritySpread",
        "BuildingTuner-DAB-heatingDeadbandMultiplier" to "dabHeatingDeadbandMultiplier",
        "BuildingTuner-DAB-temperatureProportionalRange" to "dabTemperatureProportionalRange",
        "BuildingTuner-DAB-relayDeactivationHysteresis" to "dabRelayDeactivationHysteresis",
        "BuildingTuner-DAB-zoneVOCTarget" to "dabZoneVOCTarget",
        "BuildingTuner-DAB-zoneVOCThreshold" to "dabZoneVOCThreshold",
        "BuildingTuner-DAB-targetCumulativeDamper" to "dabTargetCumulativeDamper",
        "BuildingTuner-DAB-stageUpTimerCounter" to "dabStageUpTimerCounter",
        "BuildingTuner-DAB-zoneCO2Target" to "dabZoneCO2Target",
        "BuildingTuner-DAB-proportionalKFactor" to "dabProportionalKFactor",
        "BuildingTuner-DAB-zonePriorityMultiplier" to "dabZonePriorityMultiplier",
        "BuildingTuner-DAB-temperatureIntegralTime" to "dabTemperatureIntegralTime",
        "BuildingTuner-DAB-coolingDeadband" to "dabCoolingDeadband",
        "BuildingTuner-DAB-zoneCO2Threshold" to "dabZoneCO2Threshold",
        "BuildingTuner-DAB-heatingDeadband" to "dabHeatingDeadband",
        "BuildingTuner-DAB-coolingDeadbandMultiplier" to "dabCoolingDeadbandMultiplier",
        "BuildingTuner-DAB-outsideTempHeatingLockout" to "dabOutsideTempHeatingLockout",
        "BuildingTuner-DAB-humidityHysteresis" to "dabHumidityHysteresis",
        "BuildingTuner-DAB-outsideTempCoolingLockout" to "dabOutsideTempCoolingLockout",
        "BuildingTuner-DAB-reheatRelayActivationHysteresis" to "dabReheatRelayActivationHysteresis",
        "BuildingTuner-DAB-reheatTemperatureIntegralTime" to "dabReheatTemperatureIntegralTime",
        "BuildingTuner-DAB-reheatTempOffset" to "reheatTempOffset",
        "BuildingTuner-DAB-reheatTemperatureProportionalRange" to "dabReheatTemperatureProportionalRange",
        "BuildingTuner-DAB-reheatIntegralKFactor" to "dabReheatIntegralKFactor",
        "BuildingTuner-DAB-reheatProportionalKFactor" to "dabReheatProportionalKFactor",

        "BuildingTuner-TI-coolingDeadbandMultiplier" to "tiCoolingDeadbandMultiplier",
        "BuildingTuner-TI-integralKFactor" to "tiIntegralKFactor",
        "BuildingTuner-TI-temperatureProportionalRange" to "tiTemperatureProportionalRange",
        "BuildingTuner-TI-heatingDeadband" to "tiHeatingDeadband",
        "BuildingTuner-TI-temperatureIntegralTime" to "tiTemperatureIntegralTime",
        "BuildingTuner-TI-heatingDeadbandMultiplier" to "tiHeatingDeadbandMultiplier",
        "BuildingTuner-TI-zonePrioritySpread" to "tiZonePrioritySpread",
        "BuildingTuner-TI-proportionalKFactor" to "tiProportionalKFactor",
        "BuildingTuner-TI-coolingDeadband" to "tiCoolingDeadband",
        "BuildingTuner-TI-zonePriorityMultiplier" to "tiZonePriorityMultiplier",


        "BuildingTuner-OAO-outsideDamperMixedAirMinimum" to "outsideDamperMixedAirMinimum",
        "BuildingTuner-OAO-economizingToMainCoolingLoopMap" to "economizingToMainCoolingLoopMap",
        "BuildingTuner-OAO-systemPrePurgeFanSpeedTuner" to "systemPrePurgeFanSpeedTuner",
        "BuildingTuner-OAO-co2DamperOpeningRate" to "co2DamperOpeningRate",
        "BuildingTuner-OAO-systemPostPurgeRuntimeTuner" to "systemPostPurgeRuntimeTuner",
        "BuildingTuner-OAO-economizingMinTemperature" to "economizingMinTemperature",
        "BuildingTuner-OAO-economizingMaxTemperature" to "economizingMaxTemperature",
        "BuildingTuner-OAO-economizingMinHumidity" to "economizingMinHumidity",
        "BuildingTuner-OAO-outsideDamperMixedAirTarget" to "outsideDamperMixedAirTarget",
        "BuildingTuner-OAO-systemPrePurgeRuntimeTuner" to "systemPrePurgeRuntimeTuner",
        "BuildingTuner-OAO-economizingMaxHumidity" to "economizingMaxHumidity",
        "BuildingTuner-OAO-systemPrePurgeOccupiedTimeOffsetTuner" to "systemPrePurgeOccupiedTimeOffsetTuner",
        "BuildingTuner-OAO-enthalpyDuctCompensationOffset" to "enthalpyDuctCompensationOffset",
        "BuildingTuner-OAO-systemPostPurgeFanSpeedTuner" to "systemPostPurgeFanSpeedTuner",
        "BuildingTuner-OAO-systemPostPurgeOccupiedTimeOffsetTuner" to "systemPostPurgeOccupiedTimeOffsetTuner",
        "BuildingTuner-OAO-systemPurgeDabDamperMinOpenMultiplier" to "systemPurgeDabDamperMinOpenMultiplier",
        "BuildingTuner-OAO-systemPurgeVavMinFanLoopOutput" to "systemPurgeVavMinFanLoopOutput",
        "BuildingTuner-OAO-systemPurgeDabMinFanLoopOutput" to "systemPurgeDabMinFanLoopOutput",
        "BuildingTuner-OAO-systemPurgeVavDamperMinOpenMultiplier" to "systemPurgeVavDamperMinOpenMultiplier",
        "BuildingTuner-OAO-economizingDryBulbThreshold" to "economizingDryBulbThreshold",

        "BuildingTuner-OAO-standaloneEnthalpyDuctCompensationOffset" to "standaloneEnthalpyDuctCompensationOffset",
        "BuildingTuner-OAO-standaloneEconomizingToMainCoolingLoopMap" to "standaloneEconomizingToMainCoolingLoopMap",
        "BuildingTuner-OAO-standaloneEconomizingMinTemperature" to "standaloneEconomizingMinTemperature",
        "BuildingTuner-OAO-standaloneEconomizingMaxTemperature" to "standaloneEconomizingMaxTemperature",
        "BuildingTuner-OAO-standaloneEconomizingMinHumidity" to "standaloneEconomizingMinHumidity",
        "BuildingTuner-OAO-standaloneEconomizingMaxHumidity" to "standaloneEconomizingMaxHumidity",
        "BuildingTuner-OAO-standaloneEconomizingDryBulbThreshold" to "standaloneEconomizingDryBulbThreshold",
        "BuildingTuner-OAO-standaloneOutsideDamperMixedAirTarget" to "standaloneOutsideDamperMixedAirTarget",
        "BuildingTuner-OAO-standaloneOutsideDamperMixedAirMinimum" to "standaloneOutsideDamperMixedAirMinimum",
        "BuildingTuner-OAO-standaloneDuctTemperatureOffset" to "standaloneDuctTemperatureOffset",
        "BuildingTuner-OAO-standaloneCoolingAirflowTempLowerOffset" to "standaloneCoolingAirflowTempLowerOffset",
        "BuildingTuner-OAO-standaloneCoolingAirflowTempUpperOffset" to "standaloneCoolingAirflowTempUpperOffset",
        "BuildingTuner-OAO-standaloneHeatingAirflowTempUpperOffset" to "standaloneHeatingAirflowTempUpperOffset",
        "BuildingTuner-OAO-standaloneHeatingAirflowTempLowerOffset" to "standaloneHeatingAirflowTempLowerOffset",

        //TODO - stand alone OAO tuners?

        "BuildingTuner-DualDuct-zoneVOCTarget" to "dualDuctZoneVocTarget",
        "BuildingTuner-DualDuct-zoneCO2Target" to "dualDuctZoneCO2Target",
        "BuildingTuner-DualDuct-coolingDeadband" to "dualDuctCoolingDeadband",
        "BuildingTuner-DualDuct-integralKFactor" to "dualDuctIntegralKFactor",
        "BuildingTuner-DualDuct-zoneVOCThreshold" to "dualDuctZoneVOCThreshold",
        "BuildingTuner-DualDuct-zoneCO2Threshold" to "dualDuctZoneCO2Threshold",
        "BuildingTuner-DualDuct-temperatureIntegralTime" to "dualDuctTemperatureIntegralTime",
        "BuildingTuner-DualDuct-proportionalKFactor" to "dualDuctProportionalKFactor",
        "BuildingTuner-DualDuct-zonePrioritySpread" to "dualDuctZonePrioritySpread",
        "BuildingTuner-DualDuct-coolingDeadbandMultiplier" to "dualDuctCoolingDeadbandMultiplier",
        "BuildingTuner-DualDuct-temperatureProportionalRange" to "dualDuctTemperatureProportionalRange",
        "BuildingTuner-DualDuct-heatingDeadband" to "dualDuctHeatingDeadband",
        "BuildingTuner-DualDuct-zonePriorityMultiplier" to "dualDuctZonePriorityMultiplier",
        "BuildingTuner-DualDuct-heatingDeadbandMultiplier" to "dualDuctHeatingDeadbandMultiplier",

        "BuildingTuner-stage1CoolingAirflowTempUpperOffset" to "stage1CoolingAirflowTempUpperOffset",
        "BuildingTuner-stage1CoolingAirflowTempLowerOffset" to "stage1CoolingAirflowTempLowerOffset",
        "BuildingTuner-stage4CoolingAirflowTempLowerOffset" to "stage4CoolingAirflowTempLowerOffset",
        "BuildingTuner-stage5CoolingAirflowTempUpperOffset" to "stage5CoolingAirflowTempUpperOffset",
        "BuildingTuner-stage2HeatingAirflowTempLowerOffset" to "stage2HeatingAirflowTempLowerOffset",
        "BuildingTuner-stage2CoolingAirflowTempLowerOffset" to "stage2CoolingAirflowTempLowerOffset",
        "BuildingTuner-stage5CoolingAirflowTempLowerOffset" to "stage5CoolingAirflowTempLowerOffset",
        "BuildingTuner-stage5HeatingAirflowTempLowerOffset" to "stage5HeatingAirflowTempLowerOffset",
        "BuildingTuner-stage3HeatingAirflowTempUpperOffset" to "stage3HeatingAirflowTempUpperOffset",
        "BuildingTuner-stage4HeatingAirflowTempLowerOffset" to "stage4HeatingAirflowTempLowerOffset",
        "BuildingTuner-stage3CoolingAirflowTempUpperOffset" to "stage3CoolingAirflowTempUpperOffset",
        "BuildingTuner-stage1HeatingAirflowTempLowerOffset" to "stage1HeatingAirflowTempLowerOffset",
        "BuildingTuner-stage3HeatingAirflowTempLowerOffset" to "stage3HeatingAirflowTempLowerOffset",
        "BuildingTuner-stage1HeatingAirflowTempUpperOffset" to "stage1HeatingAirflowTempUpperOffset",
        "BuildingTuner-stage2HeatingAirflowTempUpperOffset" to "stage2HeatingAirflowTempUpperOffset",
        "BuildingTuner-stage3CoolingAirflowTempLowerOffset" to "stage3CoolingAirflowTempLowerOffset",
        "BuildingTuner-stage4HeatingAirflowTempUpperOffset" to "stage4HeatingAirflowTempUpperOffset",
        "BuildingTuner-stage4CoolingAirflowTempUpperOffset" to "stage4CoolingAirflowTempUpperOffset",
        "BuildingTuner-stage5HeatingAirflowTempUpperOffset" to "stage5HeatingAirflowTempUpperOffset",
        "BuildingTuner-stage2CoolingAirflowTempUpperOffset" to "stage2CoolingAirflowTempUpperOffset",

        "BuildingTuner-OTN-integralKFactor" to "otnIntegralKFactor",
        "BuildingTuner-OTN-temperatureIntegralTime" to "otnTemperatureIntegralTime",
        "BuildingTuner-OTN-zonePriorityMultiplier" to "otnZonePriorityMultiplier",
        "BuildingTuner-OTN-coolingDeadband" to "otnCoolingDeadband",
        "BuildingTuner-OTN-heatingDeadband" to "otnHeatingDeadband",
        "BuildingTuner-OTN-temperatureProportionalRange" to "otnTemperatureProportionalRange",
        "BuildingTuner-OTN-proportionalKFactor" to "otnProportionalKFactor",
        "BuildingTuner-OTN-zonePrioritySpread" to "otnZonePrioritySpread",

        "BuildingTuner-DCWB-chilledWaterTemperatureIntegralTime" to "chilledWaterTemperatureIntegralTime",
        "BuildingTuner-DCWB-chilledWaterIntegralKFactor" to "chilledWaterIntegralKFactor",
        "BuildingTuner-DCWB-chilledWaterTemperatureProportionalRange" to "dcwbChilledWaterTemperatureProportionalRange",
        "BuildingTuner-DCWB-adaptiveComfortThresholdMargin" to "adaptiveComfortThresholdMargin",
        "BuildingTuner-DCWB-chilledWaterProportionalKFactor" to "chilledWaterProportionalKFactor",

        "BuildingTuner-2PipeFancoilHeatingThreshold" to "pipe2FancoilHeatingThreshold",
        "BuildingTuner-2PipeFancoilCoolingThreshold" to "pipe2FancoilCoolingThreshold",

        "BuildingSchedulable-coolingUserLimitMin" to "coolingUserLimitMin",
        "BuildingSchedulable-buildingLimitMax" to "buildingLimitMax",
        "BuildingSchedulable-heatingUserLimitMax" to "heatingUserLimitMax",
        "BuildingSchedulable-buildingLimitMin" to "buildingLimitMin",
        "BuildingSchedulable-heatingUserLimitMin" to "heatingUserLimitMin",
        "BuildingSchedulable-coolingUserLimitMax" to "coolingUserLimitMax",
        "BuildingSchedulable-buildingToZoneDifferential" to "buildingToZoneDifferential",
        "BuildingSchedulable-heatingDeadband" to "heatingDeadband",
        "BuildingSchedulable-unoccupiedZoneSetback" to "unoccupiedZoneSetback",
        "BuildingSchedulable-coolingDeadband" to "coolingDeadband",

        "BuildingTuner-VRV-heatingDeadbandMultiplier" to "vrvHeatingDeadbandMultiplier",
        "BuildingTuner-VRV-heatingDeadband" to "vrvHeatingDeadband",
        "BuildingTuner-VRV-coolingDeadbandMultiplier" to "vrvCoolingDeadbandMultiplier",
        "BuildingTuner-VRV-coolingDeadband" to "vrvCoolingDeadband",

    )
    fun getDomainNameFromDis(point : Map<Any, Any>) : String? {
        val displayNme = point["dis"].toString()
        return entries.filterKeys { displayNme.replace("\\s".toRegex(),"").substringAfterLast("-") == it }
            .map { it.value }
            .firstOrNull()
    }
    fun findDisFromDomainName(domainName : String) : String? {
        return entries.filterValues { it.equals(domainName,true) }
            .map { it.key }
            .firstOrNull()
    }
}