package a75f.io.domain.cutover

object DabZoneProfileCutOverMapping {
    val entries = mapOf(
        "damper1Type" to "damper1Type",
        "damper2Type" to "damper2Type",
        "damper1Shape" to "damper1Shape",
        "damper2Shape" to "damper2Shape",
        "damper1Size" to "damper1Size",
        "damper2Size" to "damper2Size",
        "reheatType" to "reheatType",
        "normalizedDamper1Pos" to "normalizedDamper1Cmd",
        "normalizedDamper2Pos" to "normalizedDamper2Cmd",

        "reheatMinDamper" to "minReheatDamperPos",

        "autoawayEnabled" to "autoAway",
        "autoForceOccupiedEnabled" to "autoForceOccupied",
        "enableCFMControl" to "enableCFMControl",
        "enableIAQControl" to "enableIAQControl",
        "enableCO2Control" to "enableCO2Control",

        "minCoolingDamperPos" to "minCoolingDamperPos",
        "minHeatingDamperPos" to "minHeatingDamperPos",
        "maxHeatingDamperPos" to "maxHeatingDamperPos",
        "maxCoolingDamperPos" to "maxCoolingDamperPos",
        "temperatureOffset" to "temperatureOffset",

        "zonePriority" to "zonePriority",
        "zonePriorityMultiplier" to "dabZonePriorityMultiplier",
        "zonePrioritySpread" to "dabZonePrioritySpread",
        "zoneDeadTime" to "zoneDeadTime",
        "abnormalCurTempRiseTrigger" to "abnormalCurTempRiseTrigger",
        "forcedOccupiedTime" to "forcedOccupiedTime",
        "autoAwayTime" to "autoAwayTime",
        "autoAwaySetback" to "autoAwaySetback",
        "constantTempAlertTime" to "constantTempAlertTime",

        "minCFMIAQ" to "minCFMIAQ",
        "desiredTemp" to "desiredTemp",
        "desiredTempCooling" to "desiredTempCooling",
        "desiredTempHeating" to "desiredTempHeating",

        "currentTemp" to "currentTemp",
        "co2" to "zoneCO2",
        "humidity" to "zoneHumidity",
        "voc" to "zoneVoc",
        "pressure" to "pressureSensor",
        "occupancyDetection" to "occupancyDetection",
        "uvi" to "zoneUvi",
        "occupancySensor" to "zoneOccupancy",
        "illuminance" to "zoneIlluminance",
        "sound" to "zoneSound",

        "damper1Pos" to "damper1Cmd",
        "damper2Pos" to "damper2Cmd",
        "damperFeedback" to "damperFeedback",
        "reheatPos" to "reheatCmd",
        "occupancy" to "occupancyMode",

        "heatingLoopOp" to "heatingLoopOutput",
        "coolingLoopOp" to "coolingLoopOutput",
        "enteringAirTemp" to "enteringAirTemp",
        "dischargeAirTemp" to "dischargeAirTemp1",
        "dischargeSp" to "dischargeAirTempSetpoint",

        "coolingDeadbandMultiplier" to "dabCoolingDeadbandMultiplier",
        "heatingDeadbandMultiplier" to "dabHeatingDeadbandMultiplier",

        "proportionalKFactor" to "dabProportionalKFactor",
        "integralKFactor" to "dabIntegralKFactor",
        "temperatureProportionalRange" to "dabTemperatureProportionalRange",
        "temperatureIntegralTime" to "dabTemperatureIntegralTime",

        "scheduleType" to "scheduleType",
        "equipStatus" to "equipStatus",
        "equipScheduleStatus" to "equipScheduleStatus",
        "equipStatusMessage" to "equipStatusMessage",

        "zoneDynamicPriority" to "zoneDynamicPriority",

        "heartBeat" to "heartBeat",
        "otaStatus" to "otaStatus",

        "satCurrentRequest" to "satCurrentRequest",
        "satRequestPercentage" to "satRequestPercentage",
        "co2CurrentRequest" to "co2CurrentRequest",
        "co2RequestPercentage" to "co2RequestPercentage",
        "spCurrentRequest" to "pressureCurrentRequest",
        "staticRequestPercentage" to "pressureRequestPercentage",

        "valveActuationStartDamperPosDuringSysHeating" to "valveActuationStartDamperPosDuringSysHeating",
        "reheatZoneMaxDischargeTemp" to "reheatZoneMaxDischargeTemp",
        "reheatZoneToDATMinDifferential" to "reheatZoneToDATMinDifferential",
        "reheatZoneDischargeTempOffset" to "reheatZoneDischargeTempOffset",

        "minCFMCooling" to "minCFMCooling",
        "minCFMReheating" to "minCFMReheating",
        "maxCFMCooling" to "maxCFMCooling",
        "kFactor" to "kFactor",
        "maxCFMReheating" to "maxCFMReheating",
        "airVelocity" to "airVelocity",
        "airflow" to "airFlowSensor",
        "fanControlOnFixedTimeDelay" to "fanControlOnFixedTimeDelay",
        "supplyAirTemp1" to "dischargeAirTemp1",
        "supplyAirTemp2" to "dischargeAirTemp2",
        "zoneCO2Threshold" to "dabZoneCo2Threshold",
        "zoneVOCThreshold" to "dabZoneVocThreshold",
        "ZoneVocTarget" to "dabZoneVocTarget",
        "zoneCO2Target" to "dabZoneCo2Target",
        "reheatTempOffset" to "reheatTempOffset",
        "reheatTemperatureIntegralTime" to "dabReheatTemperatureIntegralTime",
        "reheatTemperatureProportionalRange" to "dabReheatTemperatureProportionalRange",
        "reheatTempOffset" to "reheatTempOffset",
        "reheatIntegralKFactor" to "dabReheatIntegralKFactor",
        "reheatRelayActivationHysteresis" to "dabReheatRelayActivationHysteresis",
        "autoAwaySetback" to "autoAwaySetback",
        "Demand Response Setback"  to "demandResponseSetback",
        "reheatProportionalKFactor" to "dabReheatProportionalKFactor",
    )
}