package a75f.io.domain.cutover

object SseZoneProfileCutOverMapping {
    val entries = mapOf(
        "airflowTempSensorTh1" to "dischargeAirTemperature",
        "currentTemp" to "currentTemp",
        "humidity" to "zoneHumidity",
        "co2" to "zoneCO2",
        "equipStatus" to "equipStatus",
        "equipStatusMessage" to "equipStatusMessage",
        "equipScheduleStatus" to "equipScheduleStatus",
        "heartBeat" to "heartBeat",
        "scheduleType" to "scheduleType",
        "temperatureOffset" to "temperatureOffset",
        "autoForceOccupiedEnabled" to "autoForceOccupied",
        "autoawayEnabled" to "autoAway",
        "occupancy" to "occupancyMode",
        "occupancyDetection" to "occupancyDetection",
        "desiredTemp" to "desiredTemp",
        "desiredTempCooling" to "desiredTempCooling",
        "desiredTempHeating" to "desiredTempHeating",
        "pressure" to "pressureSensor",
        "otaStatus" to "otaStatus",
        "zonePriority" to "zonePriority",
        "external10kTempSensorTh2" to "externalAirTempSensor",
        "coolingStage1" to "coolingStage1",
        "heatingStage1" to "heatingStage1",
        "analogIn1Association" to "analog1InputAssociation",
        "enableAirflowTempSensor" to "thermistor1InputEnable",
        "enableExternal10kTempSensorTh2" to "thermistor2InputEnable",
        "enableRelay1" to "relay1OutputEnable",
        "enableFanStageRelay2" to "relay2OutputEnable",
        "analogIn1Enabled" to "analog1InputEnable",
        "fanStage1" to "fanStage1",
        "zoneDeadTime" to "zoneDeadTime",
        "autoAwayTime" to "autoAwayTime",
        "forcedOccupiedTime" to "forcedOccupiedTime",
        "constantTempAlertTime" to "constantTempAlertTime",
        "standaloneStage1Hysteresis" to "standaloneStage1Hysteresis",
        "standaloneCoolingPreconditioningRate" to "standaloneCoolingPreconditioningRate",
        "standaloneHeatingPreconditioningRate" to "standaloneHeatingPreconditioningRate",
        "abnormalCurTempRiseTrigger" to "abnormalCurTempRiseTrigger",
        "standaloneAirflowSampleWaitTime" to "standaloneAirflowSampleWaitTime",
        "standaloneCO2Target" to "standaloneCo2Target",
        "standaloneCO2Threshold" to "standaloneCo2Threshold",
        "autoAwaySetback" to "autoAwaySetback",
        "Demand Response Setback" to "demandResponseSetback",
        "coolingAirflowTemp" to "coolingAirflowTemp",
        "heatingAirflowTemp" to "heatingAirflowTemp",
        "standaloneCoolingAirflowTempUpperOffset" to "standaloneStage1CoolingUpperOffset",
        "standaloneCoolingAirflowTempLowerOffset" to "standaloneStage1CoolingLowerOffset",
        "standaloneHeatingAirflowTempUpperOffset" to "standaloneStage1HeatingUpperOffset",
        "standaloneHeatingAirflowTempLowerOffset" to "standaloneStage1HeatingLowerOffset",
        "currentDrawn_10" to "currentTx10",
        "currentDrawn_20" to "currentTx20",
        "currentDrawn_50" to "currentTx50",

    )
}