package a75f.io.domain.cutover

object VavFullyModulatingRtuCutOverMapping {
    val entries = linkedMapOf(
        "outsideTemperature" to "outsideTemperature",
        "cmHumidity" to "cmHumidity",
        "coolingLoopOutput" to "coolingLoopOutput",
        "occupancy" to "systemOccupancyMode",
        "systemPrePurgeEnabled" to "systemPrePurgeEnable",
        "useOutsideTempLockoutHeating" to "useOutsideTempLockoutHeating",
        "useOutsideTempLockoutCooling" to "useOutsideTempLockoutCooling",

        "outsideHumidity" to "outsideHumidity",
        "backFillDuration" to "backFillDuration",
        "epidemicModeSystemState" to "epidemicModeSystemState",

        "systemEnhancedVentilationEnabled" to "systemEnhancedVentilationEnable",
        "cmHeatingDesiredTemp" to "cmHeatingDesiredTemp",
        "cmCoolingDesiredTemp" to "cmCoolingDesiredTemp",
        "StatusMessage" to "equipStatusMessage",
        "fanLoopOutput" to "fanLoopOutput",
        "averageHumidity" to "averageHumidity",

        "operatingMode" to "operatingMode",
        "co2LoopOutput" to "co2LoopOutput",
        "averageTemperature" to "averageTemperature",
        "ScheduleStatus" to "equipScheduleStatus",
        "heatingLoopOutput" to "heatingLoopOutput",
        "cmCurrentTemp" to "currentTemp",
        "systemPostPurgeEnabled" to "systemPostPurgeEnable",
        "systemCI" to "systemCI",

        "analog1Out" to "analog1Out",
        "analog2Out" to "analog2Out",
        "analog3Out" to "analog3Out",
        "analog4Out" to "analog4Out",
        "analog1In" to "analog1In",
        "analog2In" to "analog2In",
        "relay1State" to "relay1",
        "relay2State" to "relay2",
        "relay3State" to "relay3",
        "relay4State" to "relay4",
        "relay5State" to "relay5",
        "relay6State" to "relay6",
        "relay7State" to "relay7",
        "relay8State" to "relay8",
        "th1In" to "th1In",
        "th2In" to "th2In",
        "firmwareVersion" to "firmwareVersion",


        "analog1OutputEnabled" to "analog1OutputEnable",
        "analog2OutputEnabled"  to "analog2OutputEnable",
        "analog3OutputEnabled" to "analog3OutputEnable",
        "analog4OutputEnabled" to "analog4OutputEnable",



        "relay1OutputEnabled" to "relay1OutputEnable",
        "relay2OutputEnabled" to "relay2OutputEnable",
        "relay3OutputEnabled" to "relay3OutputEnable",
        "relay4OutputEnabled" to "relay4OutputEnable",
        "relay5OutputEnabled" to "relay5OutputEnable",
        "relay6OutputEnabled" to "relay6OutputEnable",
        "relay7OutputEnabled" to "relay7OutputEnable",

        "relay1OutputAssociation" to "relay1OutputAssociation",
        "relay2OutputAssociation" to "relay2OutputAssociation",
        "relay3OutputAssociation" to "relay3OutputAssociation",
        "relay4OutputAssociation" to "relay4OutputAssociation",
        "relay5OutputAssociation" to "relay5OutputAssociation",
        "relay6OutputAssociation" to "relay6OutputAssociation",
        "relay7OutputAssociation" to "relay7OutputAssociation",

        "mechanicalHeatingAvailable" to "mechanicalHeatingAvailable",
        "mechanicalCoolingAvailable" to "mechanicalCoolingAvailable",
        "demandResponseMode" to "demandResponseMode",
        "conditioningMode" to "conditioningMode",

        "compensateHumidity" to "compensateHumidity",
        "outsideTempCoolingLockout" to "vavOutsideTempCoolingLockout",
        "desiredCI" to "desiredCI",

        "targetMinInsideHumidty" to "systemtargetMinInsideHumidity",
        "outsideTempHeatingLockout" to "vavOutsideTempHeatingLockout",
        "Humidifier" to "humidifier",
        "weightedAverageHeatingLoadMA" to "weightedAverageHeatingLoad",


        "targetMaxInsideHumidty" to "systemtargetMaxInsideHumidity",
        "weightedAverageCoolingLoadMA" to "weightedAverageCoolingLoad",

        "analog1AtMinCoolingSat" to "analog1MinCooling",
        "analog1AtMaxCoolingSat" to "analog1MaxCooling",
        "analog2AtMinStaticPressure" to "analog2MinStaticPressure",
        "analog2AtMaxStaticPressure" to "analog2MaxStaticPressure",
        "analog3AtMinHeating" to "analog3MinHeating",
        "analog3AtMaxHeating" to "analog3MaxHeating",
        "analog4AtMinCO2" to "analog4MinOutsideDamper",
        "analog4AtMaxCO2" to "analog4MaxOutsideDamper",
        "humidifierType" to "relay7OutputEnable",


        "satTRSp" to "satTRSp",
        "satSPMin" to "satSpMin",
        "satSPMax" to "satSpMax",
        "satSPInit" to "satSpInit",
        "satSPTrim" to "satSpTrim",
        "satTimeInterval" to "satTimeInterval",
        "satIgnoreRequest" to "satIgnoreRequest",
        "satSPRes" to "satSpResMax",
        "satSPResMax" to "satSpResMax",
        "satTimeDelay" to "satTimeDelay",

        "staticPressureTRSp" to "staticPressureTRSp",
        "staticPressureSPInit" to "staticPressureSpInit",
        "staticPressureSPMin" to "staticPressureSpMin",
        "staticPressureSPMax" to "staticPressureSpMax",
        "staticPressureTimeDelay" to "staticPressureTimeDelay",
        "staticPressureTimeInterval" to "staticPressureTimeInterval",
        "staticPressureSPRes" to "staticPressureSpRes",
        "staticPressureSPResMax" to "staticPressureSpResMax",
        "staticPressureSPTrim" to "staticPressureSpTrim",
        "staticPressureIgnoreRequest" to "staticPressureIgnoreRequest",

        "co2TRSp" to "co2TRSp",
        "co2SPMin" to "co2SpMin",
        "co2SPInit" to "co2SpInit",
        "co2IgnoreRequest" to "co2IgnoreRequest",
        "coolingPreconditioningRate" to "coolingPreconditioningRate",
        "co2TimeDelay" to "co2TimeDelay",
        "co2SPRes" to "co2SPRes",
        "co2SPResMax" to "co2SpResMax",
        "co2SPMax" to "co2SpMax",
        "co2TimeInterval" to "co2TimeInterval",
        "co2SPTrim" to "co2SpTrim",

        "airflowSampleWaitTime" to "airflowSampleWaitTime",
        "clockUpdateInterval" to "clockUpdateInterval",
        "heatingPreconditioningRate" to "heatingPreconditioningRate",

        "stage1HeatingAirflowTempLowerOffset" to "stage1HeatingAirflowTempLowerOffset",
        "stage1CoolingAirflowTempLowerOffset" to "stage1CoolingAirflowTempLowerOffset",
        "stage1CoolingAirflowTempUpperOffset" to "stage1CoolingAirflowTempUpperOffset",
        "stage1HeatingAirflowTempUpperOffset" to "stage1HeatingAirflowTempUpperOffset",
        "stage2CoolingAirflowTempLowerOffset" to "stage2CoolingAirflowTempLowerOffset",
        "stage2CoolingAirflowTempUpperOffset" to "stage2CoolingAirflowTempUpperOffset",
        "stage2HeatingAirflowTempLowerOffset" to "stage2HeatingAirflowTempLowerOffset",
        "stage2HeatingAirflowTempUpperOffset" to "stage2HeatingAirflowTempUpperOffset",
        "stage3HeatingAirflowTempLowerOffset" to "stage3HeatingAirflowTempLowerOffset",
        "stage3HeatingAirflowTempUpperOffset" to "stage3HeatingAirflowTempUpperOffset",
        "stage3CoolingAirflowTempUpperOffset" to "stage3CoolingAirflowTempUpperOffset",
        "stage3CoolingAirflowTempLowerOffset" to "stage3CoolingAirflowTempLowerOffset",
        "stage4CoolingAirflowTempLowerOffset" to "stage4CoolingAirflowTempLowerOffset",
        "stage4HeatingAirflowTempUpperOffset" to "stage4HeatingAirflowTempUpperOffset",
        "stage4CoolingAirflowTempUpperOffset" to "stage4CoolingAirflowTempUpperOffset",
        "stage4HeatingAirflowTempLowerOffset" to "stage4HeatingAirflowTempLowerOffset",
        "stage5HeatingAirflowTempUpperOffset" to "stage5HeatingAirflowTempUpperOffset",
        "stage5CoolingAirflowTempUpperOffset" to "stage5CoolingAirflowTempUpperOffset",
        "stage5HeatingAirflowTempLowerOffset" to "stage5HeatingAirflowTempLowerOffset",
        "stage5CoolingAirflowTempLowerOffset" to "stage5CoolingAirflowTempLowerOffset",

        "cmTempPercentDeadZonesAllowed" to "cmTempPercentDeadZonesAllowed",
        "perDegreeHumidityFactor" to "perDegreeHumidityFactor",
        "ccuAlarmVolumeLevel" to "ccuAlarmVolumeLevel",
        "cmHeartBeatInterval" to "cmHeartBeatInterval",
        "targetCumulativeDamper" to "vavTargetCumulativeDamper",
        "relayDeactivationHysteresis" to "vavRelayDeactivationHysteresis",
        "humidityHysteresis" to "vavHumidityHysteresis",
        "stageUpTimerCounter" to "vavStageUpTimerCounter",
        "humidityCompensationOffset" to "humidityCompensationOffset",
        "stageDownTimerCounter" to "vavStageDownTimerCounter",
        "otaStatus" to "otaStatus",
        "heartBeatsToSkip" to "heartBeatsToSkip",
        "zoneTemperatureDeadLeeway" to "zoneTemperatureDeadLeeway",
        "analogFanSpeedMultiplier" to "vavAnalogFanSpeedMultiplier",
        "cmResetCommandTimer" to "cmResetCommandTimer",
        "proportionalKFactor" to "vavProportionalKFactor",
        "temperatureIntegralTime" to "vavTemperatureIntegralTime",
        "integralKFactor" to "vavIntegralKFactor",
        "temperatureProportionalRange" to "vavTemperatureProportionalRange",
        "modeChangeoverHysteresis" to "vavModeChangeOverHysteresis",
        "fanSignal" to "fanSignal",
        "heatingSignal" to "heatingSignal",
        "coolingSignal" to "coolingSignal",
        "co2Signal" to "outsideTemperature",
        "occupancySignal" to "fanEnable"
    )
}