package a75f.io.bo.serial;

/**
 * Created by rmatt isOn 7/30/2017.
 */

public enum ErrorType
{
	BAD_PACKET_FRAMING, DBASE_FULL, CCU_UPDATE_FSV_NOT_IN_DBASE, FLUSH_FSV_NOT_IN_DBASE, GOT_PAIRING_BUT_NOT_ENABLED, GOT_PAIRING_CONFIRM_FROM_WRONG_FSV, COMMAND_NOT_RECOGNIZED, FSV_REGULAR_UPDATE_FSV_NOT_IN_DBASE, FSV_ADDRESS_NOT_MATCH_SOURCE, FSV_SETTING_REQUEST_NOT_IN_DBASE, FSV_SCHEDULE_REQUEST_NOT_IN_DBASE, FSV_SETTINGS_UPDATE_NOT_IN_DBASE, FSV_REBOOT_NOT_IN_DBASE, FSV_CLOCK_REQUEST_NOT_IN_DBASE, SN_SETTINGS_REQUEST_NOT_IN_DBASE, SN_CONTROLS_REQUEST_NOT_IN_DBASE, SN_REGULAR_UPDATE_SN_NOT_IN_DBASE, SN_FIRMWARE_METADADTA_REQUEST_NOT_IN_DBASE, SN_FIRMWARE_PACKET_REQUEST_NOT_IN_DBASE, SN_LIGHTING_SCHEDULE_REQUEST_NOT_IN_DBASE, SN_MAX_ALLOWED_LIGHTING_MODULES_EXCEEDED
}
