package a75f.io.device.serial;

/**
 * Created by ryanmattison isOn 7/26/17.
 */

public enum DamperActuator_t
{
	DAMPER_ACTUATOR_NOT_PRESENT,
	DAMPER_ACTUATOR_MAT,
	DAMPER_ACTUATOR_2_10V,
	DAMPER_ACTUATOR_0_10V,
	DAMPER_ACTUATOR_10_2V,
	DAMPER_ACTUATOR_10_0V,
	DAMPER_ACTUATOR_NOT_PRESENT_REHEAT_PULSED,
	DAMPER_ACTUATOR_NOT_PRESENT_REHEAT_ONE_STAGE,
	DAMPER_ACTUATOR_NOT_PRESENT_REHEAT_TWO_STAGE,
	DAMPER_ACTUATOR_MAT_REHEAT_2_10V,
	DAMPER_ACTUATOR_MAT_REHEAT_0_10V,
	DAMPER_ACTUATOR_MAT_REHEAT_10_2V,
	DAMPER_ACTUATOR_MAT_REHEAT_10_0V,
	DAMPER_ACTUATOR_MAT_REHEAT_PULSED,
	DAMPER_ACTUATOR_MAT_REHEAT_ONE_STAGE,
	DAMPER_ACTUATOR_MAT_REHEAT_TWO_STAGE,
	DAMPER_ACTUATOR_2_10V_REHEAT_ONE_STAGE,
	DAMPER_ACTUATOR_0_10V_REHEAT_ONE_STAGE,
	DAMPER_ACTUATOR_10_2V_REHEAT_ONE_STAGE,
	DAMPER_ACTUATOR_10_0V_REHEAT_ONE_STAGE,
	DAMPER_ACTUATOR_2_10V_REHEAT_TWO_STAGE,
	DAMPER_ACTUATOR_0_10V_REHEAT_TWO_STAGE,
	DAMPER_ACTUATOR_10_2V_REHEAT_TWO_STAGE,
	DAMPER_ACTUATOR_10_0V_REHEAT_TWO_STAGE,
	DAMPER_ACTUATOR_0_5V,
	DAMPER_ACTUATOR_0_5V_REHEAT_ONE_STAGE,
	DAMPER_ACTUATOR_0_5V_REHEAT_TWO_STAGE
}