package a75f.io.device.serial;

public enum FirmwareComponentType_t {
    FIRMWARE_COMPONENT_WIRELESS_RTH,
    FIRMWARE_COMPONENT_SMART_NODE,
    FIRMWARE_COMPONENT_CONTROL_MOTE,
    FIRMWARE_COMPONENT_ITM,
    FIRMWARE_COMPONENT_SMART_STAT_BACK,
    FIRMWARE_COMPONENT_HIA
}
