package a75f.io.device.serial;

public enum FirmwareDeviceType_t {
    FIRMWARE_DEVICE_WIRELESS_RTH ,
    FIRMWARE_DEVICE_SMART_NODE ,
    FIRMWARE_DEVICE_CONTROL_MOTE ,
    FIRMWARE_DEVICE_SMART_STAT ,
    FIRMWARE_DEVICE_SMART_STAT_REMOTE ,
    FIRMWARE_DEVICE_SMART_LITE ,
    FIRMWARE_DEVICE_SMART_STAT_BACK ,
    FIRMWARE_DEVICE_HYPERSTAT,
    FIRMWARE_DEVICE_HELIONODE,
    FIRMWARE_DEVICE_HYPERSTAT_SPLIT,
    FIRMWARE_DEVICE_CONNECT_MODULE,
    FIRMWARE_DEVICE_HYPERSTAT_INTERFACE_BOARD,
    FIRMWARE_DEVICE_MY_STAT
}
