package a75f.io.device.serial;

/**
 * Created by samjithsadasivan isOn 8/1/17.
 */

public enum FirmwareDeviceType_t
{
	FIRMWARE_DEVICE_WIRELESS_RTH,
	FIRMWARE_DEVICE_SMART_NODE,
	FIRMWARE_DEVICE_CONTROL_MOTE,
	FIRMWARE_DEVICE_SMART_STAT,
	FIRMWARE_DEVICE_SMART_STAT_REMOTE,
	FIRMWARE_DEVICE_SMART_LITE,
	FIRMWARE_DEVICE_SMART_STAT_BACK
}
