package a75f.io.device.serial;

/**
 * Created by rmatt isOn 7/30/2017.
 */

public enum MessageType
{
	FSV_PAIRING_REQ,
	CM_PAIRING_REPONSE,
	FSV_PAIRING_CONFIRM,
	CM_TO_WRM_OVER_AIR_WRM_SCHEDULE,
	CM_TO_WRM_OVER_AIR_WRM_SETTINGS,
	CM_TO_CCU_OVER_USB_WRM_REGULAR_UPDATE,
	WRM_TO_CM_OVER_AIR_WRM_SETTINGS_UPDATE,
	CCU_TO_CM_OVER_USB_WRM_PAIRING_ENABLE,
	CCU_TO_CM_OVER_USB_WRM_PAIRING_DISABLE,
	CCU_TO_CM_OVER_USB_CM_RELAY_ACTIVATION,
	CCU_TO_CM_OVER_USB_DATABASE_SEED_WRM,
	CCU_TO_CM_OVER_USB_DATABASE_FLUSH_WRM,
	CCU_TO_CM_OVER_USB_WRM_SCHEDULE,
	CCU_TO_CM_OVER_USB_WRM_SETTINGS,
	CCU_TO_CM_OVER_USB_CM_AND_WRM_CLOCK_UPDATE,
	CM_TO_CCU_OVER_USB_CM_REGULAR_UPDATE,
	FSV_REBOOT,
	WRM_TO_CM_OVER_AIR_WRM_SETTINGS_REQUEST,
	WRM_TO_CM_OVER_AIR_WRM_SCHEDULE_REQUEST,
    WRM_TO_CM_OVER_AIR_WRM_REGULAR_UPDATE,
	WRM_TO_CM_OVER_AIR_WRM_CLOCK_REQUEST,
	CM_TO_WRM_OVER_AIR_WRM_CLOCK_UPDATE,
	CM_TO_CCU_OVER_USB_ERROR_REPORT,
	CCU_TO_CM_OVER_USB_REQUEST_PAIRING_TABLE,
	CM_TO_CCU_OVER_USB_DUMP_PAIRING_TABLE,
	CCU_TO_CM_OVER_USB_CCU_HEARTBEAT,
	DEVICE_TO_CM_OVER_AIR_DEVICE_REBOOT,
	SN_TO_CM_OVER_AIR_SN_LOCAL_CONTROLS_OVERRIDE,
	CCU_TO_CM_OVER_USB_DEVICE_LOCAL_CONTROLS_OVERRIDE_ACK,
	DEVICE_TO_CM_OVER_AIR_DEVICE_SETTINGS_REQUEST,
	DEVICE_TO_CM_OVER_AIR_DEVICE_CONTROLS_REQUEST,
	CM_TO_SN_OVER_AIR_SN_SETTINGS,
	CM_TO_SN_OVER_AIR_SN_CONTROLS,
	SN_TO_CM_OVER_AIR_SN_REGULAR_UPDATE,
	CM_TO_CCU_OVER_USB_SN_REGULAR_UPDATE,
	CCU_TO_CM_OVER_USB_DATABASE_SEED_SN,
	CCU_TO_CM_OVER_USB_DATABASE_FLUSH_DEVICE,
	CCU_TO_CM_OVER_USB_SN_SETTINGS,
	CCU_TO_CM_OVER_USB_SN_CONTROLS,
	CCU_TO_CM_OVER_USB_FIRMWARE_METADATA,
	DEVICE_TO_CM_OVER_AIR_FIRMWARE_METADATA_REQUEST,
	CM_TO_DEVICE_OVER_AIR_FIRMWARE_METADATA,
	CM_TO_CCU_OVER_USB_FIRMWARE_PACKET_REQUEST,
	CCU_TO_CM_OVER_USB_FIRMWARE_PACKET,
	DEVICE_TO_CM_OVER_AIR_FIRMWARE_PACKET_REQUEST,
	CM_TO_DEVICE_OVER_AIR_FIRMWARE_PACKET,
	DEVICE_TO_CM_OVER_AIR_DEVICE_LIGHTING_SCHEDULE_REQUEST,
	CM_TO_DEVICE_OVER_AIR_DEVICE_LIGHTING_SCHEDULE,
	CCU_TO_CM_OVER_USB_DEVICE_LIGHTING_SCHEDULE,
	CCU_TO_CM_OVER_USB_DATABASE_SEED_SMART_STAT,
	CCU_TO_CM_OVER_USB_SMART_STAT_SETTINGS,
	CM_TO_SMART_STAT_OVER_AIR_SMART_STAT_SETTINGS,
	CCU_TO_CM_OVER_USB_SMART_STAT_CONTROLS,
	CM_TO_SMART_STAT_OVER_AIR_SMART_STAT_CONTROLS,
	SMART_STAT_TO_CM_OVER_AIR_SMART_STAT_LOCAL_CONTROLS_OVERRIDE,
	CM_TO_CCU_OVER_USB_SMART_STAT_LOCAL_CONTROLS_OVERRIDE,
	SMART_STAT_TO_CM_OVER_AIR_SMART_STAT_REGULAR_UPDATE,
	CM_TO_CCU_OVER_USB_SMART_STAT_REGULAR_UPDATE,
	CCU_TO_CM_OVER_USB_CM_RESET_MESSAGE,
	NUM_PROTOCOL_MESSAGE_TYPES;

	@Override
	public String toString() {
		return name();
	}
}
