package a75f.io.device.serial;

/**
 * Created by rmatt isOn 7/30/2017.
 */

public enum MessageType
{
	FSV_PAIRING_REQ,
	CM_PAIRING_REPONSE,
	FSV_PAIRING_CONFIRM,
	CM_SCHEDULE,
	CM_SETTINGS,
	FSV_REGULAR_UPDATE,
	FSV_SETTINGS_UPDATE,
	CCU_PAIRING_ENABLE,
	CCU_PAIRING_DISABLE,
	CCU_RELAY_ACTIVATION,
	CCU_PAIRING_SEED,
	CCU_PAIRING_FLUSH,
	CCU_SCHEDULE,
	CCU_SETTINGS,
	CCU_CLOCK_UPDATE,
	CM_REGULAR_UPDATE,
	FSV_REBOOT,
	FSV_SETTINGS_REQUEST,
	FSV_SCHEDULE_REQUEST,
	FSV_OVER_AIR_REGULAR_UPDATE,
	FSV_CLOCK_REQUEST,
	CM_CLOCK_UPDATE,
	CM_ERROR_REPORT,
	CCU_REQUEST_PAIRING_TABLE,
	CM_DUMP_PAIRING_TABLE,
	CCU_HEARTBEAT_UPDATE,
	
	CM_TO_CCU_OVER_USB_SN_REBOOT,
	CM_TO_CCU_OVER_USB_SN_SET_TEMPERATURE_UPDATE,
	CCU_TO_CM_OVER_USB_SN_SET_TEMPERATURE_ACK,
	SN_TO_CM_OVER_AIR_SN_SETTINGS_REQUEST,
	SN_TO_CM_OVER_AIR_SN_CONTROLS_REQUEST,
	CM_TO_SN_OVER_AIR_SN_SETTINGS,
	CM_TO_SN_OVER_AIR_SN_CONTROLS,
	SN_TO_CM_OVER_AIR_SN_REGULAR_UPDATE,
	CM_TO_CCU_OVER_USB_SN_REGULAR_UPDATE,
	CCU_TO_CM_OVER_USB_DATABASE_SEED_SN,
	CCU_TO_CM_OVER_USB_DATABASE_FLUSH_SN,
	CCU_TO_CM_OVER_USB_SN_SETTINGS,
	CCU_TO_CM_OVER_USB_SN_CONTROLS,
	CCU_TO_CM_OVER_USB_FIRMWARE_METADATA,
	SN_TO_CM_OVER_AIR_FIRMWARE_METADATA_REQUEST,
	CM_TO_SN_OVER_AIR_FIRMWARE_METADATA,
	CM_TO_CCU_OVER_USB_FIRMWARE_PACKET_REQUEST,
	CCU_TO_CM_OVER_USB_FIRMWARE_PACKET,
	SN_TO_CM_OVER_AIR_FIRMWARE_PACKET_REQUEST,
	CM_TO_SN_OVER_AIR_FIRMWARE_PACKET,
	SN_TO_CM_OVER_AIR_SN_LIGHTING_SCHEDULE_REQUEST,
	CM_TO_SN_OVER_AIR_SN_LIGHTING_SCHEDULE,
	CCU_TO_CM_OVER_USB_SN_LIGHTING_SCHEDULE,
	CCU_TO_CM_OVER_USB_DATABASE_SEED_SMART_STAT,
	CCU_TO_CM_OVER_USB_SMART_STAT_SETTINGS,
	CM_TO_SMART_STAT_OVER_AIR_SMART_STAT_SETTINGS,
	CCU_TO_CM_OVER_USB_SMART_STAT_CONTROLS,
	CM_TO_SMART_STAT_OVER_AIR_SMART_STAT_CONTROLS,
	SMART_STAT_TO_CM_OVER_AIR_SMART_STAT_LOCAL_CONTROLS_OVERRIDE,
	CM_TO_CCU_OVER_USB_SMART_STAT_LOCAL_CONTROLS_OVERRIDE,
	SMART_STAT_TO_CM_OVER_AIR_SMART_STAT_REGULAR_UPDATE,
	CM_TO_CCU_OVER_USB_SMART_STAT_REGULAR_UPDATE,
    CCU_TO_CM_OVER_USB_CM_RESET,
    CM_TO_CCU_OVER_USB_CM4_REGULAR_UPDATE,
    CCU_TO_CM_OVER_USB_CM_SETTINGS,
	CM_TO_CCU_OVER_USB_FIRMWARE_UPDATE_ACK,
	HYPERSTAT_CCU_DATABASE_SEED_MESSAGE, /* CCU->CM init */
	HYPERSTAT_REQUEST_MESSAGE, /*parameterized request message*/
	HYPERSTAT_SETTINGS_MESSAGE,
	HYPERSTAT_CONTROLS_MESSAGE,
	HYPERSTAT_REGULAR_UPDATE_MESSAGE,
	HYPERSTAT_LOCAL_CONTROLS_OVERRIDE_MESSAGE,
	HYPERSTAT_IDU_CONTROLS_MESSAGE,
	HYPERSTAT_IDU_STATUS_MESSAGE,
	HYPERSTAT_IDU_FIELD_SETTINGS_MESSAGE,
	HYPERSTAT_CCU_TO_CM_SERIALIZED_MESSAGE, /* CCU message wrapper with metadata */
	HYPERSTAT_CM_TO_CCU_SERIALIZED_MESSAGE,
	HYPERSTAT_SETTINGS2_MESSAGE,
	HYPERSTAT_SETTINGS3_MESSAGE,
	CM_TO_CCU_OTA_STATUS,
	CCU_TO_CM_FIRMWARE_UPDATE_CONTROL_MESSAGE,
	HYPERSPLIT_CCU_DATABASE_SEED_MESSAGE,
	HYPERSPLIT_SETTINGS_MESSAGE,
	HYPERSPLIT_SETTINGS2_MESSAGE,
	HYPERSPLIT_SETTINGS3_MESSAGE,
	HYPERSPLIT_CONTROLS_MESSAGE,
	HYPERSPLIT_REGULAR_UPDATE_MESSAGE,
	CCU_TO_CM_OVER_USB_SN_SETTINGS2,
	DEVICE_TO_CM_OVER_AIR_DEVICE_SETTINGS2_REQUEST,
	CM_TO_SN_OVER_AIR_SN_SETTINGS2,

	CCU_TO_CM_OVER_USB_CM_SERIAL_SETTINGS, //86
	CCU_TO_CM_OVER_USB_CM_SERIAL_CONTROLS,//87
	CM_TO_CCU_OVER_USB_CM_SERIAL_REGULAR_UPDATE, //88
	MODBUS_MESSAGE, //89
	HYPERSPLIT_SETTINGS4_MESSAGE,
	RESERVED1, // fast OTA for CM
	RESERVED2,
	MYSTAT_REQUEST_MESSAGE,
	MYSTAT_CCU_DATABASE_SEED_MESSAGE,
	MYSTAT_SETTINGS_MESSAGE,
	MYSTAT_SETTINGS2_MESSAGE,
	MYSTAT_CONTROLS_MESSAGE,
	MYSTAT_REGULAR_UPDATE_MESSAGE,
	MYSTAT_LOCAL_CONTROLS_OVERRIDE_MESSAGE;


	@Override
	public String toString() {
		return name();
	}
}