package a75f.io.device.serial;

public enum ProfileMap_t {
    PROFILE_MAP_NOT_AVAILABLE,
    PROFILE_MAP_VAV_NO_FAN,
    PROFILE_MAP_VAV_SERIES_FAN,
    PROFILE_MAP_VAV_PARALLEL_FAN,
    PROFILE_MAP_VAV_ACTIVE_CHILLED_BEAM,
    PROFILE_MAP_VAV_DUAL_DUCT,
    PROFILE_MAP_VAV_SMART_VAV,
    PROFILE_MAP_GENERIC_PI_CONTROL,
    PROFILE_MAP_BYPASS_DAMPER_CONTROL,
    PROFILE_MAP_SINGLE_STAGE_EQUIPMENT,
    PROFILE_MAP_PCN,
    PROFILE_MAP_NUM_OF
}
