# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

schedules:
  - cron: '30 18 * * *' # This cron expression represents 12:00 AM IST
    displayName: CCU Scheduled Nightly Build
    branches:
      include:
        - master

jobs:
- job: Job_1
  displayName: Build APK QA
  condition: eq(variables['isQA'], 'true')
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'
  - task: Gradle@2
    displayName: 'gradlew assembleQA'
    inputs:
      tasks: 'assembleQA'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: qaApk'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/app/build/outputs/apk/qa/'
      ArtifactName: qaApk

- job: Job_2
  displayName: Build APK Stagig
  condition: eq(variables['isStaging'], 'true')
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'      
  - task: Gradle@2
    displayName: 'gradlew assembleStaging'
    inputs:
      tasks: assembleStaging
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: StagingApk'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/app/build/outputs/apk/staging/'
      ArtifactName: StagingApk

- job: Job_3
  displayName: Build APK Prod
  condition: eq(variables['isProd'], 'true')
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'       
  - task: Gradle@2
    displayName: 'gradlew assembleProd'
    inputs:
      tasks: 'assembleProd'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: ProdApk'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/app/build/outputs/apk/prod/'
      ArtifactName: ProdApk
      
- job: Job_4
  displayName: Build APK Carrier
  condition: eq(variables['isCarrier'], 'true')
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'       
  - task: Gradle@2
    displayName: 'gradlew assembleCarrier_prod'
    inputs:
      tasks: 'assembleCarrier_prod'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Carrier_prodApk'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/app/build/outputs/apk/carrier_prod/'
      ArtifactName: Carrier_prodApk

- job: Job_5
  displayName: Build APK Airoverse
  condition: eq(variables['isAiroverse'], 'true')
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'       
  - task: Gradle@2
    displayName: 'gradlew assembleAiroverse_prod'
    inputs:
      tasks: 'assembleAiroverse_prod'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Airoverse_prodApk'
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/app/build/outputs/apk/airoverse_prod/'
      ArtifactName: Airoverse_prodApk



