package a75f.io.logic.bo.building;

import com.fasterxml.jackson.annotation.JsonIgnore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;

import a75f.io.api.haystack.CCUHsApi;
import a75f.io.api.haystack.Tags;
import a75f.io.logic.L;
import a75f.io.logic.bo.building.definitions.ProfileType;
import a75f.io.logic.bo.building.definitions.RoomDataInterface;

/**
 * Created by Yinten isOn 8/15/2017.
 */
//Also known as room.
public class Zone
{
    public  String                  roomName          = "Default Zone";
    public  ArrayList<ZoneProfile>  mZoneProfiles     = new ArrayList<>();
    private HashMap<String, Object> mTuningParameters = new HashMap<>();
    @JsonIgnore
    private RoomDataInterface mRoomDataInterface;
    public String          mZoneRef;
    
    public Zone()
    {
    }
    
    //Also known as zone name.
    public Zone(String zoneName, Floor f)
    {
        this.roomName = zoneName;
        HashMap siteMap = CCUHsApi.getInstance().read(Tags.SITE);
        a75f.io.api.haystack.Zone hsZone = new a75f.io.api.haystack.Zone.Builder()
                                                     .setDisplayName(zoneName)
                                                     .setFloorRef(f.mFloorRef)
                                                     .setSiteRef(siteMap.get("id").toString())
                                                     .build();
        mZoneRef = CCUHsApi.getInstance().addZone(hsZone);
    }
    
    @JsonIgnore
    public ArrayList<Output> getOutputs(short address)
    {
        ArrayList<Output> retVal = new ArrayList<>();
        for (ZoneProfile zp : mZoneProfiles)
        {
            BaseProfileConfiguration profileConfiguration = zp.getProfileConfiguration(address);
            if (profileConfiguration != null)
            {
                retVal.addAll(profileConfiguration.getOutputs());
            }
        }
        return retVal;
    }
    
    @Override
    @JsonIgnore
    public String toString()
    {
        return roomName;
    }
    
    @JsonIgnore
    public ZoneProfile findProfile(ProfileType profileType)
    {
        ZoneProfile retVal = null;
        for (ZoneProfile zoneProfile : mZoneProfiles)
        {
            if(zoneProfile.getProfileType().equals(profileType))
            {
                return zoneProfile;
            }
        }
        
        

        return retVal;
    }
    
    public double getDesiredVal(ZoneProfile z) {
        //TODO- TEMP
        return 72.0;
        /*float desiredTemperature = LZoneProfile.resolveZoneProfileLogicalValue(z);
        boolean occupied = desiredTemperature > 0;
        if (!occupied)
        {
            desiredTemperature = LZoneProfile.resolveAnyValue(z);
        }
        return desiredTemperature;*/
    }
    
    @JsonIgnore
    public void removeNodeAndClearAssociations(Short selectedModule)
    {
        for (ZoneProfile zp : mZoneProfiles)
        {
            if (zp.getProfileConfiguration(selectedModule) != null)
            {
                zp.removeProfileConfiguration(selectedModule);
            }
            L.removeHSDeviceEntities(selectedModule);
        }
    }
    
    public HashSet<Short> getNodes()
    {
        HashSet<Short> addresses = new HashSet<Short>();
        for (ZoneProfile zp : mZoneProfiles)
        {
            addresses.addAll(zp.getNodeAddresses());
        }
        return addresses;
    }
    
    public HashMap<String, Object> getTuningParameters()
    {
        return mTuningParameters;
    }
    
    public void setTuningParameters(HashMap<String, Object> tuningParameters)
    {
        this.mTuningParameters = tuningParameters;
    }
    
    @JsonIgnore
    public double getZoneCurrentTemp()
    {
        for (ZoneProfile zp : mZoneProfiles)
        {
         return zp.getAverageZoneTemp();
        }
        
        return 72; //TEMP
    }
    
    @JsonIgnore
    public double getZoneDesiredTemp()
    {
        return 72;//TODO - TEMP
    }
    
    @JsonIgnore
    public double getZoneTempTarget() //Humidity compensated
    {
        return 72;//TODO - TEMP
    }
    
    @JsonIgnore
    public void setRoomDataInterface(RoomDataInterface roomDataInterface)
    {
        this.mRoomDataInterface = roomDataInterface;
    }
    
    /*@JsonIgnore
    public ZonePriority getPriority() {
    
        int p = 0;
        for (ZoneProfile zoneProfile : mZoneProfiles)
        {
            if (zoneProfile.getPriority() > p) {
                p = zoneProfile.getPriority();
            }
        }
        return ZonePriority.values()[p];
    }
    
    @JsonIgnore
    public double getDynamicPriority(int ciTarget) {
        
        if (getZoneCurrentTemp() == 0) {
            return getPriority().ordinal();
        }
        *//* Dynamic priority is generated by multiplying zone priority by 1.3 for every multiple of comfort slider value away
           from desired. The idea is that occupants in a zone that is further away from the desired are exponentially more
           likely to feel uncomfortable
         *//*
        return Math.pow(1.3 , (Math.abs(getZoneCurrentTemp() - getZoneDesiredTemp())/ciTarget));
    }*/
    
    //Scratch
    //    @JsonIgnore
    //    public Output findPort(Port port, short smartNodeAddress)
    //    {
    //        for (Output output : getOutputs(smartNodeAddress))
    //        {
    //            if (output.getPort() == port)
    //            {
    //                output.mConfigured = true;
    //                return output;
    //            }
    //        }
    //        Output output = new Output();
    //        output.setPort(port);
    //        output.setAddress(smartNodeAddress);
    //        output.mConfigured = false;
    //        return output;
    //    }
}