package a75f.io.bo.building.definitions;

/**
 * Created by Yinten on 9/20/2017.
 */

public class AlgoTuningParameters
{
    static final String KINVEY_COLLECTION_NAME = "00AlgoTuningParameters";
    static final int    ALGO_TUNERS_VERSION    = 62;
    
    static final int     ZONE_DEAD_TIME                    = 15;
    static final int     BUILDING_TO_ZONE_DIFF             = 3;
    static final int     CM_HEART_BEAT_INTERVAL            = 1;
    static final int     HEART_BEAT_TO_SKIP                = 5;
    static final double  AUTO_MODE_CHANGE_OVER_MULTIPLER   = 1.0;
    static final int     AUTO_WAY_TIME                     = 60;
    static final int     REBALANCE_HOLD_TIME               = 20;
    static final int     FORCED_OCCUPIED_TIME              = 120;
    static final int     COOLING_AIRFLOW_TEMP              = 60;
    static final int     HEATING_AIRFLOW_TEMP              = 105;
    static final int     COOLING_AIRFLOW_TEMP_LOWER_OFFSET = -20;
    static final int     COOLING_AIRFLOW_TEMP_UPPER_OFFSET = -8;
    static final int     HEATING_AIRFLOW_TEMP_LOWER_OFFSET = 25;
    static final int     HEATING_AIRFLOW_TEMP_UPPER_OFFSET = 40;
    static final int     AIRFLOW_TEMP_BREACH_HOLD_DOWN     = 5;
    static final int     HUMIDITY_THRESHOLD                = 35;
    static final int     HUMIDITY_COMP_FACTOR              = 10;
    static final boolean USE_SAME_OCCU_TEMP_ACROSS_DAYS    = true;
    static final int     DCV_CO2_THRESHOLD_LEVEL           = 1000;
    static final int     DCV_DAMPER_OPENING_RATE           = 10;
    static final int     DUMB_MODE_DCV_DAMPER_OPENING      = 30;
    static final int     ABNORMAL_CUR_TEMP_TRIGGER_VAL     = 4;
    static final int     USER_LIMIT_SPREAD                 = 3;
    static final int     PRECONDTION_RATE                  = 15;
    static final double  SETBACK_MULTIPLIER                = 1.5;
    static final int     ENTHALPY_COMPENSATION             = 0;
    static final int     OUTSIDE_AIR_MIN_TEMP              = 0;
    static final int     OUTSIDE_AIR_MAX_TEMP              = 70;
    public static final int     OUTSIDE_AIR_MIN_HUMIDITY          = 10;
    static final int     OUTSIDE_AIR_MAX_HUMIDITY          = 95;
    static final int     ECONOMIZER_LOAD_THRESHOLD         = 30;
    static final int     ECONOMIZER_HOLDTIME               = 15;
    static final int     ECONOMIZER_LOAD_DROP              = 30;
    
    static final double  ANALOG_FAN_SPEED_MULTIPLIER              = 1.0;
    static final int     ANALOG_MIN_HEATING                       = 50;
    static final int     ANALOG_MAX_HEATING                       = 20;
    static final int     ANALOG_MIN_COOLING                       = 70;
    static final int     ANALOG_MAX_COOLING                       = 100;
    //default values for algo tuners
    static final double  PC_CONST                                 = 0.5; //prpcontrlConstant
    static final double  IC_CONST                                 = 0.5; // mIntegCtrlConstant
    static final int     CUM_DAMPER_POS_TARGET                    = 70;
    static final int     IC_TIMEOUT                               = 30;
    static final double  PC_SPREAD                                = 2.0;
    static final double  PC_MULTIPLIER                            = 2.0;
    static final int     DXCOIL_HOLD_TIME_MULITPLIER              = 2;
    static final int     PERCENT_DEAD_ZONES                       = 50;
    static final double  DXCOIL_OFFSET_LIMIT_MULTIPLIER           = 0.5;
    static final double  DXCOIL_OFFSET_HEAT_OFFSET                = 0.0;
    static final double  DXCOIL_OFFSET_COOL_OFFSET                = 0.0;
    static final int     CLOCK_INTERVAL                           = 15;
    static final double  BACK_PRESSURE_LIMIT                      = 2.5;
    static final int     CUM_DAMPERPOS_INC_BP                     = 5;
    static final int     MULTI_ZONE_STAGE2_TIMER                  = 15;
    static final int     SINGLE_ZONE_STAGE2_TIMER                 = 2;
    static final int     MULTI_ZONE_STAGE2_PDROP                  = 50;
    static final int     SINGLE_ZONE_STAGE2_OFFSET                = 2;
    static final int     IGNORE_CM_REPORT_ERR                     = 1;
    static final int     IGNORE_FSV_NOT_INDBERR                   = 1;
    static final int     SHOW_RPM_ALERTS                          = 0;
    static final int     FORCED_OCCUPIED_ZONE_PRIORITY            = 50000;
    static final int     ZONE_PRIORITY_SPREAD                     = 2;
    static final double  ZONE_PRIORITY_MULTIPLIER                 = 1.3;
    static final int     ECON_IC_TIMEOUT                          = 30;
    static final double  ECON_PC_SPREAD                           = 2.0;
    static final double  ANALOG1_PC_CONST                         = 0.5;
    static final double  ANALOG1_IC_CONST                         = 0.5;
    static final int     ANALOG1_IC_TIMEOUT                       = 30;
    static final double  ANALOG1_PC_SPREAD                        = 2.0;
    static final double  ANALOG3_PC_CONST                         = 0.5;
    static final double  ANALOG3_IC_CONST                         = 0.5;
    static final int     ANALOG3_IC_TIMEOUT                       = 30;
    static final double  ANALOG3_PC_SPREAD                        = 2.0;
    static final double  AUTO_MODE_COOL_HEAT_DXCILIMIT            = 2.0;
    static final double  AUTO_MODE_TOTAL_DXCILIMIT                = 0.2;
    static final boolean USE_COOLHEAT_DXCI_AUTOMODE               = false;
    static final boolean USE_INSTANT_GRATIFICATION_MODE           = false;
    static final boolean FOLLOW_AUTO_SCHEDULE                     = false;
    static final boolean USE_OUTSIDE_TEMP_LOCKOUT                 = false;
    static final boolean USE_CELSIUS                              = false;
    static final boolean USE_MILITARY_TIME                        = false;
    static final boolean SN_INSTALL                               = false;
    static final int     FSV_START_ADDRESS                        = 1000;
    static final int     NO_HEATING_ABOVE                         = 80;
    static final int     NO_COOLING_BELOW                         = 60;
    static final int     ZONE_DUMB_TEMP                           = 3; //curTemp * 1.5
    static final int     STAGE1_FAN_ONTIME                        = 5;
    static final int     STAGE1_FAN_OFFTIME                       = 0;
    static final int     BUILDING_MAX_TEMP                        = 85; // in deg F
    static final int     BUILDING_MIN_TEMP                        = 60; // in deg F
    static final int     USER_MAX_TEMP                            = 73; //in deg F
    static final int     USER_MIN_TEMP                            = 70; //in def F
    static final int     WRM_FOR_HUMIDITY_VALUE                   = 0;
    static final boolean USE_EXT_HUMIDITY_SENSOR                  = false;
    static final int     EXT_HUMIDITY_SENSOR_MIN_SP               = 30;
    static final int     EXT_HUMIDITY_SENSOR_MAX_SP               = 70;
    static final int     EXT_HUMIDITY_SENSOR_SP_TIMEOUT           = 60;
    static final int     WRM_FOR_DUMB_MODE_TEMP_VALUE             = 0;
    static final int     NO2_THRESHOLD_LEVEL                      = 5;
    static final int     CO_THRESHOLD_LEVEL                       = 50;
    static final int     NO2_DAMPER_OPENING_RATE                  = 20;
    static final int     CO_DAMPER_OPENING_RATE                   = 10;
    static final int     OAO_DAMPER_POS_MIN                       = 0;
    static final int     OAO_DAMPER_POS_MAX                       = 100;
    static final int     OAO_EXHAUST_FAN_THRESHOLD                = 50;
    static final double  PRESSURE_THRESHOLD_LEVEL                 = 0.01;
    static final int     PRESSURE_DAMPER_OPENING_RATE             = 5;
    static final int     ANALOG1_MIN_VALUE                        = 0;
    static final int     ANALOG1_MAX_VALUE                        = 10;
    static final int     ANALOG3_MIN_VALUE                        = 0;
    static final int     ANALOG3_MAX_VALUE                        = 10;
    static final int     COOLING_AIRFLOW_TEMP_STAGE2_LOWER_OFFSET = -25;
    static final int     COOLING_AIRFLOW_TEMP_STAGE2_UPPER_OFFSET = -12;
    static final int     HEATING_AIRFLOW_TEMP_STAGE2_LOWER_OFFSET = 35;
    static final int     HEATING_AIRFLOW_TEMP_STAGE2_UPPER_OFFSET = 50;
    static final int     CHILLED_WATER_DELTAT_SETPOINT            = 10;
    static final int     CHILLED_WATER_FLOW_SETPOINT              = 100;
    static final int     CHILLED_WATER_MAX_FLOWRATE               = 100;
    static final int     CHILLED_WATER_ACTUATOR_MIN_POS           = 0;
    static final int     CHILLED_WATER_ACTUATOR_MAX_POS           = 100;
    static final int     AHU_FAN_MIN_LIMIT                        = 0;
    static final int     AHU_FAN_MAX_LIMIT                        = 100;
    static final boolean ENERGY_METER_MONITOR                     = false;
    static final        double PRESSURE_DEAD_ZONE                       = 0.01;
    static final        double REHEAT_OFFSET                            = 1.0;
    static final        int    REFRIGERATION_LOWER_LIMIT                = 23;
    static final        int    REFRIGERATION_HIGHER_LIMIT               = 45;
    static final        double REHEAT_DAMPER_REOPEN_OFFSET              = 2.0;
    static final        int    REHEAT_MAX_DAMPER_POS                    = 40;
    static final        int    ALARM_VOLUME_DEFAULT                     = 0; //Max volume limit is 7;
    public static final int    LIGHTING_INTENSITY_OCCUPANT_DETECTED     = 75;
    public static final int    MIN_LIGHTING_CONTROL_OVERRIDE_IN_MINUTES = 20;
    public static final int SSE_Cooling_Deadband = 1;  //(°F)
    public static final int SSE_Heating_Deadband = 1;  //(°F)
}
