package a75f.io.logic

const val COOLINGLOOPOUTPUTID = 8
const val HEATINGLOOPOUTPUTID = 31
const val FANLOOPOUTPUTID = 22
const val CO2LOOPOUTPUTID = 6
const val OUTSIDETEMPERATUREID = 43
const val HUMIDITYID = 38
const val OUTSIDEHUMIDITYID = 42
const val CMHEATINGDESIREDTEMPID = 19
const val CMCOOLINGDESIREDTEMPID = 20
const val CURRENTTEMPID = 14
const val AVERAGETEMPERATUREID =3
const val AVERAGEHUMIDITYID = 2
const val COOLINGSTAGE1ID = 9
const val COOLINGSTAGE2ID =10
const val COOLINGSTAGE3ID = 11
const val COOLINGSTAGE4ID = 12
const val COOLINGSTAGE5ID =13
const val HEATINGSTAGE1ID = 32
const val HEATINGSTAGE2ID = 33
const val HEATINGSTAGE3ID = 34
const val HEATINGSTAGE4ID = 35
const val HEATINGSTAGE5ID = 36
const val FANSTAGE1ID = 53
const val FANSTAGE2ID = 54
const val FANSTAGE3ID = 55
const val FANSTAGE4ID = 27
const val FANSTAGE5ID = 28
const val HUMIDIFIERENABLEDID = 37
const val DEHUMIDIFIERENABLEDID = 16
const val CONDITIONINGMODEID = 46
const val OPERATIONMODEID = 47
const val FANSIGNALID = 23
const val HEATINGSIGNALID = 30
const val CHWVALVESIGNALID = 80
const val COOLINGSIGNALID = 7
const val COMPOSITESIGNALID= 82

const val DESIREDTEMPID= 18
const val CO2ID = 4
const val VOCID = 45
const val TEMPERATUREOFFSETID = 17
const val DAMPER1POSID = 66
const val DAMPER2POSID = 67
const val SUPPLYAIRTEMP1ID = 1
const val SUPPLYAIRTEMP2ID = 68
const val PRESSUREID = 69
const val DAMPERFEEDBACKID = 70
const val REHEATCMDID = 71
const val AIRFLOWID = 72
const val AIRVELOCITYID = 73
const val COMPOSITEDAMPERID = 74
const val SERIESFANID = 78

const val CO2SIGNALID = 81
const val DISCHARGESPID = 77
const val ENTERINGAIRTEMPID = 76
const val PARALLELFANID = 79
const val EXTERNAL10KTEMPSENSORTH2ID = 75
const val OCCUPANCYID = 40
const val FANSPEEDID = 21
const val DUCTSTATICPRESSURE= 83


const val HEARTBEATID= 29

