package a75f.io.domain.api

/**
 * List of all known domain names.
 * Camel case naming is followed to keep the names more relatable to the actual domain names.
 */

object DomainName {
    //Tuners
    const val userLimitSpread = "userLimitSpread"
    const val heatingPreconditioningRate = "heatingPreconditioningRate"
    const val coolingPreconditioningRate = "coolingPreconditioningRate"
    const val cmTempPercentDeadZonesAllowed = "cmTempPercentDeadZonesAllowed"
    const val airflowSampleWaitTime = "airflowSampleWaitTime"
    const val clockUpdateInterval = "clockUpdateInterval"
    const val perDegreeHumidityFactor = "perDegreeHumidityFactor"
    const val ccuAlarmVolumeLevel = "ccuAlarmVolumeLevel"
    const val cmHeartBeatInterval = "cmHeartBeatInterval"
    const val heartBeatsToSkip = "heartBeatsToSkip"
    const val cmResetCommandTimer = "cmResetCommandTimer"
    const val zoneTemperatureDeadLeeway = "zoneTemperatureDeadLeeway"
    const val humidityCompensationOffset = "humidityCompensationOffset"
    const val proportionalKFactor = "proportionalKFactor"
    const val integralKFactor = "integralKFactor"
    const val pidIntegralTime = "pidIntegralTime"
    const val demandResponseSetback = "demandResponseSetback"

    const val rebalanceHoldTime = "rebalanceHoldTime"
    const val constantTempAlertTime = "constantTempAlertTime"
    const val abnormalCurTempRiseTrigger = "abnormalCurTempRiseTrigger"
    const val heatingAirflowTemp = "heatingAirflowTemp"
    const val coolingAirflowTemp = "coolingAirflowTemp"
    const val adrHeatingDeadband = "adrHeatingDeadband"
    const val adrCoolingDeadband = "adrCoolingDeadband"
    const val autoAwayTime = "autoAwayTime"
    const val forcedOccupiedTime = "forcedOccupiedTime"
    const val zoneDeadTime = "zoneDeadTime"
    const val displayUnit = "displayUnit"
    const val autoAwaySetback = "autoAwaySetback"
    const val ccuNetworkWatchdogTimeout = "ccuNetworkWatchdogTimeout"
    const val auxHeating1Activate = "auxHeating1Activate"
    const val auxHeating2Activate = "auxHeating2Activate"
    const val waterValveSamplingWaitTime = "waterValveSamplingWaitTime"
    const val waterValveSamplingOnTime = "waterValveSamplingOnTime"
    const val waterValveSamplingLoopDeadbandOnTime = "waterValveSamplingLoopDeadbandOnTime"
    const val waterValveSamplingLoopDeadbandWaitTime = "waterValveSamplingLoopDeadbandWaitTime"
    const val buildingLimitAlertTimer = "buildingLimitAlertTimer"
    const val temperatureMode = "temperatureMode"

    const val dabAdvancedHybridAhuV2_connectModule = "dabAdvancedHybridAhuV2_connectModule"
    const val connectModuleDevice = "connectModuleDevice"

    // Profiles
    const val vavReheatNoFan = "vavReheatNoFan"
    const val vavReheatParallelFan = "vavReheatParallelFan"
    const val vavReheatSeriesFan = "vavReheatSeriesFan"
    const val activeChilledBeam = "activeChilledBeam"
    const val hyperstatSplitCPU = "hyperstatSplitCPU"

    // Devices
    const val hyperstatSplitDevice = "hyperstatSplitDevice"

    //DAB
    const val smartnodeDAB = "smartnodeDAB"
    const val helionodeDAB = "helionodeDAB"
    const val dabTargetCumulativeDamper = "dabTargetCumulativeDamper"
    const val dabAnalogFanSpeedMultiplier = "dabAnalogFanSpeedMultiplier"
    const val dabHumidityHysteresis = "dabHumidityHysteresis"
    const val dabRelayDeactivationHysteresis = "dabRelayDeactivationHysteresis"
    const val dabRebalanceHoldTime = "rebalanceHoldTime"
    const val dabModeChangeoverHysteresis = "dabModeChangeOverHysteresis"
    const val dabStageUpTimerCounter = "dabStageUpTimerCounter"
    const val dabStageDownTimerCounter = "dabStageDownTimerCounter"
    const val dabProportionalKFactor = "dabProportionalKFactor"
    const val dabIntegralKFactor = "dabIntegralKFactor"
    const val dabTemperatureProportionalRange = "dabTemperatureProportionalRange"
    const val dabTemperatureIntegralTime = "dabTemperatureIntegralTime"
    const val dabOutsideTempCoolingLockout = "dabOutsideTempCoolingLockout"
    const val dabOutsideTempHeatingLockout = "dabOutsideTempHeatingLockout"
    const val dabZonePrioritySpread = "dabZonePrioritySpread"
    const val dabZoneVocTarget = "dabZoneVocTarget"
    const val dabZoneVocThreshold = "dabZoneVocThreshold"
    const val dabZoneCo2Target = "dabZoneCo2Target"
    const val dabZonePriorityMultiplier = "dabZonePriorityMultiplier"
    const val dabCoolingDeadband = "dabCoolingDeadband"
    const val dabZoneCo2Threshold = "dabZoneCo2Threshold"
    const val dabHeatingDeadband = "dabHeatingDeadband"
    const val dabCoolingDeadbandMultiplier = "dabCoolingDeadbandMultiplier"
    const val dabReheatRelayActivationHysteresis = "dabReheatRelayActivationHysteresis"
    const val dabReheatTemperatureIntegralTime = "dabReheatTemperatureIntegralTime"
    const val reheatTempOffset = "reheatTempOffset"
    const val dabReheatTemperatureProportionalRange = "dabReheatTemperatureProportionalRange"
    const val dabReheatIntegralKFactor = "dabReheatIntegralKFactor"
    const val dabReheatProportionalKFactor = "dabReheatProportionalKFactor"
    const val reheatProportionalKFactor = "reheatProportionalKFactor"

    const val dabSupplyAirTemperatureProportionalKFactor = "dabSupplyAirTemperatureProportionalKFactor"
    const val dabSupplyAirTemperatureProportionalRange = "dabSupplyAirTemperatureProportionalRange"
    const val dabSupplyAirTemperatureIntegralTime = "dabSupplyAirTemperatureIntegralTime"
    const val dabSupplyAirTemperatureIntegralKFactor = "dabSupplyAirTemperatureIntegralKFactor"

    const val dabDuctStaticPressureProportionalKFactor = "dabDuctStaticPressureProportionalKFactor"
    const val dabDuctStaticPressureProportionalRange = "dabDuctStaticPressureProportionalRange"
    const val dabDuctStaticPressureIntegralTime = "dabDuctStaticPressureIntegralTime"
    const val dabDuctStaticPressureIntegralKFactor = "dabDuctStaticPressureIntegralKFactor"


    //VAV
    const val vavTargetCumulativeDamper = "vavTargetCumulativeDamper"
    const val vavAnalogFanSpeedMultiplier = "vavAnalogFanSpeedMultiplier"
    const val vavHumidityHysteresis = "vavHumidityHysteresis"
    const val vavRelayDeactivationHysteresis = "vavRelayDeactivationHysteresis"
    const val vavRebalanceHoldTime = "vavRebalanceHoldTime"
    const val vavModeChangeoverHysteresis = "vavModeChangeoverHysteresis"
    const val vavStageUpTimerCounter = "vavStageUpTimerCounter"
    const val vavStageDownTimerCounter = "vavStageDownTimerCounter"
    const val vavProportionalKFactor = "vavProportionalKFactor"
    const val vavIntegralKFactor = "vavIntegralKFactor"
    const val vavTemperatureProportionalRange = "vavTemperatureProportionalRange"
    const val vavTemperatureIntegralTime = "vavTemperatureIntegralTime"
    const val vavOutsideTempCoolingLockout = "vavOutsideTempCoolingLockout"
    const val vavOutsideTempHeatingLockout = "vavOutsideTempHeatingLockout"

    const val vavSupplyAirTemperatureProportionalKFactor = "vavSupplyAirTemperatureProportionalKFactor"
    const val vavSupplyAirTemperatureProportionalRange = "vavSupplyAirTemperatureProportionalRange"
    const val vavSupplyAirTemperatureIntegralTime = "vavSupplyAirTemperatureIntegralTime"
    const val vavSupplyAirTemperatureIntegralKFactor = "vavSupplyAirTemperatureIntegralKFactor"

    const val vavDuctStaticPressureProportionalKFactor = "vavDuctStaticPressureProportionalKFactor"
    const val vavDuctStaticPressureProportionalRange = "vavDuctStaticPressureProportionalRange"
    const val vavDuctStaticPressureIntegralTime = "vavDuctStaticPressureIntegralTime"
    const val vavDuctStaticPressureIntegralKFactor = "vavDuctStaticPressureIntegralKFactor"

    //VAV-Zone
    const val damperType = "damperType"
    const val damperSize = "damperSize"
    const val damperShape = "damperShape"
    const val reheatType = "reheatType"
    const val zonePriority = "zonePriority"
    const val autoForceOccupied = "autoForceOccupied"
    const val autoAway = "autoAway"
    const val prePurgeEnable = "prePurgeEnable"
    const val prePurgeStatus = "prePurgeStatus"
    const val enableIAQControl = "enableIAQControl"
    const val enableCo2Control = "enableCo2Control"
    const val enableCFMControl = "enableCFMControl"
    const val temperatureOffset = "temperatureOffset"
    const val minHeatingDamperPos = "minHeatingDamperPos"
    const val maxHeatingDamperPos = "maxHeatingDamperPos"
    const val minCoolingDamperPos = "minCoolingDamperPos"
    const val maxCoolingDamperPos = "maxCoolingDamperPos"
    const val kFactor = "kFactor"
    const val minCFMCooling = "minCFMCooling"
    const val maxCFMCooling = "maxCFMCooling"
    const val minCFMReheating = "minCFMReheating"
    const val maxCFMReheating = "maxCFMReheating"

    const val vavIntegralKfactor = "vavIntegralKFactor"
    const val vavZoneVocTarget = "vavZoneVocTarget"
    const val vavZoneCo2Threshold = "vavZoneCo2Threshold"
    const val vavZoneCo2Target = "vavZoneCo2Target"
    const val vavCoolingDeadband = "vavCoolingDeadband"
    const val vavHeatingDeadband = "vavHeatingDeadband"
    const val vavZoneVoCThreshold = "vavZoneVocThreshold"
    const val valveActuationStartDamperPosDuringSysHeating = "valveActuationStartDamperPosDuringSysHeating"
    const val vavHeatingDeadbandMultiplier = "vavHeatingDeadbandMultiplier"
    const val vavCoolingDeadbandMultiplier = "vavCoolingDeadbandMultiplier"
    const val fanControlOnFixedTimeDelay = "fanControlOnFixedTimeDelay"
    const val reheatZoneMaxDischargeTemp = "reheatZoneMaxDischargeTemp"
    const val reheatZoneToDATMinDifferential = "reheatZoneToDATMinDifferential"
    const val reheatZoneDischargeTempOffset = "reheatZoneDischargeTempOffset"
    const val vavModeChangeOverHysteresis = "vavModeChangeOverHysteresis"
    const val vavZonePrioritySpread = "vavZonePrioritySpread"
    const val vavZonePriorityMultiplier = "vavZonePriorityMultiplier"
    const val dabHeatingDeadbandMultiplier = "dabHeatingDeadbandMultiplier"
    const val vavReheatRelayActivationHysteresis = "vavReheatRelayActivationHysteresis"

    //ACB-Zone
    const val valveType = "valveType"
    const val thermistor2Type = "thermistor2Type"
    const val condensateNC = "condensateNC"
    const val condensateNO = "condensateNO"
    const val chilledWaterValve = "chilledWaterValveCoolCmdPoint"
    const val chilledWaterValveIsolationCmdPointNO = "chilledWaterValveIsolationCmdPointNO"
    const val chilledWaterValveIsolationCmdPointNC = "chilledWaterValveIsolationCmdPointNC"
    const val relayActivationHysteresis = "relayActivationHysteresis"

    //VAV-TR
    const val satSPInit = "satSpInit"
    const val satSPMin = "satSpMin"
    const val satSPMax = "satSpMax"
    const val satTimeDelay = "satTimeDelay"
    const val satTimeInterval = "satTimeInterval"
    const val satIgnoreRequest = "satIgnoreRequest"
    const val satSPTrim = "satSpTrim"
    const val satSPRes = "satSpRes"
    const val satSPResMax = "satSpResMax"
    const val staticPressureSPInit = "staticPressureSpInit"
    const val staticPressureSPMin = "staticPressureSpMin"
    const val staticPressureSPMax = "staticPressureSpMax"
    const val staticPressureTimeDelay = "staticPressureTimeDelay"
    const val staticPressureTimeInterval = "staticPressureTimeInterval"
    const val staticPressureIgnoreRequest = "staticPressureIgnoreRequest"
    const val staticPressureSPTrim = "staticPressureSpTrim"
    const val staticPressureSPRes = "staticPressureSpRes"
    const val staticPressureSPResMax = "staticPressureSpResMax"
    const val co2SPInit = "co2SpInit"
    const val co2SPMin = "co2SpMin"
    const val co2SPMax = "co2SpMax"
    const val co2TimeDelay = "co2TimeDelay"
    const val co2TimeInterval = "co2TimeInterval"
    const val co2IgnoreRequest = "co2IgnoreRequest"
    const val co2SPTrim = "co2SpTrim"
    const val co2SPRes = "co2SpRes"
    const val co2SPResMax = "co2SpResMax"

    const val vavAirflowCFMIntegralKFactor = "vavAirFlowCFMIntegralKFactor"
    const val vavAirflowCFMProportionalKFactor = "vavAirFlowCFMProportionalKFactor"
    const val vavAirflowCFMIntegralTime = "vavAirFlowCFMIntegralTime"
    const val vavAirflowCFMProportionalRange = "vavAirflowCFMProportionalRange"


    const val standaloneCoolingDeadband = "standaloneCoolingDeadband"
    const val standaloneHeatingDeadband = "standaloneHeatingDeadband"
    const val standaloneStage2CoolingLowerOffset = "standaloneStage2CoolingLowerOffset"
    const val standaloneStage1HeatingUpperOffset = "standaloneStage1HeatingUpperOffset"
    const val standaloneStage1HeatingLowerOffset = "standaloneStage1HeatingLowerOffset"
    const val standaloneVocThreshold = "standaloneVocThreshold"
    const val standaloneCoolingPreconditioningRate = "standaloneCoolingPreconditioningRate"
    const val standaloneHeatingPreconditioningRate = "standaloneHeatingPreconditioningRate"
    const val standaloneStage1CoolingUpperOffset = "standaloneStage1CoolingUpperOffset"
    const val standaloneCo2Target = "standaloneCo2Target"
    const val standaloneAirflowSampleWaitTime = "standaloneAirflowSampleWaitTime"
    const val standaloneStage1Hysteresis = "standaloneStage1Hysteresis"
    const val standaloneStage1CoolingLowerOffset = "standaloneStage1CoolingLowerOffset"
    const val standaloneCo2Threshold = "standaloneCo2Threshold"
    const val standaloneVocTarget = "standaloneVocTarget"
    const val standaloneCoolingDeadbandMultiplier = "standaloneCoolingDeadbandMultiplier"
    const val standaloneHeatingDeadbandMultiplier = "standaloneHeatingDeadbandMultiplier"
    const val standaloneStage2CoolingUpperOffset = "standaloneStage2CoolingUpperOffset"
    const val standaloneTemperatureProportionalRange = "standaloneTemperatureProportionalRange"
    const val standaloneStage2HeatingLowerOffset = "standaloneStage2HeatingLowerOffset"
    const val standaloneProportionalKFactor = "standaloneProportionalKFactor"
    const val standaloneRelayActivationHysteresis = "standaloneRelayActivationHysteresis"
    const val standaloneHumidityHysteresis = "standaloneHumidityHysteresis"
    const val standaloneTemperatureIntegralTime = "standaloneTemperatureIntegralTime"
    const val standaloneAnalogFanSpeedMultiplier = "standaloneAnalogFanSpeedMultiplier"
    const val standaloneStage2HeatingUpperOffset = "standaloneStage2HeatingUpperOffset"
    const val standaloneIntegralKFactor = "standaloneIntegralKFactor"
    const val minFanRuntimePostConditioning = "minFanRuntimePostConditioning"

    //TI
    const val tiCoolingDeadbandMultiplier = "tiCoolingDeadbandMultiplier"
    const val tiHeatingDeadband = "tiHeatingDeadband"
    const val tiIntegralKFactor = "tiIntegralKFactor"
    const val tiTemperatureIntegralTime = "tiTemperatureIntegralTime"
    const val tiHeatingDeadbandMultiplier = "tiHeatingDeadbandMultiplier"
    const val tiTemperatureProportionalRange = "tiTemperatureProportionalRange"
    const val tiZonePriorityMultiplier = "tiZonePriorityMultiplier"
    const val tiZonePrioritySpread = "tiZonePrioritySpread"
    const val tiCoolingDeadband = "tiCoolingDeadband"
    const val tiProportionalKFactor = "tiProportionalKFactor"

    //OAO

    const val outsideDamperMixedAirMinimum = "outsideDamperMixedAirMinimum"
    const val economizingToMainCoolingLoopMap = "economizingToMainCoolingLoopMap"
    const val systemPrePurgeFanSpeedTuner = "systemPrePurgeFanSpeedTuner"
    const val standalonePrePurgeFanSpeedTuner = "standalonePrePurgeFanSpeedTuner"
    const val prePurgeOutsideDamperOpen = "prePurgeOutsideDamperOpen"
    const val co2DamperOpeningRate = "co2DamperOpeningRate"
    const val systemPostPurgeRuntimeTuner = "systemPostPurgeRuntimeTuner"
    const val economizingMinTemperature = "economizingMinTemperature"
    const val economizingMaxTemperature = "economizingMaxTemperature"
    const val economizingMinHumidity = "economizingMinHumidity"
    const val outsideDamperMixedAirTarget = "outsideDamperMixedAirTarget"
    const val systemPrePurgeRuntimeTuner = "systemPrePurgeRuntimeTuner"
    const val standalonePrePurgeRuntimeTuner = "standalonePrePurgeRuntimeTuner"
    const val economizingMaxHumidity = "economizingMaxHumidity"
    const val systemPrePurgeOccupiedTimeOffsetTuner = "systemPrePurgeOccupiedTimeOffsetTuner"
    const val standalonePrePurgeOccupiedTimeOffsetTuner = "standalonePrePurgeOccupiedTimeOffsetTuner"
    const val enthalpyDuctCompensationOffset = "enthalpyDuctCompensationOffset"
    const val systemPostPurgeFanSpeedTuner = "systemPostPurgeFanSpeedTuner"
    const val systemPostPurgeOccupiedTimeOffsetTuner = "systemPostPurgeOccupiedTimeOffsetTuner"
    const val systemPurgeDabDamperMinOpenMultiplier = "systemPurgeDabDamperMinOpenMultiplier"
    const val systemPurgeVavMinFanLoopOutput = "systemPurgeVavMinFanLoopOutput"
    const val systemPurgeDabMinFanLoopOutput = "systemPurgeDabMinFanLoopOutput"
    const val systemPurgeVavDamperMinOpenMultiplier = "systemPurgeVavDamperMinOpenMultiplier"
    const val economizingDryBulbThreshold = "economizingDryBulbThreshold"

    const val standaloneEnthalpyDuctCompensationOffset = "standaloneEnthalpyDuctCompensationOffset"
    const val standaloneEconomizingToMainCoolingLoopMap = "standaloneEconomizingToMainCoolingLoopMap"
    const val standaloneEconomizingMinTemperature = "standaloneEconomizingMinTemperature"
    const val standaloneEconomizingMaxTemperature = "standaloneEconomizingMaxTemperature"
    const val standaloneEconomizingMinHumidity = "standaloneEconomizingMinHumidity"
    const val standaloneEconomizingMaxHumidity = "standaloneEconomizingMaxHumidity"
    const val standaloneEconomizingDryBulbThreshold = "standaloneEconomizingDryBulbThreshold"
    const val standaloneOutsideDamperMixedAirTarget = "standaloneOutsideDamperMixedAirTarget"
    const val standaloneOutsideDamperMixedAirMinimum = "standaloneOutsideDamperMixedAirMinimum"
    const val standaloneDuctTemperatureOffset = "standaloneDuctTemperatureOffset"
    const val standaloneCoolingAirflowTempLowerOffset = "standaloneCoolingAirflowTempLowerOffset"
    const val standaloneCoolingAirflowTempUpperOffset = "standaloneCoolingAirflowTempUpperOffset"
    const val standaloneHeatingAirflowTempUpperOffset = "standaloneHeatingAirflowTempUpperOffset"
    const val standaloneHeatingAirflowTempLowerOffset = "standaloneHeatingAirflowTempLowerOffset"


    const val dualDuctZoneVocTarget = "dualDuctZoneVocTarget"
    const val dualDuctZoneCo2Target = "dualDuctZoneCo2Target"
    const val dualDuctCoolingDeadband = "dualDuctCoolingDeadband"
    const val dualDuctIntegralKFactor = "dualDuctIntegralKFactor"
    const val dualDuctZoneVocThreshold = "dualDuctZoneVocThreshold"
    const val dualDuctZoneCo2Threshold = "dualDuctZoneCo2Threshold"
    const val dualDuctTemperatureIntegralTime = "dualDuctTemperatureIntegralTime"
    const val dualDuctProportionalKFactor = "dualDuctProportionalKFactor"
    const val dualDuctZonePrioritySpread = "dualDuctZonePrioritySpread"
    const val dualDuctCoolingDeadbandMultiplier = "dualDuctCoolingDeadbandMultiplier"
    const val dualDuctTemperatureProportionalRange = "dualDuctTemperatureProportionalRange"
    const val dualDuctHeatingDeadband = "dualDuctHeatingDeadband"
    const val dualDuctZonePriorityMultiplier = "dualDuctZonePriorityMultiplier"
    const val dualDuctHeatingDeadbandMultiplier = "dualDuctHeatingDeadbandMultiplier"


    const val stage1CoolingAirflowTempLowerOffset = "stage1CoolingAirflowTempLowerOffset"
    const val stage2CoolingAirflowTempLowerOffset = "stage2CoolingAirflowTempLowerOffset"
    const val stage3CoolingAirflowTempLowerOffset = "stage3CoolingAirflowTempLowerOffset"
    const val stage4CoolingAirflowTempLowerOffset = "stage4CoolingAirflowTempLowerOffset"
    const val stage5CoolingAirflowTempLowerOffset = "stage5CoolingAirflowTempLowerOffset"
    const val stage1CoolingAirflowTempUpperOffset = "stage1CoolingAirflowTempUpperOffset"
    const val stage2CoolingAirflowTempUpperOffset = "stage2CoolingAirflowTempUpperOffset"
    const val stage3CoolingAirflowTempUpperOffset = "stage3CoolingAirflowTempUpperOffset"
    const val stage4CoolingAirflowTempUpperOffset = "stage4CoolingAirflowTempUpperOffset"
    const val stage5CoolingAirflowTempUpperOffset = "stage5CoolingAirflowTempUpperOffset"
    const val stage1HeatingAirflowTempLowerOffset = "stage1HeatingAirflowTempLowerOffset"
    const val stage2HeatingAirflowTempLowerOffset = "stage2HeatingAirflowTempLowerOffset"
    const val stage3HeatingAirflowTempLowerOffset = "stage3HeatingAirflowTempLowerOffset"
    const val stage4HeatingAirflowTempLowerOffset = "stage4HeatingAirflowTempLowerOffset"
    const val stage5HeatingAirflowTempLowerOffset = "stage5HeatingAirflowTempLowerOffset"
    const val stage1HeatingAirflowTempUpperOffset = "stage1HeatingAirflowTempUpperOffset"
    const val stage2HeatingAirflowTempUpperOffset = "stage2HeatingAirflowTempUpperOffset"
    const val stage3HeatingAirflowTempUpperOffset = "stage3HeatingAirflowTempUpperOffset"
    const val stage4HeatingAirflowTempUpperOffset = "stage4HeatingAirflowTempUpperOffset"
    const val stage5HeatingAirflowTempUpperOffset = "stage5HeatingAirflowTempUpperOffset"


    const val otnIntegralKFactor = "otnIntegralKFactor"
    const val otnTemperatureIntegralTime = "otnTemperatureIntegralTime"
    const val otnZonePriorityMultiplier = "otnZonePriorityMultiplier"
    const val otnCoolingDeadband = "otnCoolingDeadband"
    const val otnHeatingDeadband = "otnHeatingDeadband"
    const val otnTemperatureProportionalRange = "otnTemperatureProportionalRange"
    const val otnProportionalKFactor = "otnProportionalKFactor"
    const val otnZonePrioritySpread = "otnZonePrioritySpread"

    const val chilledWaterTemperatureIntegralTime = "chilledWaterTemperatureIntegralTime"
    const val chilledWaterIntegralKFactor = "chilledWaterIntegralKFactor"
    const val dcwbChilledWaterTemperatureProportionalRange = "dcwbChilledWaterTemperatureProportionalRange"
    const val adaptiveComfortThresholdMargin = "adaptiveComfortThresholdMargin"
    const val chilledWaterProportionalKFactor = "chilledWaterProportionalKFactor"

    const val pipe2FancoilHeatingThreshold = "pipe2FancoilHeatingThreshold"
    const val pipe2FancoilCoolingThreshold = "pipe2FancoilCoolingThreshold"

    const val vrvHeatingDeadbandMultiplier = "vrvHeatingDeadbandMultiplier"
    const val vrvHeatingDeadband = "vrvHeatingDeadband"
    const val vrvCoolingDeadbandMultiplier = "vrvCoolingDeadbandMultiplier"
    const val vrvCoolingDeadband = "vrvCoolingDeadband"

    const val coolingUserLimitMin = "coolingUserLimitMin"
    const val buildingLimitMax = "buildingLimitMax"
    const val heatingUserLimitMin = "heatingUserLimitMin"
    const val coolingUserLimitMax = "coolingUserLimitMax"
    const val heatingUserLimitMax = "heatingUserLimitMax"
    const val buildingLimitMin = "buildingLimitMin"
    const val heatingDeadband = "heatingDeadband"
    const val coolingDeadband = "coolingDeadband"
    const val unoccupiedZoneSetback = "unoccupiedZoneSetback"
    const val buildingToZoneDifferential = "buildingToZoneDifferential"

    const val heartBeat = "heartBeat"
    const val rssi = "rssi"
    const val currentTemp = "currentTemp"
    const val zoneHumidity = "zoneHumidity"
    const val desiredTemp = "desiredTemp"
    const val desiredTempCooling = "desiredTempCooling"
    const val desiredTempHeating = "desiredTempHeating"
    const val coolingLoopOutput = "coolingLoopOutput"
    const val heatingLoopOutput = "heatingLoopOutput"
    const val fanLoopOutput = "fanLoopOutput"
    const val scheduleType = "scheduleType"
    const val equipStatus = "equipStatus"
    const val equipStatusMessage = "equipStatusMessage"
    const val equipScheduleStatus = "equipScheduleStatus"
    const val zoneCo2 = "zoneCo2"
    const val dischargeAirTemp = "dischargeAirTemp"
    const val enteringAirTemp = "enteringAirTemp"
    const val pressureSensor = "pressureSensor"
    const val zoneVoc = "zoneVoc"
    const val occupancyMode = "occupancyMode"
    const val occupancyDetection = "occupancyDetection"
    const val fanOpMode = "fanOpMode"
    const val zoneIlluminance = "zoneIlluminance"
    const val zoneSound = "zoneSound"
    const val zonePm25 = "zonePm25"
    const val zoneCo = "zoneCo"
    const val zoneNo = "zoneNo"
    const val zoneUvi = "zoneUvi"
    const val zoneCo2Equivalent = "zoneCo2e"
    const val zoneOccupancy = "zoneOccupancy"

    const val dischargeAirTempSetpoint = "dischargeAirTempSetpoint"
    const val otaStatus = "otaStatus"
    const val reheatCmd = "reheatCmd"
    const val reheatCmdCal = "reheatCmdCal"
    const val damperCmd = "damperCmd"
    const val damperCmdCal = "damperCmdCal"
    const val damperFeedback = "damperFeedback"
    const val normalizedDamperCmd = "normalizedDamperCmd"
    const val airVelocity = "airVelocity"
    const val airFlowSensor = "airFlowSensor"
    const val airFlowSetpoint = "airFlowSetpoint"
    const val zoneDynamicPriority = "zoneDynamicPriority"
    const val co2RequestPercentage = "co2RequestPercentage"
    const val satRequestPercentage = "satRequestPercentage"
    const val satCurrentRequest = "satCurrentRequest"
    const val co2CurrentRequest = "co2CurrentRequest"
    const val pressureRequestPercentage = "pressureRequestPercentage"
    const val pressureCurrentRequest = "pressureCurrentRequest"
    const val vavZoneVocThreshold = "vavZoneVocThreshold"

    const val seriesFanCmd = "seriesFanCmd"
    const val parallelFanCmd = "parallelFanCmd"

    const val relay1 = "relay1"
    const val relay2 = "relay2"
    const val relay3 = "relay3"
    const val relay4 = "relay4"
    const val relay5 = "relay5"
    const val relay6 = "relay6"
    const val relay7 = "relay7"
    const val analog1 = "analog1"
    const val analog2 = "analog2"
    const val analog3 = "analog3"
    const val analog4 = "analog4"
    const val analog1Out = "analog1Out"
    const val analog2Out = "analog2Out"
    const val analog1In = "analog1In"
    const val analog2In = "analog2In"
    const val th1In = "th1In"
    const val th2In = "th2In"

    const val smartnodeVAVReheatNoFan = "smartnodeVAVReheatNoFan"
    const val smartnodeVAVReheatParallelFan = "smartnodeVAVReheatParallelFan"
    const val smartnodeVAVReheatSeriesFan = "smartnodeVAVReheatSeriesFan"
    const val smartnodeActiveChilledBeam = "smartnodeActiveChilledBeam"
    const val helionodeVAVReheatNoFan = "helionodeVAVReheatNoFan"
    const val helionodeVAVReheatParallelFan = "helionodeVAVReheatParallelFan"
    const val helionodeVAVReheatSeriesFan = "helionodeVAVReheatSeriesFan"
    const val helionodeActiveChilledBeam = "helionodeActiveChilledBeam"
    const val smartnodeBypassDamper = "smartnodeBypassDamper"

    const val ductStaticPressureSensor = "ductStaticPressureSensor"
    const val ductStaticPressureSetpoint = "ductStaticPressureSetpoint"
    const val pressureSensorType = "pressureSensorType"
    const val damperMinPosition = "damperMinPosition"
    const val damperMaxPosition = "damperMaxPosition"
    const val sensorMinVoltage = "sensorMinVoltageOutput"
    const val sensorMaxVoltage = "sensorMaxVoltageOutput"
    const val pressureSensorMinVal = "pressureSensorMinVal"
    const val pressureSensorMaxVal = "pressureSensorMaxVal"
    const val satMinThreshold = "satMinThreshold"
    const val satMaxThreshold = "satMaxThreshold"
    const val expectedPressureError = "expectedPressureError"
    const val bypassDamperCmd = "bypassDamperCmd"
    const val supplyAirTemp = "supplyAirTemp"
    const val bypassDamperLoopOutput = "bypassDamperLoopOutput"
    const val bypassCoolingLockout = "bypassCoolingLockout"
    const val bypassHeatingLockout = "bypassHeatingLockout"
    const val bypassDamperSATTimeDelay = "bypassDamperSATTimeDelay"
    const val bypassDamperIntegralTime = "bypassDamperIntegralTime"
    const val relay1OutputEnable = "relay1OutputEnable"
    const val relay2OutputEnable = "relay2OutputEnable"
    const val relay3OutputEnable = "relay3OutputEnable"
    const val relay4OutputEnable = "relay4OutputEnable"
    const val relay5OutputEnable = "relay5OutputEnable"
    const val relay6OutputEnable = "relay6OutputEnable"
    const val relay7OutputEnable = "relay7OutputEnable"
    const val relay1OutputAssociation = "relay1OutputAssociation"
    const val relay2OutputAssociation = "relay2OutputAssociation"
    const val relay3OutputAssociation = "relay3OutputAssociation"
    const val relay4OutputAssociation = "relay4OutputAssociation"
    const val relay5OutputAssociation = "relay5OutputAssociation"
    const val relay6OutputAssociation = "relay6OutputAssociation"
    const val relay7OutputAssociation = "relay7OutputAssociation"

    const val cmCoolingDesiredTemp = "cmCoolingDesiredTemp"
    const val cmHeatingDesiredTemp = "cmHeatingDesiredTemp"
    const val cmCurrentTemp = "cmCurrentTemp"
    const val outsideTemperature = "outsideTemperature"
    const val outsideHumidity = "outsideHumidity"
    const val operatingMode = "operatingMode"
    const val systemCI = "systemCI"
    const val averageHumidity = "averageHumidity"
    const val cmHumidity = "cmHumidity"
    const val averageTemperature = "averageTemperature"

    const val epidemicModeSystemState = "epidemicModeSystemState"
    const val systemPrePurgeEnabled = "systemPrePurgeEnabled"
    const val systemPostPurgeEnabled = "systemPostPurgeEnabled"
    const val systemEnhancedVentilationEnabled = "systemEnhancedVentilationEnabled"

    const val useOutsideTempLockoutCooling = "useOutsideTempLockoutCooling"
    const val useOutsideTempLockoutHeating = "useOutsideTempLockoutHeating"
    const val mechanicalCoolingAvailable = "coolingAvailable"
    const val mechanicalHeatingAvailable = "heatingAvailable"
    const val co2LoopOutput = "co2LoopOutput"

    const val weightedAverageCoolingLoadMA = "weightedAverageCoolingLoadMA"
    const val weightedAverageHeatingLoadMA = "weightedAverageHeatingLoadMA"
    const val weightedAverageCoolingLoadPostML = "weightedAverageCoolingLoadPostML"
    const val weightedAverageHeatingLoadPostML = "weightedAverageHeatingLoadPostML"

    const val desiredCI = "desiredCI"
    const val conditioningMode = "conditioningMode"
    const val targetMaxInsideHumidity = "targetMaxInsideHumidity"
    const val targetMinInsideHumidity = "targetMinInsideHumidity"
    const val compensateHumidity = "compensateHumidity"
    const val demandResponseMode = "demandResponseMode"

    const val coolingStage1 = "coolingStage1"
    const val coolingStage2 = "coolingStage2"
    const val coolingStage3 = "coolingStage3"
    const val coolingStage4 = "coolingStage4"
    const val coolingStage5 = "coolingStage5"

    const val heatingStage1 = "heatingStage1"
    const val heatingStage2 = "heatingStage2"
    const val heatingStage3 = "heatingStage3"
    const val heatingStage4 = "heatingStage4"
    const val heatingStage5 = "heatingStage5"

    const val fanStage1 = "fanStage1"
    const val fanStage2 = "fanStage2"
    const val fanStage3 = "fanStage3"
    const val fanStage4 = "fanStage4"
    const val fanStage5 = "fanStage5"

    const val humidifierEnable = "humidifierEnable"
    const val dehumidifierEnable = "dehumidifierEnable"

    const val relay8 = "relay8"
    const val analog3Out = "analog3Out"
    const val analog4Out = "analog4Out"

    // External Ahu
    const val satSetpointControlEnable = "satSetpointControlEnable"
    const val dualSetpointControlEnable = "dualSetpointControlEnable"
    const val staticPressureSetpointControlEnable = "staticPressureSetpointControlEnable"
    const val dcvDamperControlEnable = "dcvDamperControlEnable"
    const val occupancyModeControl = "occupancyModeControl"
    const val humidifierOperationEnable = "humidifierOperationEnable"
    const val dehumidifierOperationEnable = "dehumidifierOperationEnable"
    const val systemSATMinimum = "systemSATMinimum"
    const val systemSATMaximum = "systemSATMaximum"
    const val systemHeatingSATMinimum = "systemHeatingSATMinimum"
    const val systemHeatingSATMaximum = "systemHeatingSATMaximum"
    const val systemCoolingSATMinimum = "systemCoolingSATMinimum"
    const val systemCoolingSATMaximum = "systemCoolingSATMaximum"
    const val systemStaticPressureMinimum = "systemStaticPressureMinimum"
    const val systemStaticPressureMaximum = "systemStaticPressureMaximum"
    const val systemDCVDamperPosMinimum = "systemDCVDamperPosMinimum"
    const val systemDCVDamperPosMaximum = "systemDCVDamperPosMaximum"
    const val tagValueIncrement = "tagValueIncrement"
    const val systemOccupancyMode = "systemOccupancyMode"
    const val supplyAirflowTemperatureSetpoint = "supplyAirflowTemperatureSetpoint"
    const val airTempHeatingSp = "airTempHeatingSp"
    const val airTempCoolingSp = "airTempCoolingSp"
    const val systemCO2Threshold = "systemCO2Threshold"
    const val systemCO2DamperOpeningRate = "systemCO2DamperOpeningRate"
    const val systemCO2Target = "systemCO2Target"
    const val systemtargetMinInsideHumidty = "systemtargetMinInsideHumidty"
    const val systemtargetMaxInsideHumidty = "systemtargetMaxInsideHumidty"
    const val dcvDamperCalculatedSetpoint = "dcvDamperCalculatedSetpoint"
    const val targetHumidifier = "targetHumidifier"
    const val targetDehumidifier = "targetDehumidifier"
    const val dcvLoopOutput = "dcvLoopOutput"
    const val systemPrePurgeEnable = "systemPrePurgeEnable"
    const val systemPostPurgeEnable = "systemPostPurgeEnable"
    const val systemEnhancedVentilationEnable = "systemEnhancedVentilationEnable"
    const val co2WeightedAverage = "co2WeightedAverage"
    const val weightedAverageChangeOverLoadMA = "weightedAverageChangeOverLoadMA"
    const val weightedAverageLoadMA = "weightedAverageLoadMA"

    const val analog1OutputEnable = "analog1OutputEnable"
    const val analog2OutputEnable = "analog2OutputEnable"
    const val analog3OutputEnable = "analog3OutputEnable"
    const val analog4OutputEnable = "analog4OutputEnable"
    const val analog2CoolStage1 = "analog2CoolStage1"
    const val analog2CoolStage2 = "analog2CoolStage2"
    const val analog2CoolStage3 = "analog2CoolStage3"
    const val analog2CoolStage4 = "analog2CoolStage4"
    const val analog2CoolStage5 = "analog2CoolStage5"
    const val analog2HeatStage1 = "analog2HeatStage1"
    const val analog2HeatStage2 = "analog2HeatStage2"
    const val analog2HeatStage3 = "analog2HeatStage3"
    const val analog2HeatStage4 = "analog2HeatStage4"
    const val analog2HeatStage5 = "analog2HeatStage5"
    const val analog2Recirculate = "analog2Recirculate"
    const val analog2Economizer = "analog2Economizer"
    const val analog2Default = "analog2Default"
    const val fanSignal = "fanSignal"
    const val linearFanSpeed = "linearFanSpeed"
    const val stagedFanSpeed = "stagedFanSpeed"

    const val systemtargetMaxInsideHumidity = "systemtargetMaxInsideHumidity"
    const val systemtargetMinInsideHumidity = "systemtargetMinInsideHumidity"

    //Advanced AHU
    const val relay8OutputEnable = "relay8OutputEnable"
    const val relay8OutputAssociation = "relay8OutputAssociation"
    const val sensorBusAddress0Enable = "sensorBusAddress0Enable"
    const val sensorBusAddress1Enable = "sensorBusAddress1Enable"
    const val sensorBusAddress2Enable = "sensorBusAddress2Enable"
    const val sensorBusAddress3Enable = "sensorBusAddress3Enable"
    const val sensorBusPressureEnable = "sensorBusPressureEnable"
    const val pressureSensorBusAdd0 = "pressureSensorBusAdd0"
    const val pressureSensorBusAdd1 = "pressureSensorBusAdd1"
    const val pressureSensorBusAdd2 = "pressureSensorBusAdd2"
    const val pressureSensorBusAdd3 = "pressureSensorBusAdd3"
    const val temperatureSensorBusAdd0 = "temperatureSensorBusAdd0"
    const val temperatureSensorBusAdd1 = "temperatureSensorBusAdd1"
    const val temperatureSensorBusAdd2 = "temperatureSensorBusAdd2"
    const val temperatureSensorBusAdd3 = "temperatureSensorBusAdd3"
    const val humiditySensorBusAdd0 = "humiditySensorBusAdd0"
    const val humiditySensorBusAdd1 = "humiditySensorBusAdd1"
    const val humiditySensorBusAdd2 = "humiditySensorBusAdd2"
    const val humiditySensorBusAdd3 = "humiditySensorBusAdd3"
    const val occupancySensorBusAdd0 = "occupancySensorBusAdd0"
    const val occupancySensorBusAdd1 = "occupancySensorBusAdd1"
    const val occupancySensorBusAdd2 = "occupancySensorBusAdd2"
    const val occupancySensorBusAdd3 = "occupancySensorBusAdd3"
    const val co2SensorBusAdd0 = "co2SensorBusAdd0"
    const val co2SensorBusAdd1 = "co2SensorBusAdd1"
    const val co2SensorBusAdd2 = "co2SensorBusAdd2"
    const val co2SensorBusAdd3 = "co2SensorBusAdd3"

    const val ductStaticPressureSensor1_1 = "ductStaticPressureSensor1_1"
    const val ductStaticPressureSensor1_2 = "ductStaticPressureSensor1_2"
    const val ductStaticPressureSensor1_10 = "ductStaticPressureSensor1_10"
    const val ductStaticPressureSensor2_1 = "ductStaticPressureSensor2_1"
    const val ductStaticPressureSensor2_2 = "ductStaticPressureSensor2_2"
    const val ductStaticPressureSensor2_10 = "ductStaticPressureSensor2_10"
    const val ductStaticPressureSensor3_1 = "ductStaticPressureSensor3_1"
    const val ductStaticPressureSensor3_2 = "ductStaticPressureSensor3_2"
    const val ductStaticPressureSensor3_10 = "ductStaticPressureSensor3_10"

    const val returnAirTemperature = "returnAirTemperature"
    const val mixedAirTemperature = "mixedAirTemperature"
    const val supplyAirTemperature1 = "supplyAirTemperature1"
    const val supplyAirTemperature2 = "supplyAirTemperature2"
    const val supplyAirTemperature3 = "supplyAirTemperature3"

    const val returnAirHumidity = "returnAirHumidity"
    const val mixedAirHumidity = "mixedAirHumidity"
    const val supplyAirHumidity1 = "supplyAirHumidity1"
    const val supplyAirHumidity2 = "supplyAirHumidity2"
    const val supplyAirHumidity3 = "supplyAirHumidity3"

    const val occupancySensor1 = "occupancySensor1"
    const val occupancySensor2 = "occupancySensor2"
    const val occupancySensor3 = "occupancySensor3"

    const val analog1InputEnable = "analog1InputEnable"
    const val analog2InputEnable = "analog2InputEnable"
    const val analog1InputAssociation = "analog1InputAssociation"
    const val analog2InputAssociation = "analog2InputAssociation"

    const val zoneAvgCo2 = "zoneAvgCo2"
    const val returnAirCo2 = "returnAirCo2"
    const val mixedAirCo2 = "mixedAirCo2"

    const val thermistor1InputEnable = "thermistor1InputEnable"
    const val thermistor2InputEnable = "thermistor2InputEnable"
    const val thermistor1InputAssociation = "thermistor1InputAssociation"
    const val thermistor2InputAssociation = "thermistor2InputAssociation"


    const val emergencyShutoff = "emergencyShutoff"

    const val loadCoolingStage1 = "loadCoolingStage1"
    const val loadCoolingStage2 = "loadCoolingStage2"
    const val loadCoolingStage3 = "loadCoolingStage3"
    const val loadCoolingStage4 = "loadCoolingStage4"
    const val loadCoolingStage5 = "loadCoolingStage5"
    const val loadHeatingStage1 = "loadHeatingStage1"
    const val loadHeatingStage2 = "loadHeatingStage2"
    const val loadHeatingStage3 = "loadHeatingStage3"
    const val loadHeatingStage4 = "loadHeatingStage4"
    const val loadHeatingStage5 = "loadHeatingStage5"
    const val loadFanStage1 = "loadFanStage1"
    const val loadFanStage2 = "loadFanStage2"
    const val loadFanStage3 = "loadFanStage3"
    const val loadFanStage4 = "loadFanStage4"
    const val loadFanStage5 = "loadFanStage5"
    const val satCoolingStage1 = "satCoolingStage1"
    const val satCoolingStage2 = "satCoolingStage2"
    const val satCoolingStage3 = "satCoolingStage3"
    const val satCoolingStage4 = "satCoolingStage4"
    const val satCoolingStage5 = "satCoolingStage5"
    const val satHeatingStage1 = "satHeatingStage1"
    const val satHeatingStage2 = "satHeatingStage2"
    const val satHeatingStage3 = "satHeatingStage3"
    const val satHeatingStage4 = "satHeatingStage4"
    const val satHeatingStage5 = "satHeatingStage5"
    const val fanPressureStage1 = "fanPressureStage1"
    const val fanPressureStage2 = "fanPressureStage2"
    const val fanPressureStage3 = "fanPressureStage3"
    const val fanPressureStage4 = "fanPressureStage4"
    const val fanPressureStage5 = "fanPressureStage5"
    const val occupiedEnable = "occupiedEnable"
    const val fanEnable = "fanEnable"
    const val ahuFreshAirFanRunCommand = "ahuFreshAirFanRunCommand"

    const val analog1OutputAssociation = "analog1OutputAssociation"
    const val analog2OutputAssociation = "analog2OutputAssociation"
    const val analog3OutputAssociation = "analog3OutputAssociation"
    const val analog4OutputAssociation = "analog4OutputAssociation"

    const val pressureBasedFanControl = "pressureBasedFanControl"
    const val satBasedCoolingControl = "satBasedCoolingControl"
    const val satBasedHeatingControl = "satBasedHeatingControl"
    const val loadBasedCoolingControl = "loadBasedCoolingControl"
    const val loadBasedHeatingControl = "loadBasedHeatingControl"
    const val loadBasedFanControl = "loadBasedFanControl"
    const val co2BasedDamperControl = "co2BasedDamperControl"
    const val compositeSignal = "compositeSignal"
    const val pressureBasedFanControlOn = "pressureBasedFanControlOn"
    const val supplyAirTempControlOn = "supplyAirTempControlOn"
    const val co2BasedDamperControlOn = "co2BasedDamperControlOn"

    const val analog1MinStaticPressure = "analog1MinStaticPressure"
    const val analog1MaxStaticPressure = "analog1MaxStaticPressure"


    const val analog2MinStaticPressure = "analog2MinStaticPressure"
    const val analog2MaxStaticPressure = "analog2MaxStaticPressure"
    const val analog3MinStaticPressure = "analog3MinStaticPressure"
    const val analog3MaxStaticPressure = "analog3MaxStaticPressure"
    const val analog4MinStaticPressure = "analog4MinStaticPressure"
    const val analog4MaxStaticPressure = "analog4MaxStaticPressure"

    const val analog1MinSatCooling = "analog1MinSatCooling"
    const val analog1MaxSatCooling = "analog1MaxSatCooling"
    const val analog2MinSatCooling = "analog2MinSatCooling"
    const val analog2MaxSatCooling = "analog2MaxSatCooling"
    const val analog3MinSatCooling = "analog3MinSatCooling"
    const val analog3MaxSatCooling = "analog3MaxSatCooling"
    const val analog4MinSatCooling = "analog4MinSatCooling"
    const val analog4MaxSatCooling = "analog4MaxSatCooling"

    const val analog1MaxSatHeating = "analog1MaxSatHeating"
    const val analog1MinSatHeating = "analog1MinSatHeating"
    const val analog2MaxSatHeating = "analog2MaxSatHeating"
    const val analog2MinSatHeating = "analog2MinSatHeating"
    const val analog3MaxSatHeating = "analog3MaxSatHeating"
    const val analog3MinSatHeating = "analog3MinSatHeating"
    const val analog4MaxSatHeating = "analog4MaxSatHeating"
    const val analog4MinSatHeating = "analog4MinSatHeating"

    const val analog1MaxDamperPos = "analog1MaxDamperPos"
    const val analog1MinDamperPos = "analog1MinDamperPos"
    const val analog2MaxDamperPos = "analog2MaxDamperPos"
    const val analog2MinDamperPos = "analog2MinDamperPos"
    const val analog3MaxDamperPos = "analog3MaxDamperPos"
    const val analog3MinDamperPos = "analog3MinDamperPos"
    const val analog4MaxDamperPos = "analog4MaxDamperPos"
    const val analog4MinDamperPos = "analog4MinDamperPos"

    const val analog1MaxFan = "analog1MaxFan"
    const val analog1MinFan = "analog1MinFan"
    const val analog2MaxFan = "analog2MaxFan"
    const val analog2MinFan = "analog2MinFan"
    const val analog3MaxFan = "analog3MaxFan"
    const val analog3MinFan = "analog3MinFan"
    const val analog4MaxFan = "analog4MaxFan"
    const val analog4MinFan = "analog4MinFan"

    const val analog1MinCoolingComposite = "analog1MinCoolingComposite"
    const val analog1MaxCoolingComposite = "analog1MaxCoolingComposite"
    const val analog2MinCoolingComposite = "analog2MinCoolingComposite"
    const val analog2MaxCoolingComposite = "analog2MaxCoolingComposite"
    const val analog3MinCoolingComposite = "analog3MinCoolingComposite"
    const val analog3MaxCoolingComposite = "analog3MaxCoolingComposite"
    const val analog4MinCoolingComposite = "analog4MinCoolingComposite"
    const val analog4MaxCoolingComposite = "analog4MaxCoolingComposite"

    const val analog1MinHeatingComposite = "analog1MinHeatingComposite"
    const val analog1MaxHeatingComposite = "analog1MaxHeatingComposite"
    const val analog2MinHeatingComposite = "analog2MinHeatingComposite"
    const val analog2MaxHeatingComposite = "analog2MaxHeatingComposite"
    const val analog3MinHeatingComposite = "analog3MinHeatingComposite"
    const val analog3MaxHeatingComposite = "analog3MaxHeatingComposite"
    const val analog4MinHeatingComposite = "analog4MinHeatingComposite"
    const val analog4MaxHeatingComposite = "analog4MaxHeatingComposite"

    const val staticPressureMin = "staticPressureMin"
    const val staticPressureMax = "staticPressureMax"
    const val systemCoolingSatMin = "systemCoolingSatMin"
    const val systemCoolingSatMax = "systemCoolingSatMax"
    const val systemHeatingSatMin = "systemHeatingSatMin"
    const val systemHeatingSatMax = "systemHeatingSatMax"

    //Connect Equip universal input mappings
    const val universalIn1Enable = "universalIn1Enable"
    const val universalIn2Enable = "universalIn2Enable"
    const val universalIn3Enable = "universalIn3Enable"
    const val universalIn4Enable = "universalIn4Enable"
    const val universalIn5Enable = "universalIn5Enable"
    const val universalIn6Enable = "universalIn6Enable"
    const val universalIn7Enable = "universalIn7Enable"
    const val universalIn8Enable = "universalIn8Enable"
    const val universalIn1Association = "universalIn1Association"
    const val universalIn2Association = "universalIn2Association"
    const val universalIn3Association = "universalIn3Association"
    const val universalIn4Association = "universalIn4Association"
    const val universalIn5Association = "universalIn5Association"
    const val universalIn6Association = "universalIn6Association"
    const val universalIn7Association = "universalIn7Association"
    const val universalIn8Association = "universalIn8Association"


    const val buildingStaticPressureSensor_1 = "buildingStaticPressureSensor_1"
    const val buildingStaticPressureSensor_2 = "buildingStaticPressureSensor_2"
    const val buildingStaticPressureSensor_10 = "buildingStaticPressureSensor_10"
    const val chilledWaterInletTemp = "chilledWaterInletTemp"
    const val chilledWaterOutletTemp = "chilledWaterOutletTemp"
    const val coolingValvePositionFeedback = "coolingValvePositionFeedback"
    const val supplyAirDamperFeedback = "supplyAirDamperFeedback"
    const val supplyAirFlowSensor = "supplyAirFlowSensor"
    const val supplyAirHumidity = "supplyAirHumidity"
    const val supplyAirPm25 = "supplyAirPm2.5"
    const val supplyFanVfdFeedback = "supplyFanVfdFeedback"
    const val heatingValvePositionFeedback = "heatingValvePositionFeedback"
    const val minimumOutsideAirDamper = "minimumOutsideAirDamper"
    const val mixedAirDamperFeedback = "mixedAirDamperFeedback"
    const val outsideAirDamperFeedback = "outsideAirDamperFeedback"
    const val outsideAirFlowSensor_10 = "outsideAirFlowSensor_10"
    const val outsideAirFlowSensor_20 = "outsideAirFlowSensor_20"
    const val returnAirDamperFeedback = "returnAirDamperFeedback"
    const val spaceTemp = "spaceTemp"
    const val currentTx10 = "currentTx10"
    const val currentTx20 = "currentTx20"
    const val currentTx30 = "currentTx30"
    const val currentTx50 = "currentTx50"
    const val currentTx60 = "currentTx60"
    const val currentTx100 = "currentTx100"
    const val currentTx120 = "currentTx120"
    const val currentTx150 = "currentTx150"
    const val currentTx200 = "currentTx200"
    const val exhaustFanVfdFeedback = "exhaustFanVfdFeedback"
    const val outsideFanVfdFeedback = "outsideFanVfdFeedback"
    const val returnFanVfdFeedback = "returnFanVfdFeedback"
    const val supplyFanAutoManual = "supplyFanAutoManual"
    const val supplyFanRunStatus = "supplyFanRunStatus"
    const val supplyFanTripStatus = "supplyFanTripStatus"
    const val exhaustFanAutoManual = "exhaustFanAutoManual"
    const val uvAMStatus = "uvAMStatus"
    const val exhaustFanAMStatus = "exhaustFanAMStatus"
    const val exhaustFanRunStatus = "exhaustFanRunStatus"
    const val exhaustFanTripStatus = "exhaustFanTripStatus"
    const val filterStatus1NO = "filterStatus1NO"
    const val filterStatus1NC = "filterStatus1NC"
    const val filterStatus2NO = "filterStatus2NO"
    const val filterStatus2NC = "filterStatus2NC"
    const val fireAlarmStatus = "fireAlarmStatus"
    const val fireDamperStatus1 = "fireDamperStatus1"
    const val fireDamperStatus2 = "fireDamperStatus2"
    const val fireDamperStatus3 = "fireDamperStatus3"
    const val fireDamperStatus4 = "fireDamperStatus4"
    const val fireDamperStatus5 = "fireDamperStatus5"
    const val fireDamperStatus6 = "fireDamperStatus6"
    const val fireDamperStatus7 = "fireDamperStatus7"
    const val fireDamperStatus8 = "fireDamperStatus8"
    const val highDifferentialPressureSwitch = "highDifferentialPressureSwitch"
    const val lowDifferentialPressureSwitch = "lowDifferentialPressureSwitch"
    const val outsideFanRunStatus = "outsideFanRunStatus"
    const val outsideFanTripStatus = "outsideFanTripStatus"
    const val returnFanRunStatus = "returnFanRunStatus"
    const val returnFanTripStatus = "returnFanTripStatus"
    const val returnFanAMStatus = "returnFanAMStatus"
    const val uvRunStatus = "uvRunStatus"
    const val uvTripStatus = "uvTripStatus"
    const val outsideFanAMStatus = "outsideFanAMStatus"
    const val emergencyShutoffNO = "emergencyShutoffNO"
    const val emergencyShutoffNC = "emergencyShutoffNC"
    const val thermistorInput = "thermistorInput"
    const val genericAlarmNO = "genericAlarmNO"
    const val genericAlarmNC = "genericAlarmNC"

    const val averageSat = "averageSat"
    const val minSat = "minSat"
    const val maxSat = "maxSat"
    const val averagePressure = "averagePressure"
    const val minPressure = "minPressure"
    const val maxPressure = "maxPressure"
    const val satCoolingLoopOutput = "satCoolingLoopOutput"
    const val satHeatingLoopOutput = "satHeatingLoopOutput"
    const val fanPressureLoopOutput = "fanPressureLoopOutput"
    const val outsideAirTemp = "outsideAirTemp"
    const val returnAirTemp = "returnAirTemp"

    const val dischargeFanAMStatus = "dischargeFanAMStatus"
    const val dischargeFanRunStatus = "dischargeFanRunStatus"
    const val dischargeFanTripStatus = "dischargeFanTripStatus"
    const val dischargeAirDamperFeedback = "dischargeAirDamperFeedback"
    const val dischargeAirFlowSensor_10 = "dischargeAirFlowSensor_10"
    const val dischargeAirFlowSensor_20 = "dischargeAirFlowSensor_20"
    const val dischargeAirHumidity = "dischargeAirHumidity"
    const val dischargeAirPm25 = "dischargeAirPm25"
    const val dischargeFanVfdFeedback = "dischargeFanVfdFeedback"
    const val minimumOutsideAirDamperFeedback = "minimumOutsideAirDamperFeedback"
    const val outsideAirHumidity = "outsideAirHumidity"
    const val filterStatus1No = "filterStatus1No"
    const val filterStatus1Nc = "filterStatus1Nc"
    const val filterStatus2No = "filterStatus2No"
    const val filterStatus2Nc = "filterStatus2Nc"

    const val condensateStatusNO = "condensateStatusNO"
    const val condensateStatusNC = "condensateStatusNC"
    //const val emergencyShutoffStatusNO = "emergencyShutoffStatusNO"
    //const val emergencyShutoffStatusNC = "emergencyShutoffStatusNC"

    const val ductStaticPressure1 = "ductStaticPressure1"
    const val ductStaticPressure2 = "ductStaticPressure2"
    const val ductStaticPressure3 = "ductStaticPressure3"


    const val coolingSignal = "coolingSignal"
    const val heatingSignal = "heatingSignal"
    const val analog4MinOutsideDamper = "analog4MinOutsideDamper"
    const val analog4MaxOutsideDamper = "analog4MaxOutsideDamper"
    const val backfillDuration = "backfillDuration"
    const val outsideAirDamper = "outsideAirDamper"
    const val weightedAverageCoolingLoad = "weightedAverageCoolingLoad"
    const val weightedAverageHeatingLoad = "weightedAverageHeatingLoad"
    const val satTRSp = "satTRSp"
    const val co2TRSp = "co2TRSp"
    const val staticPressureTRSp = "staticPressureTRSp"
    const val demandResponseEnrollment = "demandResponseEnrollment"
    const val demandResponseActivation = "demandResponseActivation"
    const val offlineMode = "offlineMode"
    const val vavFullyModulatingAhu = "vavFullyModulatingAhu"
    const val humidifier = "humidifier"
    const val dehumidifier = "dehumidifier"

    const val outsideDamperMinOpenDuringRecirculation = "outsideDamperMinOpenDuringRecirculation"
    const val outsideDamperMinOpenDuringConditioning = "outsideDamperMinOpenDuringConditioning"
    const val outsideDamperMinOpenDuringFanLow = "outsideDamperMinOpenDuringFanLow"
    const val outsideDamperMinOpenDuringFanMedium = "outsideDamperMinOpenDuringFanMedium"
    const val outsideDamperMinOpenDuringFanHigh = "outsideDamperMinOpenDuringFanHigh"

    const val exhaustFanStage1Threshold = "exhaustFanStage1Threshold"
    const val exhaustFanStage2Threshold = "exhaustFanStage2Threshold"
    const val exhaustFanHysteresis = "exhaustFanHysteresis"
    const val insideEnthalpy = "insideEnthalpy"
    const val outsideEnthalpy = "outsideEnthalpy"
    const val economizingAvailable = "economizingAvailable"
    const val matThrottle = "matThrottle"
    const val economizingLoopOutput = "economizingLoopOutput"
    const val outsideAirCalculatedMinDamper = "outsideAirCalculatedMinDamper"
    const val outsideAirLoopOutput = "outsideAirLoopOutput"
    const val outsideAirFinalLoopOutput = "outsideAirFinalLoopOutput"

    const val enableHumidityDisplay = "enableHumidityDisplay"
    const val enableCO2Display = "enableCo2Display"
    const val enableVOCDisplay = "enableVocDisplay"
    const val enablePm25Display = "enablePm25Display"

    const val co2Threshold = "co2Threshold"
    const val co2Target = "co2Target"

    const val vocThreshold = "vocThreshold"
    const val vocTarget = "vocTarget"

    const val pm25Threshold = "pm25Threshold"
    const val pm25Target = "pm25Target"

    const val analog1MinCooling = "analog1MinCooling"
    const val analog1MaxCooling = "analog1MaxCooling"
    const val analog1MinHeating = "analog1MinHeating"
    const val analog1MaxHeating = "analog1MaxHeating"
    const val analog1MinOAODamper = "analog1MinOAODamper"
    const val analog1MaxOAODamper = "analog1MaxOAODamper"
    const val analog1MinReturnDamper = "analog1MinReturnDamper"
    const val analog1MaxReturnDamper = "analog1MaxReturnDamper"
    const val analog1MinLinearFanSpeed = "analog1MinLinearFanSpeed"
    const val analog1MaxLinearFanSpeed = "analog1MaxLinearFanSpeed"
    const val analog1FanLow = "analog1FanLow"
    const val analog1FanMedium = "analog1FanMedium"
    const val analog1FanHigh = "analog1FanHigh"

    const val analog2MinCooling = "analog2MinCooling"
    const val analog2MaxCooling = "analog2MaxCooling"
    const val analog2MinHeating = "analog2MinHeating"
    const val analog2MaxHeating = "analog2MaxHeating"
    const val analog2MinOAODamper = "analog2MinOAODamper"
    const val analog2MaxOAODamper = "analog2MaxOAODamper"
    const val analog2MinReturnDamper = "analog2MinReturnDamper"
    const val analog2MaxReturnDamper = "analog2MaxReturnDamper"
    const val analog2MinLinearFanSpeed = "analog2MinLinearFanSpeed"
    const val analog2MaxLinearFanSpeed = "analog2MaxLinearFanSpeed"
    const val analog2FanLow = "analog2FanLow"
    const val analog2FanMedium = "analog2FanMedium"
    const val analog2FanHigh = "analog2FanHigh"

    const val analog3MinCooling = "analog3MinCooling"
    const val analog3MaxCooling = "analog3MaxCooling"
    const val analog3MinHeating = "analog3MinHeating"
    const val analog3MaxHeating = "analog3MaxHeating"
    const val analog3MinOAODamper = "analog3MinOAODamper"
    const val analog3MaxOAODamper = "analog3MaxOAODamper"
    const val analog3MinReturnDamper = "analog3MinReturnDamper"
    const val analog3MaxReturnDamper = "analog3MaxReturnDamper"
    const val analog3MinLinearFanSpeed = "analog3MinLinearFanSpeed"
    const val analog3MaxLinearFanSpeed = "analog3MaxLinearFanSpeed"
    const val analog3FanLow = "analog3FanLow"
    const val analog3FanMedium = "analog3FanMedium"
    const val analog3FanHigh = "analog3FanHigh"

    const val analog4MinCooling = "analog4MinCooling"
    const val analog4MaxCooling = "analog4MaxCooling"
    const val analog4MinHeating = "analog4MinHeating"
    const val analog4MaxHeating = "analog4MaxHeating"
    const val analog4MinOAODamper = "analog4MinOAODamper"
    const val analog4MaxOAODamper = "analog4MaxOAODamper"
    const val analog4MinReturnDamper = "analog4MinReturnDamper"
    const val analog4MaxReturnDamper = "analog4MaxReturnDamper"
    const val analog4MinLinearFanSpeed = "analog4MinLinearFanSpeed"
    const val analog4MaxLinearFanSpeed = "analog4MaxLinearFanSpeed"
    const val analog4FanLow = "analog4FanLow"
    const val analog4FanMedium = "analog4FanMedium"
    const val analog4FanHigh = "analog4FanHigh"

    const val fanOutRecirculate = "fanOutRecirculate"
    const val fanOutEconomizer = "fanOutEconomizer"
    const val fanOutHeatingStage1 = "fanOutHeatingStage1"
    const val fanOutHeatingStage2 = "fanOutHeatingStage2"
    const val fanOutHeatingStage3 = "fanOutHeatingStage3"
    const val fanOutCoolingStage1 = "fanOutCoolingStage1"
    const val fanOutCoolingStage2 = "fanOutCoolingStage2"
    const val fanOutCoolingStage3 = "fanOutCoolingStage3"

    const val fanLowSpeed = "fanLowSpeed"
    const val fanMediumSpeed = "fanMediumSpeed"
    const val fanHighSpeed = "fanHighSpeed"
    const val exhaustFanStage1 = "exhaustFanStage1"
    const val exhaustFanStage2 = "exhaustFanStage2"
    const val dcvDamper = "dcvDamper"

    const val oaoDamper = "oaoDamper"
    const val outsideDamperSensor = "outsideDamperSensor"
    const val returnDamperPosition = "returnDamperPosition"

    const val filterStatusNO = "filterStatusNO"
    const val filterStatusNC = "filterStatusNC"
    const val ductStaticPressureSensor0_1 = "ductStaticPressureSensor0_1"
    const val ductStaticPressureSensor0_2 = "ductStaticPressureSensor0_2"
    const val ductStaticPressureSensor0_10 = "ductStaticPressureSensor0_10"

    const val dcvAvailable = "dcvAvailable"
    const val weatherOutsideTemp = "weatherOutsideTemp"
    const val weatherOutsideHumidity = "weatherOutsideHumidity"
    const val enableOutsideAirOptimization = "enableOutsideAirOptimization"

    const val universal1In = "universal1In"
    const val universal2In = "universal2In"
    const val universal3In = "universal3In"
    const val universal4In = "universal4In"
    const val universal5In = "universal5In"
    const val universal6In = "universal6In"
    const val universal7In = "universal7In"
    const val universal8In = "universal8In"
    const val humiditySensor = "humiditySensor"
    const val occupancySensor = "occupancySensor"
    const val illuminanceSensor = "illuminanceSensor"
    const val co2Sensor = "co2Sensor"
    const val vocSensor = "vocSensor"
    const val pm25Sensor = "pm25Sensor"
    const val pm10Sensor = "pm10Sensor"
    const val soundSensor = "soundSensor"
    const val mixedAirTempSensor = "mixedAirTempSensor"
    const val dischargeAirTemperature = "dischargeAirTemperature"
    const val mixedAirHumiditySensor = "mixedAirHumiditySensor"
    const val outsideAirTempSensor = "outsideAirTempSensor"
    const val outsideAirHumiditySensor = "outsideAirHumiditySensor"
    const val supplyAirTempSensor = "supplyAirTempSensor"
    const val supplyAirTemperature = "supplyAirTemperature"
    const val supplyAirHumiditySensor = "supplyAirHumiditySensor"


    // DAB zone
    const val damper1Cmd = "damper1Cmd"
    const val damper1Shape = "damper1Shape"
    const val damper1Type = "damper1Type"
    const val damper1Size = "damper1Size"
    const val  normalizedDamper1Cmd = "normalizedDamper1Cmd"
    const val dischargeAirTemp1 = "dischargeAirTemp1"
    const val minCFMIAQ = "minCFMIAQ"
    const val minReheatDamperPos = "minReheatDamperPos"

    const val damper2Cmd = "damper2Cmd"
    const val damper2Shape = "damper2Shape"
    const val damper2Type = "damper2Type"
    const val damper2Size = "damper2Size"
    const val  normalizedDamper2Cmd = "normalizedDamper2Cmd"
    const val dischargeAirTemp2 = "dischargeAirTemp2"

    const val voltageInput = "voltageInput"
    const val otaStatusHyperlite = "otaStatusHyperlite"
    const val otaStatusConnectModule = "otaStatusConnectModule"

    const val coolingLoopOutputFeedback = "coolingLoopOutputFeedback"
    const val heatingLoopOutputFeedback = "heatingLoopOutputFeedback"
    const val fanLoopOutputFeedback = "fanLoopOutputFeedback"
    const val satCoolingStage1Feedback = "satCoolingStage1Feedback"
    const val satCoolingStage2Feedback = "satCoolingStage2Feedback"
    const val satCoolingStage3Feedback = "satCoolingStage3Feedback"
    const val satCoolingStage4Feedback = "satCoolingStage4Feedback"
    const val satCoolingStage5Feedback = "satCoolingStage5Feedback"
    const val satHeatingStage1Feedback = "satHeatingStage1Feedback"
    const val satHeatingStage2Feedback = "satHeatingStage2Feedback"
    const val satHeatingStage3Feedback = "satHeatingStage3Feedback"
    const val satHeatingStage4Feedback = "satHeatingStage4Feedback"
    const val satHeatingStage5Feedback = "satHeatingStage5Feedback"
    const val fanPressureStage1Feedback = "fanPressureStage1Feedback"
    const val fanPressureStage2Feedback = "fanPressureStage2Feedback"
    const val fanPressureStage3Feedback = "fanPressureStage3Feedback"
    const val fanPressureStage4Feedback = "fanPressureStage4Feedback"
    const val fanPressureStage5Feedback = "fanPressureStage5Feedback"
    const val pressureBasedFanControlFeedback = "pressureBasedFanControlFeedback"
    const val satBasedCoolingControlFeedback = "satBasedCoolingControlFeedback"
    const val satBasedHeatingControlFeedback = "satBasedHeatingControlFeedback"

    //PLC
    const val analog1InputType = "analog1InputType"
    //target value ?
    const val dynamicTargetValue = "dynamicTargetValue"
    const val thermistor1InputType = "thermistor1InputType"
    const val pidProportionalRange = "pidProportionalRange"
    const val nativeSensorType = "nativeSensorType"
    const val expectZeroErrorAtMidpoint = "expectZeroErrorAtMidpoint"
    const val invertControlLoopoutput = "invertControlLoopoutput"
    const val useAnalogIn2ForSetpoint = "useAnalogIn2ForSetpoint"
    const val analog2InputType = "analog2InputType"
    const val setpointSensorOffset = "setpointSensorOffset"
    const val analog1MinOutput = "analog1MinOutput"
    const val analog1MaxOutput = "analog1MaxOutput"
    const val relay1OnThreshold = "relay1OnThreshold"
    const val relay1OffThreshold = "relay1OffThreshold"
    const val relay2OnThreshold = "relay2OnThreshold"
    const val relay2OffThreshold = "relay2OffThreshold"
    const val relay1Cmd = "relay1Cmd"
    const val relay2Cmd = "relay2Cmd"




}

