package a75f.io.domain.api

/**
 * List of all known domain names.
 * Camel case naming is followed to keep the names more relatable to the actual domain names.
 */

object DomainName {
    //Tuners
    const val userLimitSpread = "userLimitSpread"
    const val heatingPreconditioningRate = "heatingPreconditioningRate"
    const val coolingPreconditioningRate = "coolingPreconditioningRate"
    const val cmTempPercentDeadZonesAllowed = "cmTempPercentDeadZonesAllowed"
    const val airflowSampleWaitTime = "airflowSampleWaitTime"
    const val clockUpdateInterval = "clockUpdateInterval"
    const val perDegreeHumidityFactor = "perDegreeHumidityFactor"
    const val ccuAlarmVolumeLevel = "ccuAlarmVolumeLevel"
    const val cmHeartBeatInterval = "cmHeartBeatInterval"
    const val heartBeatsToSkip = "heartBeatsToSkip"
    const val cmResetCommandTimer = "cmResetCommandTimer"
    const val zoneTemperatureDeadLeeway = "zoneTemperatureDeadLeeway"
    const val humidityCompensationOffset = "humidityCompensationOffset"
    const val proportionalKFactor = "proportionalKFactor"
    const val integralKFactor = "integralKFactor"
    const val pidIntegralTime = "pidIntegralTime"

    const val rebalanceHoldTime = "rebalanceHoldTime"
    const val constantTempAlertTime = "constantTempAlertTime"
    const val abnormalCurTempRiseTrigger = "abnormalCurTempRiseTrigger"
    const val heatingAirflowTemp = "heatingAirflowTemp"
    const val coolingAirflowTemp = "coolingAirflowTemp"
    const val adrHeatingDeadband = "adrHeatingDeadband"
    const val adrCoolingDeadband = "adrCoolingDeadband"
    const val autoAwayTime = "autoAwayTime"
    const val forcedOccupiedTime = "forcedOccupiedTime"
    const val zoneDeadTime = "zoneDeadTime"
    const val displayUnit = "displayUnit"
    const val autoAwaySetback = "autoAwaySetback"
    const val ccuNetworkWatchdogTimeout = "ccuNetworkWatchdogTimeout"
    const val auxHeating1Activate = "auxHeating1Activate"
    const val auxHeating2Activate = "auxHeating2Activate"
    const val waterValveSamplingWaitTime = "waterValveSamplingWaitTime"
    const val waterValveSamplingOnTime = "waterValveSamplingOnTime"
    const val waterValveSamplingLoopDeadbandOnTime = "waterValveSamplingLoopDeadbandOnTime"
    const val waterValveSamplingLoopDeadbandWaitTime = "waterValveSamplingLoopDeadbandWaitTime"
    const val buildingLimitAlertTimer = "buildingLimitAlertTimer"


    //DAB
    const val dabTargetCumulativeDamper = "dabTargetCumulativeDamper"
    const val dabAnalogFanSpeedMultiplier = "dabAnalogFanSpeedMultiplier"
    const val dabHumidityHysteresis = "dabHumidityHysteresis"
    const val dabRelayDeactivationHysteresis = "dabRelayDeactivationHysteresis"
    const val dabRebalanceHoldTime = "dabRebalanceHoldTime"
    const val dabModeChangeoverHysteresis = "dabModeChangeoverHysteresis"
    const val dabStageUpTimerCounter = "dabStageUpTimerCounter"
    const val dabStageDownTimerCounter = "dabStageDownTimerCounter"
    const val dabProportionalKFactor = "dabProportionalKFactor"
    const val dabIntegralKFactor = "dabIntegralKFactor"
    const val dabTemperatureProportionalRange = "dabTemperatureProportionalRange"
    const val dabTemperatureIntegralTime = "dabTemperatureIntegralTime"
    const val dabOutsideTempCoolingLockout = "dabOutsideTempCoolingLockout"
    const val dabOutsideTempHeatingLockout = "dabOutsideTempHeatingLockout"
    const val dabZonePrioritySpread = "dabZonePrioritySpread"
    const val dabZoneVOCTarget = "dabZoneVOCTarget"
    const val dabZoneVOCThreshold = "dabZoneVOCThreshold"
    const val dabZoneCO2Target = "dabZoneCO2Target"
    const val dabZonePriorityMultiplier = "dabZonePriorityMultiplier"
    const val dabCoolingDeadband = "dabCoolingDeadband"
    const val dabZoneCO2Threshold = "dabZoneCO2Threshold"
    const val dabHeatingDeadband = "dabHeatingDeadband"
    const val dabCoolingDeadbandMultiplier = "dabCoolingDeadbandMultiplier"
    const val dabReheatRelayActivationHysteresis = "dabReheatRelayActivationHysteresis"
    const val dabReheatTemperatureIntegralTime = "dabReheatTemperatureIntegralTime"
    const val reheatTempOffset = "reheatTempOffset"
    const val dabReheatTemperatureProportionalRange = "dabReheatTemperatureProportionalRange"
    const val dabReheatIntegralKFactor = "dabReheatIntegralKFactor"
    const val reheatProportionalKFactor = "reheatProportionalKFactor"

    //VAV
    const val vavTargetCumulativeDamper = "vavTargetCumulativeDamper"
    const val vavAnalogFanSpeedMultiplier = "vavAnalogFanSpeedMultiplier"
    const val vavHumidityHysteresis = "vavHumidityHysteresis"
    const val vavRelayDeactivationHysteresis = "vavRelayDeactivationHysteresis"
    const val vavRebalanceHoldTime = "vavRebalanceHoldTime"
    const val vavModeChangeoverHysteresis = "vavModeChangeoverHysteresis"
    const val vavStageUpTimerCounter = "vavStageUpTimerCounter"
    const val vavStageDownTimerCounter = "vavStageDownTimerCounter"
    const val vavProportionalKFactor = "vavProportionalKFactor"
    const val vavIntegralKFactor = "vavIntegralKFactor"
    const val vavTemperatureProportionalRange = "vavTemperatureProportionalRange"
    const val vavTemperatureIntegralTime = "vavTemperatureIntegralTime"
    const val vavOutsideTempCoolingLockout = "vavOutsideTempCoolingLockout"
    const val vavOutsideTempHeatingLockout = "vavOutsideTempHeatingLockout"

    //VAV-Zone
    const val damperType = "damperType"
    const val damperSize = "damperSize"
    const val damperShape = "damperShape"
    const val reheatType = "reheatType"
    const val zonePriority = "zonePriority"
    const val autoForceOccupied = "autoForceOccupied"
    const val autoAway = "autoAway"
    const val enableIAQControl = "enableIAQControl"
    const val enableCo2Control = "enableCo2Control"
    const val enableCFMControl = "enableCFMControl"
    const val temperatureOffset = "temperatureOffset"
    const val minHeatingDamperPos = "minHeatingDamperPos"
    const val maxHeatingDamperPos = "maxHeatingDamperPos"
    const val minCoolingDamperPos = "minCoolingDamperPos"
    const val maxCoolingDamperPos = "maxCoolingDamperPos"
    const val kFactor = "kFactor"
    const val minCFMCooling = "minCFMCooling"
    const val maxCFMCooling = "maxCFMCooling"
    const val minCFMReheating = "minCFMReheating"
    const val maxCFMReheating = "maxCFMReheating"

    const val vavIntegralKfactor = "vavIntegralKfactor"
    const val vavZoneVocTarget = "vavZoneVocTarget"
    const val vavZoneCo2Threshold = "vavZoneCo2Threshold"
    const val vavZoneCo2Target = "vavZoneCo2Target"
    const val vavCoolingDeadband = "vavCoolingDeadband"
    const val vavHeatingDeadband = "vavHeatingDeadband"
    const val vavZoneVOCThreshold = "vavZoneVOCThreshold"
    const val valveActuationStartDamperPosDuringSysHeating = "valveActuationStartDamperPosDuringSysHeating"
    const val vavHeatingDeadbandMultiplier = "vavHeatingDeadbandMultiplier"
    const val vavCoolingDeadbandMultiplier = "vavCoolingDeadbandMultiplier"
    const val fanControlOnFixedTimeDelay = "fanControlOnFixedTimeDelay"
    const val reheatZoneMaxDischargeTemp = "reheatZoneMaxDischargeTemp"
    const val reheatZoneToDATMinDifferential = "reheatZoneToDATMinDifferential"
    const val reheatZoneDischargeTempOffset = "reheatZoneDischargeTempOffset"
    const val vavModeChangeOverHysteresis = "vavModeChangeOverHysteresis"
    const val vavZonePrioritySpread = "vavZonePrioritySpread"
    const val vavZonePriorityMultiplier = "vavZonePriorityMultiplier"
    const val dabHeatingDeadbandMultiplier = "dabHeatingDeadbandMultiplier"


    //VAV-TR
    const val satSPInit = "satSPInit"
    const val satSPMin = "satSpMin"
    const val satSPMax = "satSpMax"
    const val satTimeDelay = "satTimeDelay"
    const val satTimeInterval = "satTimeInterval"
    const val satIgnoreRequest = "satIgnoreRequest"
    const val satSPTrim = "satSPTrim"
    const val satSPRes = "satSpRes"
    const val satSPResMax = "satSpResMax"
    const val staticPressureSPInit = "staticPressureSPInit"
    const val staticPressureSPMin = "staticPressureSpMin"
    const val staticPressureSPMax = "staticPressureSpMax"
    const val staticPressureTimeDelay = "staticPressureTimeDelay"
    const val staticPressureTimeInterval = "staticPressureTimeInterval"
    const val staticPressureIgnoreRequest = "staticPressureIgnoreRequest"
    const val staticPressureSPTrim = "staticPressureSPTrim"
    const val staticPressureSPRes = "staticPressureSpRes"
    const val staticPressureSPResMax = "staticPressureSpResMax"
    const val co2SPInit = "co2SPInit"
    const val co2SPMin = "co2SpMin"
    const val co2SPMax = "co2SpMax"
    const val co2TimeDelay = "co2TimeDelay"
    const val co2TimeInterval = "co2TimeInterval"
    const val co2IgnoreRequest = "co2IgnoreRequest"
    const val co2SPTrim = "co2SPTrim"
    const val co2SPRes = "co2SpRes"
    const val co2SPResMax = "co2SpResMax"

    const val vavAirflowCFMIntegralKFactor = "vavAirflowCFMIntegralKFactor"
    const val vavAirflowCFMProportionalKFactor = "vavAirflowCFMProportionalKFactor"
    const val vavAirflowCFMIntegralTime = "vavAirflowCFMIntegralTime"
    const val vavAirflowCFMProportionalRange = "vavAirflowCFMProportionalRange"


    const val standaloneCoolingDeadband = "standaloneCoolingDeadband"
    const val standaloneHeatingDeadband = "standaloneHeatingDeadband"
    const val standaloneStage2CoolingLowerOffset = "standaloneStage2CoolingLowerOffset"
    const val standaloneStage1HeatingUpperOffset = "standaloneStage1HeatingUpperOffset"
    const val standaloneStage1HeatingLowerOffset = "standaloneStage1HeatingLowerOffset"
    const val standaloneVOCThreshold = "standaloneVOCThreshold"
    const val standaloneCoolingPreconditioningRate = "standaloneCoolingPreconditioningRate"
    const val standaloneHeatingPreconditioningRate = "standaloneHeatingPreconditioningRate"
    const val standaloneStage1CoolingUpperOffset = "standaloneStage1CoolingUpperOffset"
    const val standaloneCO2Target = "standaloneCO2Target"
    const val standaloneAirflowSampleWaitTime = "standaloneAirflowSampleWaitTime"
    const val standaloneStage1Hysteresis = "standaloneStage1Hysteresis"
    const val standaloneStage1CoolingLowerOffset = "standaloneStage1CoolingLowerOffset"
    const val standaloneCO2Threshold = "standaloneCO2Threshold"
    const val standaloneVOCTarget = "standaloneVOCTarget"
    const val standaloneCoolingDeadbandMultiplier = "standaloneCoolingDeadbandMultiplier"
    const val standaloneHeatingDeadbandMultiplier = "standaloneHeatingDeadbandMultiplier"
    const val standaloneStage2CoolingUpperOffset = "standaloneStage2CoolingUpperOffset"
    const val standaloneTemperatureProportionalRange = "standaloneTemperatureProportionalRange"
    const val standaloneStage2HeatingLowerOffset = "standaloneStage2HeatingLowerOffset"
    const val standaloneProportionalKFactor = "standaloneProportionalKFactor"
    const val standaloneRelayActivationHysteresis = "standaloneRelayActivationHysteresis"
    const val standaloneHumidityHysteresis = "standaloneHumidityHysteresis"
    const val standaloneTemperatureIntegralTime = "standaloneTemperatureIntegralTime"
    const val standaloneAnalogFanSpeedMultiplier = "standaloneAnalogFanSpeedMultiplier"
    const val standaloneStage2HeatingUpperOffset = "standaloneStage2HeatingUpperOffset"
    const val standaloneIntegralKFactor = "standaloneIntegralKFactor"

    //TI
    const val tiCoolingDeadbandMultiplier = "tiCoolingDeadbandMultiplier"
    const val tiHeatingDeadband = "tiHeatingDeadband"
    const val tiIntegralKFactor = "tiIntegralKFactor"
    const val tiTemperatureIntegralTime = "tiTemperatureIntegralTime"
    const val tiHeatingDeadbandMultiplier = "tiHeatingDeadbandMultiplier"
    const val tiTemperatureProportionalRange = "tiTemperatureProportionalRange"
    const val tiZonePriorityMultiplier = "tiZonePriorityMultiplier"
    const val tiZonePrioritySpread = "tiZonePrioritySpread"
    const val tiCoolingDeadband = "tiCoolingDeadband"
    const val tiProportionalKFactor = "tiProportionalKFactor"

    //OAO

    const val outsideDamperMixedAirMinimum = "outsideDamperMixedAirMinimum"
    const val economizingToMainCoolingLoopMap = "economizingToMainCoolingLoopMap"
    const val systemPrePurgeFanSpeedTuner = "systemPrePurgeFanSpeedTuner"
    const val co2DamperOpeningRate = "co2DamperOpeningRate"
    const val systemPostPurgeRuntimeTuner = "systemPostPurgeRuntimeTuner"
    const val economizingMinTemperature = "economizingMinTemperature"
    const val economizingMaxTemperature = "economizingMaxTemperature"
    const val economizingMinHumidity = "economizingMinHumidity"
    const val outsideDamperMixedAirTarget = "outsideDamperMixedAirTarget"
    const val systemPrePurgeRuntimeTuner = "systemPrePurgeRuntimeTuner"
    const val economizingMaxHumidity = "economizingMaxHumidity"
    const val systemPrePurgeOccupiedTimeOffsetTuner = "systemPrePurgeOccupiedTimeOffsetTuner"
    const val enthalpyDuctCompensationOffset = "enthalpyDuctCompensationOffset"
    const val systemPostPurgeFanSpeedTuner = "systemPostPurgeFanSpeedTuner"
    const val systemPostPurgeOccupiedTimeOffsetTuner = "systemPostPurgeOccupiedTimeOffsetTuner"
    const val systemPurgeDabDamperMinOpenMultiplier = "systemPurgeDabDamperMinOpenMultiplier"
    const val systemPurgeVavMinFanLoopOutput = "systemPurgeVavMinFanLoopOutput"
    const val systemPurgeDabMinFanLoopOutput = "systemPurgeDabMinFanLoopOutput"
    const val systemPurgeVavDamperMinOpenMultiplier = "systemPurgeVavDamperMinOpenMultiplier"
    const val economizingDryBulbThreshold = "economizingDryBulbThreshold"

    const val standaloneEnthalpyDuctCompensationOffset = "standaloneEnthalpyDuctCompensationOffset"
    const val standaloneEconomizingToMainCoolingLoopMap = "standaloneEconomizingToMainCoolingLoopMap"
    const val standaloneEconomizingMinTemperature = "standaloneEconomizingMinTemperature"
    const val standaloneEconomizingMaxTemperature = "standaloneEconomizingMaxTemperature"
    const val standaloneEconomizingMinHumidity = "standaloneEconomizingMinHumidity"
    const val standaloneEconomizingMaxHumidity = "standaloneEconomizingMaxHumidity"
    const val standaloneEconomizingDryBulbThreshold = "standaloneEconomizingDryBulbThreshold"
    const val standaloneOutsideDamperMixedAirTarget = "standaloneOutsideDamperMixedAirTarget"
    const val standaloneOutsideDamperMixedAirMinimum = "standaloneOutsideDamperMixedAirMinimum"
    const val standaloneDuctTemperatureOffset = "standaloneDuctTemperatureOffset"
    const val standaloneCoolingAirflowTempLowerOffset = "standaloneCoolingAirflowTempLowerOffset"
    const val standaloneCoolingAirflowTempUpperOffset = "standaloneCoolingAirflowTempUpperOffset"
    const val standaloneHeatingAirflowTempUpperOffset = "standaloneHeatingAirflowTempUpperOffset"
    const val standaloneHeatingAirflowTempLowerOffset = "standaloneHeatingAirflowTempLowerOffset"


    const val dualDuctZoneVocTarget = "dualDuctZoneVocTarget"
    const val dualDuctZoneCO2Target = "dualDuctZoneCO2Target"
    const val dualDuctCoolingDeadband = "dualDuctCoolingDeadband"
    const val dualDuctIntegralKFactor = "dualDuctIntegralKFactor"
    const val dualDuctZoneVOCThreshold = "dualDuctZoneVOCThreshold"
    const val dualDuctZoneCO2Threshold = "dualDuctZoneCO2Threshold"
    const val dualDuctTemperatureIntegralTime = "dualDuctTemperatureIntegralTime"
    const val dualDuctProportionalKFactor = "dualDuctProportionalKFactor"
    const val dualDuctZonePrioritySpread = "dualDuctZonePrioritySpread"
    const val dualDuctCoolingDeadbandMultiplier = "dualDuctCoolingDeadbandMultiplier"
    const val dualDuctTemperatureProportionalRange = "dualDuctTemperatureProportionalRange"
    const val dualDuctHeatingDeadband = "dualDuctHeatingDeadband"
    const val dualDuctZonePriorityMultiplier = "dualDuctZonePriorityMultiplier"
    const val dualDuctHeatingDeadbandMultiplier = "dualDuctHeatingDeadbandMultiplier"


    const val stage1CoolingAirflowTempLowerOffset = "stage1CoolingAirflowTempLowerOffset"
    const val stage2CoolingAirflowTempLowerOffset = "stage2CoolingAirflowTempLowerOffset"
    const val stage3CoolingAirflowTempLowerOffset = "stage3CoolingAirflowTempLowerOffset"
    const val stage4CoolingAirflowTempLowerOffset = "stage4CoolingAirflowTempLowerOffset"
    const val stage5CoolingAirflowTempLowerOffset = "stage5CoolingAirflowTempLowerOffset"
    const val stage1CoolingAirflowTempUpperOffset = "stage1CoolingAirflowTempUpperOffset"
    const val stage2CoolingAirflowTempUpperOffset = "stage2CoolingAirflowTempUpperOffset"
    const val stage3CoolingAirflowTempUpperOffset = "stage3CoolingAirflowTempUpperOffset"
    const val stage4CoolingAirflowTempUpperOffset = "stage4CoolingAirflowTempUpperOffset"
    const val stage5CoolingAirflowTempUpperOffset = "stage5CoolingAirflowTempUpperOffset"
    const val stage1HeatingAirflowTempLowerOffset = "stage1HeatingAirflowTempLowerOffset"
    const val stage2HeatingAirflowTempLowerOffset = "stage2HeatingAirflowTempLowerOffset"
    const val stage3HeatingAirflowTempLowerOffset = "stage3HeatingAirflowTempLowerOffset"
    const val stage4HeatingAirflowTempLowerOffset = "stage4HeatingAirflowTempLowerOffset"
    const val stage5HeatingAirflowTempLowerOffset = "stage5HeatingAirflowTempLowerOffset"
    const val stage1HeatingAirflowTempUpperOffset = "stage1HeatingAirflowTempUpperOffset"
    const val stage2HeatingAirflowTempUpperOffset = "stage2HeatingAirflowTempUpperOffset"
    const val stage3HeatingAirflowTempUpperOffset = "stage3HeatingAirflowTempUpperOffset"
    const val stage4HeatingAirflowTempUpperOffset = "stage4HeatingAirflowTempUpperOffset"
    const val stage5HeatingAirflowTempUpperOffset = "stage5HeatingAirflowTempUpperOffset"


    const val otnIntegralKFactor = "otnIntegralKFactor"
    const val otnTemperatureIntegralTime = "otnTemperatureIntegralTime"
    const val otnZonePriorityMultiplier = "otnZonePriorityMultiplier"
    const val otnCoolingDeadband = "otnCoolingDeadband"
    const val otnHeatingDeadband = "otnHeatingDeadband"
    const val otnTemperatureProportionalRange = "otnTemperatureProportionalRange"
    const val otnProportionalKFactor = "otnProportionalKFactor"
    const val otnZonePrioritySpread = "otnZonePrioritySpread"

    const val chilledWaterTemperatureIntegralTime = "chilledWaterTemperatureIntegralTime"
    const val chilledWaterIntegralKFactor = "chilledWaterIntegralKFactor"
    const val dcwbChilledWaterTemperatureProportionalRange = "dcwbChilledWaterTemperatureProportionalRange"
    const val adaptiveComfortThresholdMargin = "adaptiveComfortThresholdMargin"
    const val chilledWaterProportionalKFactor = "chilledWaterProportionalKFactor"

    const val pipe2FancoilHeatingThreshold = "pipe2FancoilHeatingThreshold"
    const val pipe2FancoilCoolingThreshold = "pipe2FancoilCoolingThreshold"

    const val vrvHeatingDeadbandMultiplier = "vrvHeatingDeadbandMultiplier"
    const val vrvHeatingDeadband = "vrvHeatingDeadband"
    const val vrvCoolingDeadbandMultiplier = "vrvCoolingDeadbandMultiplier"
    const val vrvCoolingDeadband = "vrvCoolingDeadband"

    const val coolingUserLimitMin = "coolingUserLimitMin"
    const val buildingLimitMax = "buildingLimitMax"
    const val heatingUserLimitMin = "heatingUserLimitMin"
    const val coolingUserLimitMax = "coolingUserLimitMax"
    const val heatingUserLimitMax = "heatingUserLimitMax"
    const val buildingLimitMin = "buildingLimitMin"
    const val heatingDeadband = "heatingDeadband"
    const val coolingDeadband = "coolingDeadband"
    const val unoccupiedZoneSetback = "unoccupiedZoneSetback"
    const val buildingToZoneDifferential = "buildingToZoneDifferential"

    const val heartBeat = "heartBeat"
    const val currentTemp = "currentTemp"
    const val zoneHumidity = "zoneHumidity"
    const val desiredTemp = "desiredTemp"
    const val desiredTempCooling = "desiredTempCooling"
    const val desiredTempHeating = "desiredTempHeating"
    const val coolingLoopOutput = "coolingLoopOutput"
    const val heatingLoopOutput = "heatingLoopOutput"
    const val scheduleType = "scheduleType"
    const val equipStatus = "equipStatus"
    const val equipStatusMessage = "equipStatusMessage"
    const val equipScheduleStatus = "equipScheduleStatus"
    const val zoneCO2 = "zoneCO2"
    const val dischargeAirTemp = "dischargeAirTemp"
    const val enteringAirTemp = "enteringAirTemp"
    const val pressureSensor = "pressureSensor"
    const val zoneVoc = "zoneVoc"
    const val occupancyMode = "occupancyMode"
    const val occupancyDetection = "occupancyDetection"

    const val dischargeAirTempSetpoint = "dischargeAirTempSetpoint"
    const val otaStatus = "otaStatus"
    const val reheatCmd = "reheatCmd"
    const val damperCmd = "damperCmd"
    const val damperFeedback = "damperFeedback"
    const val normalizedDamperCmd = "normalizedDamperCmd"
    const val airVelocity = "airVelocity"
    const val airFlowSensor = "airFlowSensor"
    const val zoneDynamicPriority = "zoneDynamicPriority"
    const val co2RequestPercentage = "co2RequestPercentage"
    const val satRequestPercentage = "satRequestPercentage"
    const val satCurrentRequest = "satCurrentRequest"
    const val co2CurrentRequest = "co2CurrentRequest"
    const val pressureRequestPercentage = "pressureRequestPercentage"
    const val pressureCurrentRequest = "pressureCurrentRequest"
    const val vavZoneVocThreshold = "vavZoneVocThreshold"




}

