package a75f.io.domain.api

/**
 * List of all known domain names.
 * Camel case naming is followed to keep the names more relatable to the actual domain names.
 */

//BuildingEquip default tuners.

//Generic System Tuners
const val userLimitSpread = "userLimitSpread"
const val heatingPreconditioningRate = "heatingPreconditioningRate"
const val coolingPreconditioningRate = "coolingPreconditioningRate"
const val cmTempPercentDeadZonesAllowed = "cmTempPercentDeadZonesAllowed"
const val airflowSampleWaitTime = "airflowSampleWaitTime"
const val stage1CoolingAirflowTempLowerOffset = "stage1CoolingAirflowTempLowerOffset"
const val stage2CoolingAirflowTempLowerOffset = "stage2CoolingAirflowTempLowerOffset"
const val stage3CoolingAirflowTempLowerOffset = "stage3CoolingAirflowTempLowerOffset"
const val stage4CoolingAirflowTempLowerOffset = "stage4CoolingAirflowTempLowerOffset"
const val stage5CoolingAirflowTempLowerOffset = "stage5CoolingAirflowTempLowerOffset"
const val stage1CoolingAirflowTempUpperOffset = "stage1CoolingAirflowTempUpperOffset"
const val stage2CoolingAirflowTempUpperOffset = "stage2CoolingAirflowTempUpperOffset"
const val stage3CoolingAirflowTempUpperOffset = "stage3CoolingAirflowTempUpperOffset"
const val stage4CoolingAirflowTempUpperOffset = "stage4CoolingAirflowTempUpperOffset"
const val stage5CoolingAirflowTempUpperOffset = "stage5CoolingAirflowTempUpperOffset"
const val stage1HeatingAirflowTempLowerOffset = "stage1HeatingAirflowTempLowerOffset"
const val stage2HeatingAirflowTempLowerOffset = "stage2HeatingAirflowTempLowerOffset"
const val stage3HeatingAirflowTempLowerOffset = "stage3HeatingAirflowTempLowerOffset"
const val stage4HeatingAirflowTempLowerOffset = "stage4HeatingAirflowTempLowerOffset"
const val stage5HeatingAirflowTempLowerOffset = "stage5HeatingAirflowTempLowerOffset"
const val stage1HeatingAirflowTempUpperOffset = "stage1HeatingAirflowTempUpperOffset"
const val stage2HeatingAirflowTempUpperOffset = "stage2HeatingAirflowTempUpperOffset"
const val stage3HeatingAirflowTempUpperOffset = "stage3HeatingAirflowTempUpperOffset"
const val stage4HeatingAirflowTempUpperOffset = "stage4HeatingAirflowTempUpperOffset"
const val stage5HeatingAirflowTempUpperOffset = "stage5HeatingAirflowTempUpperOffset"

const val clockUpdateInterval = "clockUpdateInterval"
const val perDegreeHumidityFactor = "perDegreeHumidityFactor"
const val ccuAlarmVolumeLevel = "ccuAlarmVolumeLevel"
const val cmHeartBeatInterval = "cmHeartBeatInterval"
const val heartBeatsToSkip = "heartBeatsToSkip"
const val cmResetCommandTimer = "cmResetCommandTimer"
const val zoneTemperatureDeadLeeway = "zoneTemperatureDeadLeeway"
const val humidityCompensationOffset = "humidityCompensationOffset"

//DAB System Tuners
const val dabTargetCumulativeDamper = "dabTargetCumulativeDamper"
const val dabAnalogFanSpeedMultiplier = "dabAnalogFanSpeedMultiplier"
const val dabHumidityHysteresis = "dabHumidityHysteresis"
const val dabRelayDeactivationHysteresis = "dabRelayDeactivationHysteresis"
const val dabRebalanceHoldTime = "dabRebalanceHoldTime"
const val dabModeChangeoverHysteresis = "dabModeChangeoverHysteresis"
const val dabStageUpTimerCounter = "dabStageUpTimerCounter"
const val dabStageDownTimerCounter = "dabStageDownTimerCounter"
const val dabProportionalKFactor = "dabProportionalKFactor"
const val dabIntegralKFactor = "dabIntegralKFactor"
const val dabTemperatureProportionalRange = "dabTemperatureProportionalRange"
const val dabTemperatureIntegralTime = "dabTemperatureIntegralTime"
const val dabOutsideTempCoolingLockout = "dabOutsideTempCoolingLockout"
const val dabOutsideTempHeatingLockout = "dabOutsideTempHeatingLockout"

//VAV System Tuners
const val vavTargetCumulativeDamper = "vavTargetCumulativeDamper"
const val vavAnalogFanSpeedMultiplier = "vavAnalogFanSpeedMultiplier"
const val vavHumidityHysteresis = "vavHumidityHysteresis"
const val vavRelayDeactivationHysteresis = "vavRelayDeactivationHysteresis"
const val vavRebalanceHoldTime = "vavRebalanceHoldTime"
const val vavModeChangeoverHysteresis = "vavModeChangeoverHysteresis"
const val vavStageUpTimerCounter = "vavStageUpTimerCounter"
const val vavStageDownTimerCounter = "vavStageDownTimerCounter"
const val vavProportionalKFactor = "vavProportionalKFactor"
const val vavIntegralKFactor = "vavIntegralKFactor"
const val vavTemperatureProportionalRange = "vavTemperatureProportionalRange"
const val vavTemperatureIntegralTime = "vavTemperatureIntegralTime"
const val vavOutsideTempCoolingLockout = "vavOutsideTempCoolingLockout"
const val vavOutsideTempHeatingLockout = "vavOutsideTempHeatingLockout"

//VAV-TR
const val satSPInit = "satSPInit"
const val satSPMin = "satSpMin"
const val satSPMax = "satSpMax"
const val satTimeDelay = "satTimeDelay"
const val satTimeInterval = "satTimeInterval"
const val satIgnoreRequest = "satIgnoreRequest"
const val satSPTrim = "satSPTrim"
const val satSPRes = "satSpRes"
const val satSPResMax = "satSpResMax"
const val staticPressureSPInit = "staticPressureSPInit"
const val staticPressureSPMin = "staticPressureSpMin"
const val staticPressureSPMax = "staticPressureSpMax"
const val staticPressureTimeDelay = "staticPressureTimeDelay"
const val staticPressureTimeInterval = "staticPressureTimeInterval"
const val staticPressureIgnoreRequest = "staticPressureIgnoreRequest"
const val staticPressureSPTrim = "staticPressureSPTrim"
const val staticPressureSPRes = "staticPressureSpRes"
const val staticPressureSPResMax = "staticPressureSpResMax"
const val co2SPInit = "co2SPInit"
const val co2SPMin = "co2SpMin"
const val co2SPMax = "co2SpMax"
const val co2TimeDelay = "co2TimeDelay"
const val co2TimeInterval = "co2TimeInterval"
const val co2IgnoreRequest = "co2IgnoreRequest"
const val co2SPTrim = "co2SPTrim"
const val co2SPRes = "co2SpRes"
const val co2SPResMax = "co2SpResMax"

// External Ahu

const val satSetpointControlEnable = "satSetpointControlEnable"
const val dualSetpointControlEnable = "dualSetpointControlEnable"
const val staticPressureSetpointControlEnable = "staticPressureSetpointControlEnable"
const val dcvDamperControlEnable = "dcvDamperControlEnable"
const val occupancyModeControl = "occupancyModeControl"
const val humidifierOperationEnable = "humidifierOperationEnable"
const val dehumidifierOperationEnable = "dehumidifierOperationEnable"
const val systemSATMinimum = "systemSATMinimum"
const val systemSATMaximum = "systemSATMaximum"
const val systemHeatingSATMinimum = "systemHeatingSATMinimum"
const val systemHeatingSATMaximum = "systemHeatingSATMaximum"
const val systemCoolingSATMinimum = "systemCoolingSATMinimum"
const val systemCoolingSATMaximum = "systemCoolingSATMaximum"
const val systemStaticPressureMinimum = "systemStaticPressureMinimum"
const val systemStaticPressureMaximum = "systemStaticPressureMaximum"
const val systemDCVDamperPosMinimum = "systemDCVDamperPosMinimum"
const val systemDCVDamperPosMaximum = "systemDCVDamperPosMaximum"
const val targetHumidifier = "targetHumidifier"
const val targetDehumidifier = "targetDehumidifier"
const val tagValueIncrement = "tagValueIncrement"
const val systemOccupancyMode = "systemOccupancyMode"
const val ductStaticPressureSetpoint = "ductStaticPressureSetpoint"
const val supplyAirflowTemperatureSetpoint = "supplyAirflowTemperature  Setpoint"
const val systemCO2Threshold = "systemCO2Threshold"
const val systemCO2DamperOpeningRate = "systemCO2DamperOpeningRate"
const val outsideHumidity = "outsideHumidity"
const val systemtargetMinInsideHumidty = "systemtargetMinInsideHumidty"
const val systemtargetMaxInsideHumidty = "systemtargetMaxInsideHumidty"
