package a75f.io.renatus.profiles.system

/**
 * Created by Manjunath K on 29-03-2024.
 */

const val CM = "CM"
const val CONNECT_MODULE = "CONNECT MODULE"
const val SENSOR_BUS = "SENSOR BUS"
const val ENABLE = "ENABLE"
const val MAPPING = "MAPPING"
const val TEST_SIGNAL = "TEST SIGNAL"
const val ADDRESS_0 = "Address 0"
const val ADDRESS_1 = "Address 1"
const val ADDRESS_2 = "Address 2"
const val ADDRESS_3 = "Address 3"
const val PRESSURE = "Pressure"
const val TEMPERATURE = "Temperature"
const val HUMIDITY = "Humidity"
const val OCCUPANCY = "Occupancy"
const val CO2 = "CO2"
const val ANALOG_IN1 = "Analog-In 1"
const val ANALOG_IN2 = "Analog-In 2"
const val THERMISTOR_1 = "Thermistor 1"
const val THERMISTOR_2 = "Thermistor 2"
const val UNIVERSAL_IN = "Universal-In"
const val PRESSURE_BASED_FC = "Pressure Based Fan Control"
const val SAT_CONTROL = "Supply Air Temperature Control"
const val SAT_CONTROL_ON = "Supply Air Temperature Control On"
const val CO2_DAMPER_CONTROL = "CO2 Based Damper Control"
const val CO2_DAMPER_CONTROL_ON = "CO2 Based Damper Control On"
const val COOLING_CONTROL = "Load Based Cooling Control"
const val FAN_CONTROL = "Load Based Fan Control"
const val HEATING_CONTROL = "Load Based Heating Control"
const val COMPOSITE_CONTROL = "Composite Heat and Cool"
const val
        COMPRESSOR_SPEED = "Compressor Control"
const val PRESSURE_BASED_FC_ON = "Pressure Based Fan Control On"
const val SP_MIN = "Static Pressure Min"
const val SP_MAX = "Static Pressure Max"
const val SYSTEM_COOLING_SAT_MIN = "SystemCoolingSATMin"
const val SYSTEM_COOLING_SAT_MAX = "SystemCoolingSATMax"
const val SYSTEM_HEATING_SAT_MIN = "SystemHeatingSATMin"
const val SYSTEM_HEATING_SAT_MAX = "SystemHeatingSATMax"
const val CO2_THRESHOLD = "CO2 Threshold"
const val CO2_TARGET = "CO2 Target"
const val OPENING_RATE = "CO2 Damper Opening \nRate"
const val UNIVERSAL_IN1 = "Universal-In 1"
const val UNIVERSAL_IN2 = "Universal-In 2"
const val UNIVERSAL_IN3 = "Universal-In 3"
const val UNIVERSAL_IN4 = "Universal-In 4"
const val UNIVERSAL_IN5 = "Universal-In 5"
const val UNIVERSAL_IN6 = "Universal-In 6"
const val UNIVERSAL_IN7 = "Universal-In 7"
const val UNIVERSAL_IN8 = "Universal-In 8"