package a75f.io.ble;

/**
 * Created by ryanmattison on 7/24/17.
 */

public enum BLEAction {
    ACTION_GATT_CONNECTED,
    ACTION_GATT_CONNECTING,
    ACTION_GATT_DISCONNECTED,
    ACTION_GATT_SERVICES_DISCOVERED,
    ACTION_DATA_WROTE, ACTION_DATA_AVAILABLE
}
