package a75f.io.logic.bo.building.definitions;

/**
 * Created by Yinten isOn 8/17/2017.
 */

public enum Port
{
	RELAY_ONE, RELAY_TWO, RELAY_THREE, RELAY_FOUR, RELAY_FIVE, RELAY_SIX, RELAY_SEVEN, RELAY_EIGHT,
	ANALOG_OUT_ONE, ANALOG_OUT_TWO, ANALOG_IN_ONE, ANALOG_IN_TWO,TH1_IN,TH2_IN,
	SENSOR_RT, SENSOR_RH, SENSOR_CO2, SENSOR_VOC
}
