package a75f.io.logic.bo.building.definitions;

/**
 * Created by Yinten on 9/20/2017.
 */

public enum ProfileType
{
    LIGHT, TEST, SSE, HMP, VAV_REHEAT, VAV_SERIES_FAN, VAV_PARALLEL_FAN,
    SYSTEM_DEFAULT,SYSTEM_VAV_ANALOG_RTU, SYSTEM_VAV_STAGED_RTU, SYSTEM_VAV_HYBRID_RTU,SYSTEM_VAV_STAGED_VFD_RTU, SYSTEM_VAV_IE_RTU, SYSTEM_DAB_STAGED_RTU, SYSTEM_VAV_BACNET_RTU
}
