package a75f.io.logic.bo.building.definitions;

/**
 * Created by Yinten on 9/20/2017.
 */

public enum ProfileType
{
    LIGHT, TEST, SSE, HMP,PLC, EMR, DAB, VAV_REHEAT, VAV_SERIES_FAN, VAV_PARALLEL_FAN, OAO,
    SYSTEM_DEFAULT,SYSTEM_VAV_ANALOG_RTU, SYSTEM_VAV_STAGED_RTU,SYSTEM_VAV_HYBRID_RTU, SYSTEM_VAV_STAGED_VFD_RTU,SYSTEM_VAV_IE_RTU, SYSTEM_VAV_BACNET_RTU,
    SYSTEM_DAB_ANALOG_RTU,SYSTEM_DAB_STAGED_RTU,SYSTEM_DAB_HYBRID_RTU, SYSTEM_DAB_STAGED_VFD_RTU,
    SMARTSTAT_CONVENTIONAL_PACK_UNIT, SMARTSTAT_COMMERCIAL_PACK_UNIT, SMARTSTAT_HEAT_PUMP_UNIT, SMARTSTAT_TWO_PIPE_FCU, SMARTSTAT_FOUR_PIPE_FCU,
    TEMP_MONITOR, TEMP_INFLUENCE,DUAL_DUCT,MODBUS_UPS30,MODBUS_UPS400,MODBUS_UPS80,MODBUS_VRF,MODBUS_PAC, MODBUS_WLD,MODBUS_RRS,MODBUS_EM,MODBUS_EMS,MODBUS_ATS,MODBUS_UPS150,MODBUS_BTU,MODBUS_EMR,MODBUS_EMR_ZONE,
    MODBUS_UPS40K,MODBUS_UPSL,MODBUS_UPSV,MODBUS_UPSVL,MODBUS_VAV_BACnet, HYPERSTAT_SENSE, MODBUS_DEFAULT,BPOS,
    HYPERSTAT_CONVENTIONAL_PACKAGE_UNIT,HYPERSTAT_HEAT_PUMP_UNIT, HYPERSTAT_TWO_PIPE_FCU, HYPERSTAT_FOUR_PIPE_FCU,
    HYPERSTAT_VRV
}
