package a75f.io.logic.bo.building.definitions;

public enum StandaloneLogicalFanSpeeds {

    OFF,AUTO,FAN_LOW_CURRENT_OCCUPIED,FAN_LOW_OCCUPIED,FAN_LOW_ALL_TIMES, FAN_HIGH_CURRENT_OCCUPIED,FAN_HIGH_OCCUPIED,FAN_HIGH_ALL_TIMES, FAN_HIGH2_CURRENT_OCCUPIED,FAN_HIGH2_OCCUPIED,FAN_HIGH2_ALL_TIMES
}
