package a75f.io.logic.diag.otastatus

/**
 * Created by Manjunath K on 28-02-2023.
 */

enum class OtaStatus {
    OTA_REQUEST_RECEIVED,
    OTA_UPDATE_STARTED,
    OTA_REQUEST_IN_PROGRESS,
    OTA_FIRMWARE_DOWNLOAD_FAILED,
    OTA_CCU_TO_CM_FAILED,
    OTA_CCU_TO_CM_UPDATE_STARTED,
    OTA_CCU_TO_CM_PERCENT_COMPLETED_10,
    OTA_CCU_TO_CM_PERCENT_COMPLETED_50,
    OTA_CCU_TO_CM_PERCENT_COMPLETED_100,
    OTA_CCU_TO_CM_FIRMWARE_RECEIVED,
    OTA_CM_TO_DEVICE_PACKET_STARTED,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_10,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_20,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_30,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_40,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_50,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_60,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_70,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_80,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_90,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_100,
    OTA_SUCCEEDED,
    OTA_TIMEOUT,
    OTA_CM_TO_DEVICE_FAILED,
    NODE_STATUS_VALUE_FW_OTA_SUCCESSFUL,
    NODE_STATUS_VALUE_FW_OTA_FAIL_REBOOT_INTERRUPTION,
    NODE_STATUS_VALUE_FW_OTA_FAIL_NOT_FOR_ME_DEV_TYPE,
    NODE_STATUS_VALUE_FW_OTA_FAIL_NOT_FOR_ME_FW_VERSION,
    NODE_STATUS_VALUE_FW_OTA_FAIL_IMAGE_SIZE,
    NODE_STATUS_VALUE_FW_OTA_FAIL_EXT_FLASH_ERROR,
    NODE_STATUS_VALUE_FW_OTA_FAIL_IMAGE_VERIFICATION,
    NODE_STATUS_VALUE_FW_OTA_FAIL_INACTIVITY_TIMEOUT,
    NO_INFO
}