package a75f.io.logic.diag.otastatus

/**
 * Created by Manjunath K on 28-02-2023.
 */

enum class OtaStatus {
    OTA_REQUEST_RECEIVED,
    OTA_UPDATE_STARTED,
    OTA_REQUEST_IN_PROGRESS,
    OTA_FIRMWARE_DOWNLOAD_FAILED,
    OTA_CCU_TO_CM_FAILED,
    OTA_CCU_TO_CM_UPDATE_STARTED,
    OTA_CCU_TO_CM_PERCENT_COMPLETED_10,
    OTA_CCU_TO_CM_PERCENT_COMPLETED_50,
    OTA_CCU_TO_CM_PERCENT_COMPLETED_100,
    OTA_CCU_TO_CM_FIRMWARE_RECEIVED,
    OTA_CM_TO_DEVICE_PACKET_STARTED,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_10,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_20,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_30,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_40,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_50,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_60,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_70,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_80,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_90,
    OTA_CM_TO_DEVICE_PERCENT_COMPLETED_100,
    OTA_SUCCEEDED,
    OTA_TIMEOUT,
    OTA_CM_TO_DEVICE_FAILED,
    NODE_STATUS_VALUE_FW_OTA_SUCCESSFUL,
    NODE_STATUS_VALUE_FW_OTA_FAIL_REBOOT_INTERRUPTION,
    NODE_STATUS_VALUE_FW_OTA_FAIL_NOT_FOR_ME_DEV_TYPE,
    NODE_STATUS_VALUE_FW_OTA_FAIL_NOT_FOR_ME_FW_VERSION,
    NODE_STATUS_VALUE_FW_OTA_FAIL_IMAGE_SIZE,
    NODE_STATUS_VALUE_FW_OTA_FAIL_EXT_FLASH_ERROR,
    NODE_STATUS_VALUE_FW_OTA_FAIL_IMAGE_VERIFICATION,
    NODE_STATUS_VALUE_FW_OTA_FAIL_INACTIVITY_TIMEOUT,
    NO_INFO,
    OTA_UPDATE_FAILED,
    OTA_UPDATE_CANCELLED
}

enum class BundleOtaStatus {
    // 0-13
    OTA_REQUEST_RECEIVED,
    OTA_REQUEST_VALIDATION_FAILED,
    OTA_BAC_APP_DOWNLOADING,
    OTA_BAC_APP_DOWNLOAD_SUCCEEDED,
    OTA_BAC_APP_DOWNLOAD_FAILED,
    OTA_REMOTE_APP_DOWNLOADING,
    OTA_REMOTE_APP_DOWNLOAD_SUCCEEDED,
    OTA_REMOTE_APP_DOWNLOAD_FAILED,
    OTA_HOME_APP_DOWNLOADING,
    OTA_HOME_APP_DOWNLOAD_SUCCEEDED,
    OTA_HOME_APP_DOWNLOAD_FAILED,
    OTA_CCU_APP_DOWNLOADING,
    OTA_CCU_APP_DOWNLOAD_SUCCEEDED,
    OTA_CCU_APP_DOWNLOAD_FAILED,

    //14-27
    OTA_BAC_APP_INSTALLING,
    OTA_BAC_APP_INSTALL_SUCCEEDED,
    OTA_BAC_APP_INSTALL_FAILED,
    OTA_REMOTE_APP_INSTALLING,
    OTA_REMOTE_APP_INSTALL_SUCCEEDED,
    OTA_REMOTE_APP_INSTALL_FAILED,
    OTA_HOME_APP_INSTALLING,
    OTA_HOME_APP_INSTALL_SUCCEEDED,
    OTA_HOME_APP_INSTALL_FAILED,
    OTA_CCU_APP_INSTALLING,
    OTA_CCU_APP_INSTALL_SUCCEEDED,
    OTA_CCU_APP_INSTALL_FAILED,
    OTA_UPDATE_SUCCEEDED,
    OTA_UPDATE_CANCELLED,
}

enum class OtaState {
    NO_INFO_STATE, FIRMWARE_RECEIVED, CM_DEVICE_IN_PROGRESS, FIRMWARE_COPY_AVAILABLE, CM_DEVICE_TIMEOUT
}