package a75f.io.logic.diag.otastatus

/**
 * Created by Manjunath K on 28-02-2023.
 */

enum class SequenceOtaStatus {
    SEQ_REQUEST_RECEIVED,
    SEQ_UPDATE_STARTED,
    SEQ_REQUEST_IN_PROGRESS,
    SEQ_FIRMWARE_DOWNLOAD_FAILED,
    SEQ_CCU_TO_CM_FAILED,
    SEQ_CCU_TO_CM_UPDATE_STARTED,
    SEQ_CCU_TO_CM_PERCENT_COMPLETED_10,
    SEQ_CCU_TO_CM_PERCENT_COMPLETED_50,
    SEQ_CCU_TO_CM_PERCENT_COMPLETED_100,
    SEQ_CCU_TO_CM_FIRMWARE_RECEIVED,
    SEQ_CM_TO_DEVICE_PACKET_STARTED,
    SEQ_CM_TO_DEVICE_PERCENT_COMPLETED_10,
    SEQ_CM_TO_DEVICE_PERCENT_COMPLETED_20,
    SEQ_CM_TO_DEVICE_PERCENT_COMPLETED_30,
    SEQ_CM_TO_DEVICE_PERCENT_COMPLETED_40,
    SEQ_CM_TO_DEVICE_PERCENT_COMPLETED_50,
    SEQ_CM_TO_DEVICE_PERCENT_COMPLETED_60,
    SEQ_CM_TO_DEVICE_PERCENT_COMPLETED_70,
    SEQ_CM_TO_DEVICE_PERCENT_COMPLETED_80,
    SEQ_CM_TO_DEVICE_PERCENT_COMPLETED_90,
    SEQ_CM_TO_DEVICE_PERCENT_COMPLETED_100,
    SEQ_SUCCEEDED,
    SEQ_TIMEOUT,
    SEQ_CM_TO_DEVICE_FAILED,
    NODE_STATUS_VALUE_FW_OTA_SUCCESSFUL,
    NODE_STATUS_VALUE_FW_OTA_FAIL_REBOOT_INTERRUPTION,
    NODE_STATUS_VALUE_FW_OTA_FAIL_NOT_FOR_ME_DEV_TYPE,
    NODE_STATUS_VALUE_FW_OTA_FAIL_NOT_FOR_ME_FW_VERSION,
    NODE_STATUS_VALUE_FW_OTA_FAIL_IMAGE_SIZE,
    NODE_STATUS_VALUE_FW_OTA_FAIL_EXT_FLASH_ERROR,
    NODE_STATUS_VALUE_FW_OTA_FAIL_IMAGE_VERIFICATION,
    NODE_STATUS_VALUE_FW_OTA_FAIL_INACTIVITY_TIMEOUT,
    NO_INFO,
    SEQ_UPDATE_FAILED,
    SEQ_UPDATE_CANCELLED
}


enum class SequenceOtaState {
    NO_INFO_STATE, SEQUENCE_RECEIVED, CM_DEVICE_IN_PROGRESS, SEQUENCE_COPY_AVAILABLE, CM_DEVICE_TIMEOUT, SEQUENCE_UPDATE_COMPLETE, SEQUENCE_UPDATE_FAILED
}