package a75f.io.domain.config

import a75f.io.domain.api.Entity


/**
 * A profile configuration binds a particular UI element or item to its domain Name.
 * Entity builder and other framework components would use this information to extract other entity
 * specifications from the domain model.
 * Default configurations and UI options could be generated by referring to this name in the domain model.
 * CCU has to know the domain name of any UI config that has to be added.This is a hard dependency.
 */

/**
 * A UI config like autoForcedEnabled would be the simplest with an enabled status and associated value.
 */
open class ProfileConfig (var enabled: Boolean, val domainName : String) {
    var currentVal = 0.0
}

/**
 * A generic port config without anu specific actuator specified.
 */
open class PortConfig(enabled: Boolean, domainName: String, var association : String)
    : ProfileConfig(enabled, domainName)

/**
 * Relay config with actuator type.
 */
open class RelayConfig(enabled: Boolean, domainName: String, association : String, var actuatorType : String)
    : PortConfig(enabled, domainName, association)

/**
 * Analog input config with actuator type.
 */
open class AnalogInConfig(enabled: Boolean, domainName: String, association: String, var sensorType : Int)
    : PortConfig(enabled, domainName, association)

/**
 * Analog output config with actuator type.
 */
open class AnalogOutConfig(enabled: Boolean, domainName: String, association : String, var minVoltage : Double, var maxVoltage : Double)
    : PortConfig (enabled, domainName, association)



open class EntityConfig() {
    val tobeAdded = mutableListOf<Entity>()
    val tobeDeleted = mutableListOf<Entity>()
}