package a75f.io.domain.config


/**
 * A profile configuration binds a particular UI element or item to its domain Name.
 * Entity builder and other framework components would use this information to extract other entity
 * specifications from the domain model.
 * Default configurations and UI options could be generated by referring to this name in the domain model.
 * CCU has to know the domain name of any UI config that has to be added.This is a hard dependency.
 */

/**
 * A UI config like autoForcedEnabled would be the simplest with an enabled status and associated value.
 */
open class BaseConfig (val domainName : String) {
    lateinit var disName : String
}

open class EnableConfig (domainName: String, var enabled: Boolean = false) : BaseConfig(domainName)

open class ValueConfig (domainName: String, var currentVal: Double = 0.0) : BaseConfig(domainName) {
    var minVal : Double = 0.0
    var maxVal : Double = 0.0
    var incVal : Double = 0.0
}

/**
 * A generic port config without anu specific actuator specified.
 */
open class AssociationConfig(var domainName : String, var associationVal : Int = 0)

/**
 * Relay config with actuator type.
 */
class RelayAssociationConfig(domainName: String, association : Int, var actuatorType : String = "NC")
    : AssociationConfig(domainName, association)

/**
 * Analog input config with actuator type.
 */
class AnalogInAssociationConfig(domainName: String, association: Int, var sensorType : Int)
    : AssociationConfig(domainName, association)

/**
 * Analog output config with actuator type.
 */
class AnalogOutAssociationConfig(domainName: String, association : Int, var minVoltage : Double, var maxVoltage : Double)
    : AssociationConfig (domainName, association)


fun <T : BaseConfig> List<T>.containsConfig(domainName : String) : Boolean {
    return this.find {it.domainName == domainName} != null
}

fun <T : BaseConfig> List<T>.getConfig(domainName : String) : T? {
    return this.find {it.domainName == domainName}
}
fun <T : AssociationConfig> List<T>.getConfig(domainName : String) : T? {
    return this.find {it.domainName == domainName}
}

