package a75f.io.domain

import a75f.io.domain.api.DomainName
import a75f.io.domain.api.Point
import a75f.io.domain.equips.DomainEquip

class OAOEquip(equipRef: String) : DomainEquip(equipRef) {

    val outsideDamperMinDrive = Point(DomainName.outsideDamperMinDrive, equipRef)
    val outsideDamperMaxDrive = Point(DomainName.outsideDamperMaxDrive, equipRef)
    val returnDamperMinDrive = Point(DomainName.returnDamperMinDrive, equipRef)
    val returnDamperMaxDrive = Point(DomainName.returnDamperMaxDrive, equipRef)
    val outsideDamperMinOpenDuringRecirculation = Point(DomainName.outsideDamperMinOpenDuringRecirculation, equipRef)
    val outsideDamperMinOpenDuringConditioning = Point(DomainName.outsideDamperMinOpenDuringConditioning, equipRef)
    val outsideDamperMinOpenDuringFanLow = Point(DomainName.outsideDamperMinOpenDuringFanLow, equipRef)
    val outsideDamperMinOpenDuringFanMedium = Point(DomainName.outsideDamperMinOpenDuringFanMedium, equipRef)
    val outsideDamperMinOpenDuringFanHigh = Point(DomainName.outsideDamperMinOpenDuringFanHigh, equipRef)
    val returnDamperMinOpen = Point(DomainName.returnDamperMinOpen, equipRef)
    val exhaustFanStage1Threshold = Point(DomainName.exhaustFanStage1Threshold, equipRef)
    val exhaustFanStage2Threshold = Point(DomainName.exhaustFanStage2Threshold, equipRef)
    val currentTransformerType = Point(DomainName.currentTransformerType, equipRef)
    val co2Threshold = Point(DomainName.co2Threshold, equipRef)
    val exhaustFanHysteresis = Point(DomainName.exhaustFanHysteresis, equipRef)
    val usePerRoomCO2Sensing = Point(DomainName.usePerRoomCO2Sensing, equipRef)
    val systemPurgeOutsideDamperMinPos = Point(DomainName.systemPurgeOutsideDamperMinPos, equipRef)
    val enhancedVentilationOutsideDamperMinOpen = Point(DomainName.enhancedVentilationOutsideDamperMinOpen, equipRef)
    val relay1 = Point(DomainName.relay1, equipRef)

    val returnAirCo2 = Point(DomainName.returnAirCo2, equipRef)
    val economizingLoopOutput = Point(DomainName.economizingLoopOutput, equipRef)
    val economizingAvailable = Point(DomainName.economizingAvailable, equipRef)
    val insideEnthalpy = Point(DomainName.insideEnthalpy, equipRef)
    val outsideEnthalpy = Point(DomainName.outsideEnthalpy, equipRef)
    val outsideTemperature = Point(DomainName.outsideTemperature, equipRef)
    val mixedAirTemperature = Point(DomainName.mixedAirTemperature, equipRef)
    val outsideAirFinalLoopOutput = Point(DomainName.outsideAirFinalLoopOutput, equipRef)
    val returnDamperCmd = Point(DomainName.returnDamperCmd, equipRef)
    val outsideDamperCmd = Point(DomainName.outsideDamperCmd, equipRef)
    val matThrottle = Point(DomainName.matThrottle, equipRef)
    val co2WeightedAverage = Point(DomainName.co2WeightedAverage, equipRef)
    val outsideAirCalculatedMinDamper = Point(DomainName.outsideAirCalculatedMinDamper, equipRef)
    val dcvAvailable = Point(DomainName.dcvAvailable, equipRef)

    val outsideDamperMixedAirTarget = Point(DomainName.outsideDamperMixedAirTarget, equipRef)
    val outsideDamperMixedAirMinimum = Point(DomainName.outsideDamperMixedAirMinimum, equipRef)
    val economizingToMainCoolingLoopMap = Point(DomainName.economizingToMainCoolingLoopMap, equipRef)
    val economizingMinTemperature = Point(DomainName.economizingMinTemperature, equipRef)
    val economizingDryBulbThreshold = Point(DomainName.economizingDryBulbThreshold, equipRef)
    val economizingMaxTemperature = Point(DomainName.economizingMaxTemperature, equipRef)
    val economizingMinHumidity = Point(DomainName.economizingMinHumidity, equipRef)
    val economizingMaxHumidity = Point(DomainName.economizingMaxHumidity, equipRef)
    val enthalpyDuctCompensationOffset = Point(DomainName.enthalpyDuctCompensationOffset, equipRef)
    val co2DamperOpeningRate = Point(DomainName.co2DamperOpeningRate, equipRef)
    val systemPrePurgeRuntimeTuner = Point(DomainName.systemPrePurgeRuntimeTuner, equipRef)
    val systemPrePurgeOccupiedTimeOffsetTuner = Point(DomainName.systemPrePurgeOccupiedTimeOffsetTuner, equipRef)
    val systemPostPurgeRuntimeTuner = Point(DomainName.systemPostPurgeRuntimeTuner, equipRef)
    val systemPostPurgeOccupiedTimeOffsetTuner = Point(DomainName.systemPostPurgeOccupiedTimeOffsetTuner, equipRef)
    val weatherOutsideTemp = Point(DomainName.weatherOutsideTemp, equipRef)
    val weatherOutsideHumidity = Point(DomainName.weatherOutsideHumidity, equipRef)
    val systemPurgeDabDamperMinOpenMultiplier = Point(DomainName.systemPurgeDabDamperMinOpenMultiplier, equipRef)
    val systemPurgeDabMinFanLoopOutput = Point(DomainName.systemPurgeDabMinFanLoopOutput, equipRef)
    val systemPurgeVavDamperMinOpenMultiplier = Point(DomainName.systemPurgeVavDamperMinOpenMultiplier, equipRef)
    val systemPurgeVavMinFanLoopOutput = Point(DomainName.systemPurgeVavMinFanLoopOutput, equipRef)
    val systemPrePurgeFanSpeedTuner = Point(DomainName.systemPrePurgeFanSpeedTuner, equipRef)
    val systemPostPurgeFanSpeedTuner = Point(DomainName.systemPostPurgeFanSpeedTuner, equipRef)
}