package a75f.io.renatus.bacnet.util

const val BACNET = "BACNET"
const val MODEL = "Model"
const val LOADING = "Loading Bacnet Models"
const val SLAVE_ID = "Slave Id"
const val SELECT_ALL = "Select All Parameters"
const val SET = "SET"
const val PARAMETER = "PARAMETER"
const val SAME_AS_PARENT = "Same As Parent"
const val DISPLAY_UI = "DISPLAY UI"
const val SAVING = "Saving Modbus configuration"
const val SAVED = "Saved all the configuration"
const val NO_MODEL_DATA_FOUND = "No model data found..!"
const val MODBUS_DEVICE_LIST_NOT_FOUND = "Modbus device list not found..!"
const val NO_INTERNET = "Unable to fetch equipments, please confirm your Wifi connectivity"
const val WARNING = "Warning"
const val OK = "Ok"
const val SEARCH_MODEL = "Search model"
const val SEARCH_SLAVE_ID = "Search Slave Id"
const val SELECT_MODEL = "Select Model"
const val SELECTED_MODEL = "Selected Model"
const val SELECT_ADDRESS = "Select Address"
const val CONST_AUTO_DISCOVERY = "Initiating auto discovery… This may take a few mins"