@startuml
Client -> Server: Connect
Client -> Server: Send GATT Services Request
Server -> Client: Send GATT Services
Client -> Server: Read PIN
Server -> Client: Respond PIN
Client -> User: Show Pin Dialog
User -> Client: Enter and confirm PIN
Client -> Server: Write Zone Configuration Status
Server -> Client: Echo Zone Configuration Status
Client -> Server: Write BLE_LINK_KEY
Server -> Client: Echo BLE_LINK_KEY
Client -> Server: Write ROOM_NAME
Server -> Client: Echo ROOM_NAME
Client -> Server: Write LW_MESH_PAIRING_ADDRESS
Server -> Client: Echo LW_MESH_PAIRING_ADDRESS
Client -> Server: Write LW_MESH_SECURITY_KEY
Server -> Client: Echo LW_MESH_SECURITY_KEY
Client -> Server: Write FIRMWARE_SIGNATURE_KEY
Server -> Client: Echo FIRMWARE_SIGNATURE_KEY
Client -> Server: Calculate CRC Write to Server
Server -> Client: Echo CRC
Client -> Server: Read Request for Zone Configuration Status
Server -> Client: Echo ZONE_CONFIG_STATUS
Client -> User: Display success if ZONE_CONFIG_STATUS = FINISHED, or failure otherwise.

@enduml