package a75f.io.domain.equips

import a75f.io.domain.BuildConfig
import a75f.io.domain.api.DomainName
import a75f.io.domain.api.Point

class BuildingEquip (equipRef : String) : DomainEquip(equipRef) {

    val CARRIER_PROD = "carrier_prod"
    val zoneTemperatureDeadLeeway = Point(DomainName.zoneTemperatureDeadLeeway, equipRef)
    val heartBeatsToSkip = Point(DomainName.heartBeatsToSkip, equipRef)
    val humidityCompensationOffset = Point(DomainName.humidityCompensationOffset, equipRef)
    val clockUpdateInterval = Point(DomainName.clockUpdateInterval, equipRef)
    val perDegreeHumidityFactor = Point(DomainName.perDegreeHumidityFactor, equipRef)
    val ccuAlarmVolumeLevel = Point(DomainName.ccuAlarmVolumeLevel, equipRef)
    val userLimitSpread = Point(DomainName.userLimitSpread, equipRef)
    val proportionalKFactor = Point(DomainName.proportionalKFactor, equipRef)
    val integralKFactor = Point(DomainName.integralKFactor, equipRef)
    val pidIntegralTime = Point(DomainName.pidIntegralTime, equipRef)

    val rebalanceHoldTime = Point(DomainName.rebalanceHoldTime, equipRef)
    val airflowSampleWaitTime = Point(DomainName.airflowSampleWaitTime, equipRef)
    val buildingLimitAlertTimer = Point(DomainName.buildingLimitAlertTimer, equipRef)
    val constantTempAlertTime = Point(DomainName.constantTempAlertTime, equipRef)
    val abnormalCurTempRiseTrigger = Point(DomainName.abnormalCurTempRiseTrigger, equipRef)
    val heatingAirflowTemp = Point(DomainName.heatingAirflowTemp, equipRef)
    val coolingAirflowTemp = Point(DomainName.coolingAirflowTemp, equipRef)
    val adrHeatingDeadband = Point(DomainName.adrHeatingDeadband, equipRef)
    val adrCoolingDeadband = Point(DomainName.adrCoolingDeadband, equipRef)
    val autoAwayTime = Point(DomainName.autoAwayTime, equipRef)
    val cmResetCommandTimer = Point(DomainName.cmResetCommandTimer, equipRef)
    val forcedOccupiedTime = Point(DomainName.forcedOccupiedTime, equipRef)
    val zoneDeadTime = Point(DomainName.zoneDeadTime, equipRef)
    val displayUnit = Point(DomainName.displayUnit, equipRef)
    val coolingPreconditioningRate = Point(DomainName.coolingPreconditioningRate, equipRef)
    val cmHeartBeatInterval = Point(DomainName.cmHeartBeatInterval, equipRef)
    val autoAwaySetback = Point(DomainName.autoAwaySetback, equipRef)
    val heatingPreconditioningRate = Point(DomainName.heatingPreconditioningRate, equipRef)
    val cmTempPercentDeadZonesAllowed = Point(DomainName.cmTempPercentDeadZonesAllowed, equipRef)
    val ccuNetworkWatchdogTimeout = Point(DomainName.ccuNetworkWatchdogTimeout, equipRef)
    val auxHeating1Activate = Point(DomainName.auxHeating1Activate, equipRef)
    val auxHeating2Activate = Point(DomainName.auxHeating2Activate, equipRef)
    val waterValveSamplingWaitTime = Point(DomainName.waterValveSamplingWaitTime, equipRef)
    val waterValveSamplingOnTime = Point(DomainName.waterValveSamplingOnTime, equipRef)
    val waterValveSamplingLoopDeadbandOnTime = Point(DomainName.waterValveSamplingLoopDeadbandOnTime, equipRef)
    val waterValveSamplingLoopDeadbandWaitTime = Point(DomainName.waterValveSamplingLoopDeadbandWaitTime, equipRef)

    val vavZonePrioritySpread = Point(DomainName.vavZonePrioritySpread, equipRef)
    val vavZonePriorityMultiplier = Point(DomainName.vavZonePriorityMultiplier, equipRef)
    val vavIntegralKfactor = Point(DomainName.vavIntegralKfactor, equipRef)
    val vavZoneVocTarget = Point(DomainName.vavZoneVocTarget, equipRef)
    val vavZoneCo2Threshold = Point(DomainName.vavZoneCo2Threshold, equipRef)
    val vavZoneCo2Target = Point(DomainName.vavZoneCo2Target, equipRef)
    val vavCoolingDeadband = Point(DomainName.vavCoolingDeadband, equipRef)
    val vavHeatingDeadband = Point(DomainName.vavHeatingDeadband, equipRef)
    val vavZoneVOCThreshold = Point(DomainName.vavZoneVoCThreshold, equipRef)
    val vavTemperatureProportionalRange = Point(DomainName.vavTemperatureProportionalRange, equipRef)
    val vavProportionalKFactor = Point(DomainName.vavProportionalKFactor, equipRef)
    val valveActuationStartDamperPosDuringSysHeating = Point(DomainName.valveActuationStartDamperPosDuringSysHeating, equipRef)
    val vavHeatingDeadbandMultiplier = Point(DomainName.vavHeatingDeadbandMultiplier, equipRef)
    val vavCoolingDeadbandMultiplier = Point(DomainName.vavCoolingDeadbandMultiplier, equipRef)
    val vavStageDownTimerCounter = Point(DomainName.vavStageDownTimerCounter, equipRef)
    val vavOutsideTempCoolingLockout = Point(DomainName.vavOutsideTempCoolingLockout, equipRef)
    val vavRelayDeactivationHysteresis = Point(DomainName.vavRelayDeactivationHysteresis, equipRef)
    val fanControlOnFixedTimeDelay = Point(DomainName.fanControlOnFixedTimeDelay, equipRef)
    val vavAnalogFanSpeedMultiplier = Point(DomainName.vavAnalogFanSpeedMultiplier, equipRef)
    val vavTargetCumulativeDamper = Point(DomainName.vavTargetCumulativeDamper, equipRef)
    val vavOutsideTempHeatingLockout = Point(DomainName.vavOutsideTempHeatingLockout, equipRef)
    val vavHumidityHysteresis = Point(DomainName.vavHumidityHysteresis, equipRef)
    val reheatZoneMaxDischargeTemp = Point(DomainName.reheatZoneMaxDischargeTemp, equipRef)
    val vavStageUpTimerCounter = Point(DomainName.vavStageUpTimerCounter, equipRef)
    val reheatZoneToDATMinDifferential = Point(DomainName.reheatZoneToDATMinDifferential, equipRef)
    val reheatZoneDischargeTempOffset = Point(DomainName.reheatZoneDischargeTempOffset, equipRef)
    val vavModeChangeOverHysteresis = Point(DomainName.vavModeChangeOverHysteresis, equipRef)
    val vavTemperatureIntegralTime = Point(DomainName.vavTemperatureIntegralTime, equipRef)

    val satIgnoreRequest = Point(DomainName.satIgnoreRequest, equipRef)
    val satSPMax = Point(DomainName.satSPMax, equipRef)
    val satSPMin = Point(DomainName.satSPMin, equipRef)
    val satSPInit = Point(DomainName.satSPInit, equipRef)
    val satTimeDelay = Point(DomainName.satTimeDelay, equipRef)
    val satSPTrim = Point(DomainName.satSPTrim, equipRef)
    val satSPResMax = Point(DomainName.satSPResMax, equipRef)
    val satTimeInterval = Point(DomainName.satTimeInterval, equipRef)
    val satSPRes = Point(DomainName.satSPRes, equipRef)

    val staticPressureIgnoreRequest = Point(DomainName.staticPressureIgnoreRequest, equipRef)
    val staticPressureSPMin = Point(DomainName.staticPressureSPMin, equipRef)
    val staticPressureSPRes = Point(DomainName.staticPressureSPRes, equipRef)
    val staticPressureSPMax = Point(DomainName.staticPressureSPMax, equipRef)
    val staticPressureSPInit = Point(DomainName.staticPressureSPInit, equipRef)
    val staticPressureTimeDelay = Point(DomainName.staticPressureTimeDelay, equipRef)
    val staticPressureTimeInterval = Point(DomainName.staticPressureTimeInterval, equipRef)
    val staticPressureSPResMax = Point(DomainName.staticPressureSPResMax, equipRef)
    val staticPressureSPTrim = Point(DomainName.staticPressureSPTrim, equipRef)


    val co2IgnoreRequest = Point(DomainName.co2IgnoreRequest, equipRef)
    val co2SPTrim = Point(DomainName.co2SPTrim, equipRef)
    val co2SPMax = Point(DomainName.co2SPMax, equipRef)
    val co2SPRes = Point(DomainName.co2SPRes, equipRef)
    val co2TimeDelay = Point(DomainName.co2TimeDelay, equipRef)
    val co2SPInit = Point(DomainName.co2SPInit, equipRef)
    val co2SPMin = Point(DomainName.co2SPMin, equipRef)
    val co2TimeInterval = Point(DomainName.co2TimeInterval, equipRef)
    val co2SPResMax = Point(DomainName.co2SPResMax, equipRef)

    val vavAirflowCFMIntegralKFactor = Point(DomainName.vavAirflowCFMIntegralKFactor, equipRef)
    val vavAirflowCFMProportionalKFactor = Point(DomainName.vavAirflowCFMProportionalKFactor, equipRef)
    val vavAirflowCFMIntegralTime = Point(DomainName.vavAirflowCFMIntegralTime, equipRef)
    val vavAirflowCFMProportionalRange = Point(DomainName.vavAirflowCFMProportionalRange, equipRef)

    val standaloneCoolingDeadband = Point(DomainName.standaloneCoolingDeadband, equipRef)
    val standaloneHeatingDeadband = Point(DomainName.standaloneHeatingDeadband, equipRef)
    val standaloneStage2CoolingLowerOffset = Point(DomainName.standaloneStage2CoolingLowerOffset, equipRef)
    val standaloneStage1HeatingUpperOffset = Point(DomainName.standaloneStage1HeatingUpperOffset, equipRef)
    val standaloneStage1HeatingLowerOffset = Point(DomainName.standaloneStage1HeatingLowerOffset, equipRef)
    val standaloneVOCThreshold = Point(DomainName.standaloneVocThreshold, equipRef)
    val standaloneCoolingPreconditioningRate = Point(DomainName.standaloneCoolingPreconditioningRate, equipRef)
    val standaloneHeatingPreconditioningRate = Point(DomainName.standaloneHeatingPreconditioningRate, equipRef)
    val standaloneStage1CoolingUpperOffset = Point(DomainName.standaloneStage1CoolingUpperOffset, equipRef)
    val standaloneCO2Target = Point(DomainName.standaloneCo2Target, equipRef)
    val standaloneAirflowSampleWaitTime = Point(DomainName.standaloneAirflowSampleWaitTime, equipRef)
    val standaloneStage1Hysteresis = Point(DomainName.standaloneStage1Hysteresis, equipRef)
    val standaloneStage1CoolingLowerOffset = Point(DomainName.standaloneStage1CoolingLowerOffset, equipRef)
    val standaloneCO2Threshold = Point(DomainName.standaloneCo2Threshold, equipRef)
    val standaloneVOCTarget = Point(DomainName.standaloneVocTarget, equipRef)
    val standaloneCoolingDeadbandMultiplier = Point(DomainName.standaloneCoolingDeadbandMultiplier, equipRef)
    val standaloneHeatingDeadbandMultiplier = Point(DomainName.standaloneHeatingDeadbandMultiplier, equipRef)
    val standaloneStage2HeatingLowerOffset = Point(DomainName.standaloneStage2HeatingLowerOffset, equipRef)
    val standaloneStage2CoolingUpperOffset = Point(DomainName.standaloneStage2CoolingUpperOffset, equipRef)
    val standaloneTemperatureProportionalRange = Point(DomainName.standaloneTemperatureProportionalRange, equipRef)
    val standaloneProportionalKFactor = Point(DomainName.standaloneProportionalKFactor, equipRef)
    val standaloneIntegralKFactor = Point(DomainName.standaloneIntegralKFactor, equipRef)
    val standaloneRelayActivationHysteresis = Point(DomainName.standaloneRelayActivationHysteresis, equipRef)
    val standaloneHumidityHysteresis = Point(DomainName.standaloneHumidityHysteresis, equipRef)
    val standaloneTemperatureIntegralTime = Point(DomainName.standaloneTemperatureIntegralTime, equipRef)
    val standaloneAnalogFanSpeedMultiplier = Point(DomainName.standaloneAnalogFanSpeedMultiplier, equipRef)
    val standaloneStage2HeatingUpperOffset = Point(DomainName.standaloneStage2HeatingUpperOffset, equipRef)

    val dabStageDownTimerCounter = Point(getDisplayNameFromVariation(DomainName.dabStageDownTimerCounter), equipRef)
    val dabIntegralKFactor = Point(getDisplayNameFromVariation(DomainName.dabIntegralKFactor), equipRef)
    val dabModeChangeoverHysteresis = Point(getDisplayNameFromVariation(DomainName.dabModeChangeoverHysteresis), equipRef)
    val dabAnalogFanSpeedMultiplier = Point(getDisplayNameFromVariation(DomainName.dabAnalogFanSpeedMultiplier), equipRef)
    val dabZonePrioritySpread = Point(getDisplayNameFromVariation(DomainName.dabZonePrioritySpread), equipRef)
    val dabHeatingDeadbandMultiplier = Point(getDisplayNameFromVariation(DomainName.dabHeatingDeadbandMultiplier), equipRef)
    val dabTemperatureProportionalRange = Point(getDisplayNameFromVariation(DomainName.dabTemperatureProportionalRange), equipRef)
    val dabRelayDeactivationHysteresis = Point(getDisplayNameFromVariation(DomainName.dabRelayDeactivationHysteresis), equipRef)
    val dabZoneVOCTarget = Point(getDisplayNameFromVariation(DomainName.dabZoneVocTarget), equipRef)
    val dabZoneVOCThreshold = Point(getDisplayNameFromVariation(DomainName.dabZoneVocThreshold), equipRef)
    val dabTargetCumulativeDamper = Point(getDisplayNameFromVariation(DomainName.dabTargetCumulativeDamper), equipRef)
    val dabStageUpTimerCounter = Point(getDisplayNameFromVariation(DomainName.dabStageUpTimerCounter), equipRef)
    val dabZoneCO2Target = Point(getDisplayNameFromVariation(DomainName.dabZoneCo2Target), equipRef)
    val dabProportionalKFactor = Point(getDisplayNameFromVariation(DomainName.dabProportionalKFactor), equipRef)
    val dabZonePriorityMultiplier = Point(getDisplayNameFromVariation(DomainName.dabZonePriorityMultiplier), equipRef)
    val dabTemperatureIntegralTime = Point(getDisplayNameFromVariation(DomainName.dabTemperatureIntegralTime), equipRef)
    val dabCoolingDeadband = Point(getDisplayNameFromVariation(DomainName.dabCoolingDeadband), equipRef)
    val dabZoneCO2Threshold = Point(getDisplayNameFromVariation(DomainName.dabZoneCo2Threshold), equipRef)
    val dabHeatingDeadband = Point(getDisplayNameFromVariation(DomainName.dabHeatingDeadband), equipRef)
    val dabCoolingDeadbandMultiplier = Point(getDisplayNameFromVariation(DomainName.dabCoolingDeadbandMultiplier), equipRef)
    val dabOutsideTempHeatingLockout = Point(getDisplayNameFromVariation(DomainName.dabOutsideTempHeatingLockout), equipRef)
    val dabHumidityHysteresis = Point(getDisplayNameFromVariation(DomainName.dabHumidityHysteresis), equipRef)
    val dabOutsideTempCoolingLockout = Point(getDisplayNameFromVariation(DomainName.dabOutsideTempCoolingLockout), equipRef)
    val dabReheatRelayActivationHysteresis = Point(getDisplayNameFromVariation(DomainName.dabReheatRelayActivationHysteresis), equipRef)
    val dabReheatTemperatureIntegralTime = Point(getDisplayNameFromVariation(DomainName.dabReheatTemperatureIntegralTime), equipRef)
    val reheatTempOffset = Point(DomainName.reheatTempOffset, equipRef)
    val dabReheatTemperatureProportionalRange = Point(getDisplayNameFromVariation(DomainName.dabReheatTemperatureProportionalRange), equipRef)
    val dabReheatIntegralKFactor = Point(getDisplayNameFromVariation(DomainName.dabReheatIntegralKFactor), equipRef)
    val reheatProportionalKFactor = Point(DomainName.reheatProportionalKFactor, equipRef)

    //TI
    val tiCoolingDeadbandMultiplier = Point(DomainName.tiCoolingDeadbandMultiplier, equipRef)
    val tiIntegralKFactor = Point(DomainName.tiIntegralKFactor, equipRef)
    val tiTemperatureProportionalRange = Point(DomainName.tiTemperatureProportionalRange, equipRef)
    val tiHeatingDeadband = Point(DomainName.tiHeatingDeadband, equipRef)
    val tiTemperatureIntegralTime = Point(DomainName.tiTemperatureIntegralTime, equipRef)
    val tiHeatingDeadbandMultiplier = Point(DomainName.tiHeatingDeadbandMultiplier, equipRef)
    val tiZonePrioritySpread = Point(DomainName.tiZonePrioritySpread, equipRef)
    val tiZonePriorityMultiplier = Point(DomainName.tiZonePriorityMultiplier, equipRef)
    val tiProportionalKFactor = Point(DomainName.tiProportionalKFactor, equipRef)
    val tiCoolingDeadband = Point(DomainName.tiCoolingDeadband, equipRef)

    //OAO
    val outsideDamperMixedAirMinimum = Point(DomainName.outsideDamperMixedAirMinimum, equipRef)
    val economizingToMainCoolingLoopMap = Point(DomainName.economizingToMainCoolingLoopMap, equipRef)
    val systemPrePurgeFanSpeedTuner = Point(DomainName.systemPrePurgeFanSpeedTuner, equipRef)
    val co2DamperOpeningRate = Point(DomainName.co2DamperOpeningRate, equipRef)
    val systemPostPurgeRuntimeTuner = Point(DomainName.systemPostPurgeRuntimeTuner, equipRef)
    val economizingMinTemperature = Point(DomainName.economizingMinTemperature, equipRef)
    val economizingMaxTemperature = Point(DomainName.economizingMaxTemperature, equipRef)
    val economizingMinHumidity = Point(DomainName.economizingMinHumidity, equipRef)
    val outsideDamperMixedAirTarget = Point(DomainName.outsideDamperMixedAirTarget, equipRef)
    val systemPrePurgeRuntimeTuner = Point(DomainName.systemPrePurgeRuntimeTuner, equipRef)
    val economizingMaxHumidity = Point(DomainName.economizingMaxHumidity, equipRef)
    val systemPrePurgeOccupiedTimeOffsetTuner = Point(DomainName.systemPrePurgeOccupiedTimeOffsetTuner, equipRef)
    val enthalpyDuctCompensationOffset = Point(DomainName.enthalpyDuctCompensationOffset, equipRef)
    val systemPostPurgeFanSpeedTuner = Point(DomainName.systemPostPurgeFanSpeedTuner, equipRef)
    val systemPostPurgeOccupiedTimeOffsetTuner = Point(DomainName.systemPostPurgeOccupiedTimeOffsetTuner, equipRef)
    val systemPurgeDabDamperMinOpenMultiplier = Point(getDisplayNameFromVariation(DomainName.systemPurgeDabDamperMinOpenMultiplier), equipRef)
    val systemPurgeVavMinFanLoopOutput = Point(DomainName.systemPurgeVavMinFanLoopOutput, equipRef)
    val systemPurgeDabMinFanLoopOutput = Point(getDisplayNameFromVariation(DomainName.systemPurgeDabMinFanLoopOutput), equipRef)
    val systemPurgeVavDamperMinOpenMultiplier = Point(DomainName.systemPurgeVavDamperMinOpenMultiplier, equipRef)
    val economizingDryBulbThreshold = Point(DomainName.economizingDryBulbThreshold, equipRef)

    val dualDuctZoneVocTarget = Point(DomainName.dualDuctZoneVocTarget, equipRef)
    val dualDuctZoneCO2Target = Point(DomainName.dualDuctZoneCo2Target, equipRef)
    val dualDuctCoolingDeadband = Point(DomainName.dualDuctCoolingDeadband, equipRef)
    val dualDuctIntegralKFactor = Point(DomainName.dualDuctIntegralKFactor, equipRef)
    val dualDuctZoneVOCThreshold = Point(DomainName.dualDuctZoneVocThreshold, equipRef)
    val dualDuctZoneCO2Threshold = Point(DomainName.dualDuctZoneCo2Threshold, equipRef)
    val dualDuctTemperatureIntegralTime = Point(DomainName.dualDuctTemperatureIntegralTime, equipRef)
    val dualDuctProportionalKFactor = Point(DomainName.dualDuctProportionalKFactor, equipRef)
    val dualDuctZonePrioritySpread = Point(DomainName.dualDuctZonePrioritySpread, equipRef)
    val dualDuctCoolingDeadbandMultiplier = Point(DomainName.dualDuctCoolingDeadbandMultiplier, equipRef)
    val dualDuctTemperatureProportionalRange = Point(DomainName.dualDuctTemperatureProportionalRange, equipRef)
    val dualDuctHeatingDeadband = Point(DomainName.dualDuctHeatingDeadband, equipRef)
    val dualDuctZonePriorityMultiplier = Point(DomainName.dualDuctZonePriorityMultiplier, equipRef)
    val dualDuctHeatingDeadbandMultiplier = Point(DomainName.dualDuctHeatingDeadbandMultiplier, equipRef)

    val stage1CoolingAirflowTempUpperOffset = Point(DomainName.stage1CoolingAirflowTempUpperOffset, equipRef)
    val stage1CoolingAirflowTempLowerOffset = Point(DomainName.stage1CoolingAirflowTempLowerOffset, equipRef)
    val stage4CoolingAirflowTempLowerOffset = Point(DomainName.stage4CoolingAirflowTempLowerOffset, equipRef)
    val stage5CoolingAirflowTempUpperOffset = Point(DomainName.stage5CoolingAirflowTempUpperOffset, equipRef)
    val stage2HeatingAirflowTempLowerOffset = Point(DomainName.stage2HeatingAirflowTempLowerOffset, equipRef)
    val stage2CoolingAirflowTempLowerOffset = Point(DomainName.stage2CoolingAirflowTempLowerOffset, equipRef)
    val stage5CoolingAirflowTempLowerOffset = Point(DomainName.stage5CoolingAirflowTempLowerOffset, equipRef)
    val stage5HeatingAirflowTempLowerOffset = Point(DomainName.stage5HeatingAirflowTempLowerOffset, equipRef)
    val stage3HeatingAirflowTempUpperOffset = Point(DomainName.stage3HeatingAirflowTempUpperOffset, equipRef)
    val stage4HeatingAirflowTempLowerOffset = Point(DomainName.stage4HeatingAirflowTempLowerOffset, equipRef)
    val stage3CoolingAirflowTempUpperOffset = Point(DomainName.stage3CoolingAirflowTempUpperOffset, equipRef)
    val stage1HeatingAirflowTempLowerOffset = Point(DomainName.stage1HeatingAirflowTempLowerOffset, equipRef)
    val stage3HeatingAirflowTempLowerOffset = Point(DomainName.stage3HeatingAirflowTempLowerOffset, equipRef)
    val stage1HeatingAirflowTempUpperOffset = Point(DomainName.stage1HeatingAirflowTempUpperOffset, equipRef)
    val stage2HeatingAirflowTempUpperOffset = Point(DomainName.stage2HeatingAirflowTempUpperOffset, equipRef)
    val stage3CoolingAirflowTempLowerOffset = Point(DomainName.stage3CoolingAirflowTempLowerOffset, equipRef)
    val stage4HeatingAirflowTempUpperOffset = Point(DomainName.stage4HeatingAirflowTempUpperOffset, equipRef)
    val stage4CoolingAirflowTempUpperOffset = Point(DomainName.stage4CoolingAirflowTempUpperOffset, equipRef)
    val stage5HeatingAirflowTempUpperOffset = Point(DomainName.stage5HeatingAirflowTempUpperOffset, equipRef)
    val stage2CoolingAirflowTempUpperOffset = Point(DomainName.stage2CoolingAirflowTempUpperOffset, equipRef)

    //Standalone
    val standaloneEnthalpyDuctCompensationOffset = Point(DomainName.standaloneEnthalpyDuctCompensationOffset, equipRef)
    val standaloneEconomizingToMainCoolingLoopMap = Point(DomainName.standaloneEconomizingToMainCoolingLoopMap, equipRef)
    val standaloneEconomizingMinTemperature = Point(DomainName.standaloneEconomizingMinTemperature, equipRef)
    val standaloneEconomizingMaxTemperature = Point(DomainName.standaloneEconomizingMaxTemperature, equipRef)
    val standaloneEconomizingMinHumidity = Point(DomainName.standaloneEconomizingMinHumidity, equipRef)
    val standaloneEconomizingMaxHumidity = Point(DomainName.standaloneEconomizingMaxHumidity, equipRef)
    val standaloneEconomizingDryBulbThreshold = Point(DomainName.standaloneEconomizingDryBulbThreshold, equipRef)
    val standaloneOutsideDamperMixedAirTarget = Point(DomainName.standaloneOutsideDamperMixedAirTarget, equipRef)
    val standaloneOutsideDamperMixedAirMinimum = Point(DomainName.standaloneOutsideDamperMixedAirMinimum, equipRef)
    val standaloneDuctTemperatureOffset = Point(DomainName.standaloneDuctTemperatureOffset, equipRef)
    val standaloneCoolingAirflowTempLowerOffset = Point(DomainName.standaloneCoolingAirflowTempLowerOffset, equipRef)
    val standaloneCoolingAirflowTempUpperOffset = Point(DomainName.standaloneCoolingAirflowTempUpperOffset, equipRef)
    val standaloneHeatingAirflowTempUpperOffset = Point(DomainName.standaloneHeatingAirflowTempUpperOffset, equipRef)
    val standaloneHeatingAirflowTempLowerOffset = Point(DomainName.standaloneHeatingAirflowTempLowerOffset, equipRef)

    //OTN
    val otnIntegralKFactor = Point(DomainName.otnIntegralKFactor, equipRef)
    val otnTemperatureIntegralTime = Point(DomainName.otnTemperatureIntegralTime, equipRef)
    val otnZonePriorityMultiplier = Point(DomainName.otnZonePriorityMultiplier, equipRef)
    val otnCoolingDeadband = Point(DomainName.otnCoolingDeadband, equipRef)
    val otnHeatingDeadband = Point(DomainName.otnHeatingDeadband, equipRef)
    val otnTemperatureProportionalRange = Point(DomainName.otnTemperatureProportionalRange, equipRef)
    val otnProportionalKFactor = Point(DomainName.otnProportionalKFactor, equipRef)
    val otnZonePrioritySpread = Point(DomainName.otnZonePrioritySpread, equipRef)

    //DCWB
    val chilledWaterTemperatureIntegralTime = Point(DomainName.chilledWaterTemperatureIntegralTime, equipRef)
    val chilledWaterIntegralKFactor = Point(DomainName.chilledWaterIntegralKFactor, equipRef)
    val dcwbChilledWaterTemperatureProportionalRange = Point(DomainName.dcwbChilledWaterTemperatureProportionalRange, equipRef)
    val adaptiveComfortThresholdMargin = Point(DomainName.adaptiveComfortThresholdMargin, equipRef)
    val chilledWaterProportionalKFactor = Point(DomainName.chilledWaterProportionalKFactor, equipRef)

    val pipe2FancoilHeatingThreshold = Point(DomainName.pipe2FancoilHeatingThreshold, equipRef)
    val pipe2FancoilCoolingThreshold = Point(DomainName.pipe2FancoilCoolingThreshold, equipRef)

    //VRV
    val vrvHeatingDeadbandMultiplier = Point(DomainName.vrvHeatingDeadbandMultiplier, equipRef)
    val vrvHeatingDeadband = Point(DomainName.vrvHeatingDeadband, equipRef)
    val vrvCoolingDeadbandMultiplier = Point(DomainName.vrvCoolingDeadbandMultiplier, equipRef)
    val vrvCoolingDeadband = Point(DomainName.vrvCoolingDeadband, equipRef)

    //Schedulable
    val coolingUserLimitMin = Point(DomainName.coolingUserLimitMin, equipRef)
    val buildingLimitMax = Point(DomainName.buildingLimitMax, equipRef)
    val heatingUserLimitMax = Point(DomainName.heatingUserLimitMax, equipRef)
    val buildingLimitMin = Point(DomainName.buildingLimitMin, equipRef)
    val heatingUserLimitMin = Point(DomainName.heatingUserLimitMin, equipRef)
    val coolingUserLimitMax = Point(DomainName.coolingUserLimitMax, equipRef)
    val buildingToZoneDifferential = Point(DomainName.buildingToZoneDifferential, equipRef)
    val heatingDeadband = Point(DomainName.heatingDeadband, equipRef)
    val unoccupiedZoneSetback = Point(DomainName.unoccupiedZoneSetback, equipRef)
    val coolingDeadband = Point(DomainName.coolingDeadband, equipRef)

    private fun getDisplayNameFromVariation(dis: String): String {
        var displayName: String = if (BuildConfig.BUILD_TYPE.equals(
                    CARRIER_PROD,
                    ignoreCase = true
                )
            ) {
                dis.replace("(?i)-DAB-".toRegex(), "-VVT-").replace("(?i)DAB".toRegex(), "VVT")
            } else {
                dis
            }
        return displayName
    }
}