package a75f.io.domain.equips

import a75f.io.domain.api.DomainName
import a75f.io.domain.api.Point

class ConditioningStages (equipRef : String) {
    val coolingStage1 = Point(DomainName.coolingStage1 ,equipRef)
    val coolingStage2 = Point(DomainName.coolingStage2 ,equipRef)
    val coolingStage3 = Point(DomainName.coolingStage3 ,equipRef)
    val coolingStage4 = Point(DomainName.coolingStage4 ,equipRef)
    val coolingStage5 = Point(DomainName.coolingStage5 ,equipRef)

    val heatingStage1 = Point(DomainName.heatingStage1 ,equipRef)
    val heatingStage2 = Point(DomainName.heatingStage2 ,equipRef)
    val heatingStage3 = Point(DomainName.heatingStage3 ,equipRef)
    val heatingStage4 = Point(DomainName.heatingStage4 ,equipRef)
    val heatingStage5 = Point(DomainName.heatingStage5 ,equipRef)

    val fanStage1 = Point(DomainName.fanStage1 ,equipRef)
    val fanStage2 = Point(DomainName.fanStage2 ,equipRef)
    val fanStage3 = Point(DomainName.fanStage3 ,equipRef)
    val fanStage4 = Point(DomainName.fanStage4 ,equipRef)
    val fanStage5 = Point(DomainName.fanStage5 ,equipRef)

    val humidifierEnable = Point(DomainName.humidifierEnable ,equipRef)
    val dehumidifierEnable = Point(DomainName.dehumidifierEnable ,equipRef)
    val compressorStage1 = Point(DomainName.compressorStage1 ,equipRef)
    val compressorStage2 = Point(DomainName.compressorStage2 ,equipRef)
    val compressorStage3 = Point(DomainName.compressorStage3 ,equipRef)
    val compressorStage4 = Point(DomainName.compressorStage4 ,equipRef)
    val compressorStage5 = Point(DomainName.compressorStage5 ,equipRef)
    val changeOverCooling = Point(DomainName.changeOverCooling ,equipRef)
    val changeOverHeating = Point(DomainName.changeOverHeating ,equipRef)
    val fanEnable = Point(DomainName.fanEnable ,equipRef)
    val occupiedEnabled = Point(DomainName.occupiedEnable ,equipRef)
    val dcvDamper = Point(DomainName.dcvDamper ,equipRef)

    val loadCoolingStage1 = Point(DomainName.loadCoolingStage1, equipRef)
    val loadCoolingStage2 = Point(DomainName.loadCoolingStage2, equipRef)
    val loadCoolingStage3 = Point(DomainName.loadCoolingStage3, equipRef)
    val loadCoolingStage4 = Point(DomainName.loadCoolingStage4, equipRef)
    val loadCoolingStage5 = Point(DomainName.loadCoolingStage5, equipRef)
    val loadHeatingStage1 = Point(DomainName.loadHeatingStage1, equipRef)
    val loadHeatingStage2 = Point(DomainName.loadHeatingStage2, equipRef)
    val loadHeatingStage3 = Point(DomainName.loadHeatingStage3, equipRef)
    val loadHeatingStage4 = Point(DomainName.loadHeatingStage4, equipRef)
    val loadHeatingStage5 = Point(DomainName.loadHeatingStage5, equipRef)
    val loadFanStage1 = Point(DomainName.loadFanStage1, equipRef)
    val loadFanStage2 = Point(DomainName.loadFanStage2, equipRef)
    val loadFanStage3 = Point(DomainName.loadFanStage3, equipRef)
    val loadFanStage4 = Point(DomainName.loadFanStage4, equipRef)
    val loadFanStage5 = Point(DomainName.loadFanStage5, equipRef)
    val satCoolingStage1 = Point(DomainName.satCoolingStage1, equipRef)
    val satCoolingStage2 = Point(DomainName.satCoolingStage2, equipRef)
    val satCoolingStage3 = Point(DomainName.satCoolingStage3, equipRef)
    val satCoolingStage4 = Point(DomainName.satCoolingStage4, equipRef)
    val satCoolingStage5 = Point(DomainName.satCoolingStage5, equipRef)
    val satHeatingStage1 = Point(DomainName.satHeatingStage1, equipRef)
    val satHeatingStage2 = Point(DomainName.satHeatingStage2, equipRef)
    val satHeatingStage3 = Point(DomainName.satHeatingStage3, equipRef)
    val satHeatingStage4 = Point(DomainName.satHeatingStage4, equipRef)
    val satHeatingStage5 = Point(DomainName.satHeatingStage5, equipRef)
    val fanPressureStage1 = Point(DomainName.fanPressureStage1, equipRef)
    val fanPressureStage2 = Point(DomainName.fanPressureStage2, equipRef)
    val fanPressureStage3 = Point(DomainName.fanPressureStage3, equipRef)
    val fanPressureStage4 = Point(DomainName.fanPressureStage4, equipRef)
    val fanPressureStage5 = Point(DomainName.fanPressureStage5, equipRef)
    val ahuFreshAirFanRunCommand = Point(DomainName.ahuFreshAirFanRunCommand, equipRef)
    val exhaustFanStage1 = Point(DomainName.exhaustFanStage1, equipRef)
    val exhaustFanStage2 = Point(DomainName.exhaustFanStage2, equipRef)


}
