package a75f.io.domain.equips

import a75f.io.domain.api.DomainName
import a75f.io.domain.api.Point

open class DabEquip (equipRef : String) : DomainEquip(equipRef){
    val heartBeat = Point(DomainName.heartBeat, equipRef)

    val currentTemp = Point(DomainName.currentTemp, equipRef)
    val zoneHumidity = Point(DomainName.zoneHumidity, equipRef)

    val desiredTemp = Point(DomainName.desiredTemp, equipRef)
    val desiredTempCooling = Point(DomainName.desiredTempCooling, equipRef)
    val desiredTempHeating = Point(DomainName.desiredTempHeating, equipRef)

    val coolingLoopOutput = Point(DomainName.coolingLoopOutput, equipRef)
    val heatingLoopOutput = Point(DomainName.heatingLoopOutput, equipRef)

    val temperatureOffset = Point(DomainName.temperatureOffset, equipRef)
    val scheduleType = Point(DomainName.scheduleType, equipRef)
    val autoForceOccupied = Point(DomainName.autoForceOccupied, equipRef)
    val autoAway = Point(DomainName.autoAway, equipRef)
    val enableCo2Control = Point(DomainName.enableCo2Control, equipRef)
    val enableCFMControl = Point(DomainName.enableCFMControl, equipRef)
    val enableIAQControl = Point(DomainName.enableIAQControl, equipRef)
    val damper1Cmd  = Point(DomainName.damper1Cmd, equipRef)
    val damper2Cmd  = Point(DomainName.damper2Cmd, equipRef)
    val damper1Shape = Point(DomainName.damper1Shape, equipRef)
    val damper1Type = Point(DomainName.damper1Type, equipRef)
    val damper1Size = Point(DomainName.damper1Size, equipRef)
    val damper2Shape = Point(DomainName.damper2Shape, equipRef)
    val damper2Type = Point(DomainName.damper2Type, equipRef)
    val damper2Size = Point(DomainName.damper2Size, equipRef)
    val reheatType = Point(DomainName.reheatType, equipRef)
    val zonePriority = Point(DomainName.zonePriority, equipRef)

    val equipStatus = Point(DomainName.equipStatus, equipRef)
    val equipStatusMessage = Point(DomainName.equipStatusMessage, equipRef)
    val equipScheduleStatus = Point(DomainName.equipScheduleStatus, equipRef)

    val zoneCO2 = Point(DomainName.zoneCO2, equipRef)
    val enteringAirTemp = Point(DomainName.enteringAirTemp, equipRef)
    val pressureSensor = Point(DomainName.pressureSensor, equipRef)
    val zoneVoc = Point(DomainName.zoneVoc, equipRef)
    val minCFMIAQ = Point(DomainName.minCFMIAQ, equipRef)
    val minReheatDamperPos = Point(DomainName.minReheatDamperPos, equipRef)
    val maxHeatingDamperPos = Point(DomainName.maxHeatingDamperPos, equipRef)
    val minHeatingDamperPos = Point(DomainName.minHeatingDamperPos, equipRef)
    val maxCoolingDamperPos = Point(DomainName.maxCoolingDamperPos, equipRef)
    val minCoolingDamperPos = Point(DomainName.minCoolingDamperPos, equipRef)
    val occupancyMode = Point(DomainName.occupancyMode, equipRef)
    val occupancyDetection = Point(DomainName.occupancyDetection, equipRef)
    val dischargeAirTemp1 = Point(DomainName.dischargeAirTemp1, equipRef)
    val otaStatus = Point(DomainName.otaStatus, equipRef)
    val kFactor = Point(DomainName.kFactor, equipRef)
    val reheatCmd = Point(DomainName.reheatCmd, equipRef)

    val damperFeedback = Point(DomainName.damperFeedback, equipRef)
    val normalizedDamper1Cmd = Point(DomainName.normalizedDamper1Cmd, equipRef)
    val normalizedDamper2Cmd = Point(DomainName.normalizedDamper2Cmd, equipRef)
    val airVelocity = Point(DomainName.airVelocity, equipRef)
    val airFlowSensor = Point(DomainName.airFlowSensor, equipRef)
    val dischargeAirTemp2 = Point(DomainName.dischargeAirTemp2, equipRef)
    val zoneSound  = Point(DomainName.zoneSound, equipRef)
    val zoneIlluminance = Point(DomainName.zoneIlluminance, equipRef)
    val zonePm25    = Point(DomainName.zonePm25, equipRef)
    val zoneCo = Point(DomainName.zoneCo, equipRef)
    val zoneNo = Point(DomainName.zoneNo, equipRef)
    val zoneUvi = Point(DomainName.zoneUvi, equipRef)
    val zoneCo2e = Point(DomainName.zoneCo2Equivalent, equipRef)
    val zoneOccupancy   = Point(DomainName.zoneOccupancy, equipRef)

    val zoneDynamicPriority = Point(DomainName.zoneDynamicPriority, equipRef)
    val demandResponseSetback = Point(DomainName.demandResponseSetback, equipRef)
    val dabTemperatureProportionalRange = Point(DomainName.dabTemperatureProportionalRange, equipRef)
    val dabIntegralKFactor = Point(DomainName.dabIntegralKFactor, equipRef)
    val dabProportionalKFactor = Point(DomainName.dabProportionalKFactor, equipRef)
    val dabTemperatureIntegralTime = Point(DomainName.dabTemperatureIntegralTime, equipRef)
    val dabZoneCO2Target = Point(DomainName.dabZoneCO2Target, equipRef)
    val dabZoneCo2Threshold = Point(DomainName.dabZoneCO2Threshold, equipRef)
    val dabZoneVocTarget = Point(DomainName.dabZoneVOCTarget, equipRef)
    val dabZoneVocThreshold = Point(DomainName.dabZoneVOCThreshold, equipRef)
    val dabReheatTemperatureProportionalRange = Point(DomainName.dabReheatTemperatureProportionalRange, equipRef)
    val dabReheatTemperatureIntegralTime = Point(DomainName.dabReheatTemperatureIntegralTime, equipRef)
    val dabReheatProportionalKFactor = Point(DomainName.dabReheatProportionalKFactor, equipRef)
    val dabReheatIntegralKFactor = Point(DomainName.dabReheatIntegralKFactor, equipRef)
}