package a75f.io.domain.equips

import a75f.io.domain.api.DomainName
import a75f.io.domain.api.Point

open class DabModulatingRtuSystemEquip(equipRef : String) : DabSystemEquip(equipRef) {
    //Base points
    val analog1OutputEnable = Point(DomainName.analog1OutputEnable ,equipRef)
    val analog2OutputEnable = Point(DomainName.analog2OutputEnable ,equipRef)
    val analog3OutputEnable = Point(DomainName.analog3OutputEnable ,equipRef)
    val analog4OutputEnable = Point(DomainName.analog4OutputEnable ,equipRef)
    val relay3OutputEnable = Point(DomainName.relay3OutputEnable ,equipRef)
    val relay7OutputEnable = Point(DomainName.relay7OutputEnable ,equipRef)
    val occupancySignal = Point(DomainName.occupancySignal ,equipRef)
    val dcwbEnable = Point(DomainName.dcwbEnable ,equipRef)
    val adaptiveComfortThresholdMargin = Point(DomainName.adaptiveComfortThresholdMargin ,equipRef)

    val analog1OutputAssociation = Point(DomainName.analog1OutputAssociation ,equipRef)
    val analog2OutputAssociation = Point(DomainName.analog2OutputAssociation ,equipRef)
    val analog3OutputAssociation = Point(DomainName.analog3OutputAssociation ,equipRef)
    val relay3OutputAssociation = Point(DomainName.relay3OutputAssociation ,equipRef)
    //dependant points
    val coolingSignal = Point(DomainName.coolingSignal ,equipRef)
    val fanSignal = Point(DomainName.fanSignal ,equipRef)
    val heatingSignal = Point(DomainName.heatingSignal ,equipRef)
    val outsideAirDamper = Point(DomainName.outsideAirDamper ,equipRef)
    val fanEnable = Point(DomainName.fanEnable ,equipRef)
    val adaptiveDeltaEnable = Point(DomainName.adaptiveDeltaEnable ,equipRef)
    val systemDCWBValveLoopOutput = Point(DomainName.systemDCWBValveLoopOutput ,equipRef)
    val chilledWaterExitTemperatureMargin = Point(DomainName.chilledWaterExitTemperatureMargin ,equipRef)
    val chilledWaterExitTemperatureTarget = Point(DomainName.chilledWaterExitTemperatureTarget ,equipRef)
    val chilledWaterValveSignal = Point(DomainName.chilledWaterValveSignal ,equipRef)
    val maximizedExitWaterTempEnable = Point(DomainName.maximizedExitWaterTempEnable ,equipRef)
    val chilledWaterTargetDelta = Point(DomainName.chilledWaterTargetDelta ,equipRef)
    val chilledWaterMaxFlowRate = Point(DomainName.chilledWaterMaxFlowRate ,equipRef)
    val analog1ValveClosedPosition = Point(DomainName.analog1ValveClosedPosition ,equipRef)
    val analog1ValveFullPosition = Point(DomainName.analog1ValveFullPosition ,equipRef)
    val dcvDamperModulating = Point(DomainName.dcvDamperModulating ,equipRef)
    val compressorSpeed = Point(DomainName.compressorSpeed ,equipRef)

    //associated points
    val humidifier = Point(DomainName.humidifierEnable ,equipRef)
    val dehumidifier = Point(DomainName.dehumidifierEnable ,equipRef)
    val analog4OutputAssociation = Point(DomainName.analog4OutputAssociation ,equipRef);

    //dependant points
    val analog1MinFan = Point(DomainName.analog1MinFan, equipRef)
    val analog1MaxFan = Point(DomainName.analog1MaxFan, equipRef)
    val analog1MinCompressorSpeed = Point(DomainName.analog1MinCompressorSpeed, equipRef)
    val analog1MaxCompressorSpeed = Point(DomainName.analog1MaxCompressorSpeed, equipRef)
    val analog1MinDCVDamper = Point(DomainName.analog1MinDCVDamper, equipRef)
    val analog1MaxDCVDamper = Point(DomainName.analog1MaxDCVDamper, equipRef)
    val analog1MinOutsideDamper = Point(DomainName.analog1MinOutsideDamper, equipRef)
    val analog1MaxOutsideDamper = Point(DomainName.analog1MaxOutsideDamper, equipRef)
    val analog1MinCooling = Point(DomainName.analog1MinCooling, equipRef)
    val analog1MaxCooling = Point(DomainName.analog1MaxCooling, equipRef)
    val analog1MinHeating = Point(DomainName.analog1MinHeating, equipRef)
    val analog1MaxHeating = Point(DomainName.analog1MaxHeating, equipRef)
    val analog2MinFan = Point(DomainName.analog2MinFan, equipRef)
    val analog2MaxFan = Point(DomainName.analog2MaxFan, equipRef)
    val analog2MinCompressorSpeed = Point(DomainName.analog2MinCompressorSpeed, equipRef)
    val analog2MaxCompressorSpeed = Point(DomainName.analog2MaxCompressorSpeed, equipRef)
    val analog2MinDCVDamper = Point(DomainName.analog2MinDCVDamper, equipRef)
    val analog2MaxDCVDamper = Point(DomainName.analog2MaxDCVDamper, equipRef)
    val analog2MinOutsideDamper = Point(DomainName.analog2MinOutsideDamper, equipRef)
    val analog2MaxOutsideDamper = Point(DomainName.analog2MaxOutsideDamper, equipRef)
    val analog2MinCooling = Point(DomainName.analog2MinCooling, equipRef)
    val analog2MaxCooling = Point(DomainName.analog2MaxCooling, equipRef)
    val analog2MinHeating = Point(DomainName.analog2MinHeating, equipRef)
    val analog2MaxHeating = Point(DomainName.analog2MaxHeating, equipRef)
    val analog3MinFan = Point(DomainName.analog3MinFan, equipRef)
    val analog3MaxFan = Point(DomainName.analog3MaxFan, equipRef)
    val analog3MinCompressorSpeed = Point(DomainName.analog3MinCompressorSpeed, equipRef)
    val analog3MaxCompressorSpeed = Point(DomainName.analog3MaxCompressorSpeed, equipRef)
    val analog3MinDCVDamper = Point(DomainName.analog3MinDCVDamper, equipRef)
    val analog3MaxDCVDamper = Point(DomainName.analog3MaxDCVDamper, equipRef)
    val analog3MinOutsideDamper = Point(DomainName.analog3MinOutsideDamper, equipRef)
    val analog3MaxOutsideDamper = Point(DomainName.analog3MaxOutsideDamper, equipRef)
    val analog3MinCooling = Point(DomainName.analog3MinCooling, equipRef)
    val analog3MaxCooling = Point(DomainName.analog3MaxCooling, equipRef)
    val analog3MinHeating = Point(DomainName.analog3MinHeating, equipRef)
    val analog3MaxHeating = Point(DomainName.analog3MaxHeating, equipRef)
    val analog4MinFan = Point(DomainName.analog4MinFan, equipRef)
    val analog4MaxFan = Point(DomainName.analog4MaxFan, equipRef)
    val analog4MinCompressorSpeed = Point(DomainName.analog4MinCompressorSpeed, equipRef)
    val analog4MaxCompressorSpeed = Point(DomainName.analog4MaxCompressorSpeed, equipRef)
    val analog4MinDCVDamper = Point(DomainName.analog4MinDCVDamper, equipRef)
    val analog4MaxDCVDamper = Point(DomainName.analog4MaxDCVDamper, equipRef)
    val analog4MinOutsideDamper = Point(DomainName.analog4MinOutsideDamper, equipRef)
    val analog4MaxOutsideDamper = Point(DomainName.analog4MaxOutsideDamper, equipRef)
    val analog4MinCooling = Point(DomainName.analog4MinCooling, equipRef)
    val analog4MaxCooling = Point(DomainName.analog4MaxCooling, equipRef)
    val analog4MinHeating = Point(DomainName.analog4MinHeating, equipRef)
    val analog4MaxHeating = Point(DomainName.analog4MaxHeating, equipRef)

    //Association point
    val relay7OutputAssociation = Point(DomainName.relay7OutputAssociation , equipRef)


    val thermistor1InputEnable = Point(DomainName.thermistor1InputEnable, equipRef)
    val thermistor2InputEnable = Point(DomainName.thermistor2InputEnable, equipRef)
    val thermistor1InputAssociation = Point(DomainName.thermistor1InputAssociation, equipRef)
    val thermistor2InputAssociation = Point(DomainName.thermistor2InputAssociation, equipRef)
    val analog1InputEnable = Point(DomainName.analog1InputEnable, equipRef)
    val analog2InputEnable = Point(DomainName.analog2InputEnable, equipRef)
    val analog1InputAssociation = Point(DomainName.analog1InputAssociation, equipRef)
    val analog2InputAssociation = Point(DomainName.analog2InputAssociation, equipRef)

    val conditioningStages = ConditioningStages(equipRef)

    val analog1MinCHWValve = Point(DomainName.analog1MinCHWValve, equipRef)
    val analog1MaxCHWValve = Point(DomainName.analog1MaxCHWValve, equipRef)
    val analog2MinCHWValve = Point(DomainName.analog2MinCHWValve, equipRef)
    val analog2MaxCHWValve = Point(DomainName.analog2MaxCHWValve, equipRef)
    val analog3MinCHWValve = Point(DomainName.analog3MinCHWValve, equipRef)
    val analog3MaxCHWValve = Point(DomainName.analog3MaxCHWValve, equipRef)
    val analog4MinCHWValve = Point(DomainName.analog4MinCHWValve, equipRef)
    val analog4MaxCHWValve = Point(DomainName.analog4MaxCHWValve, equipRef)
}