package a75f.io.domain.equips

import a75f.io.api.haystack.CCUHsApi
import a75f.io.api.haystack.Tags
import a75f.io.domain.api.DomainName
import a75f.io.domain.api.Point
import a75f.io.logger.CcuLog

open class HyperStatSplitEquip (equipRef : String) : DomainEquip(equipRef) {

    var nodeAddress = -1
    var floorRef: String? = null
    var roomRef: String? = null

    init {
        try {
            val equipDetails = CCUHsApi.getInstance().readMapById(equipRef)
            nodeAddress = equipDetails[Tags.GROUP].toString().toInt()
            floorRef = equipDetails[Tags.FLOORREF] as String
            roomRef = equipDetails[Tags.ROOMREF] as String
        } catch (e: Exception) {
            CcuLog.e("CCU_HST", "Error in reading equip details")
        }
    }



    val currentTemp = Point(DomainName.currentTemp, equipRef)
    val zoneHumidity = Point(DomainName.zoneHumidity, equipRef)
    val zoneCO2 = Point(DomainName.zoneCo2, equipRef)
    val zonePm25 = Point(DomainName.zonePm25, equipRef)
    val zoneIlluminance = Point(DomainName.zoneIlluminance, equipRef)
    val zoneOccupancy = Point(DomainName.zoneOccupancy, equipRef)
    val zoneSound = Point(DomainName.zoneSound, equipRef)

    val temperatureOffset = Point(DomainName.temperatureOffset, equipRef)
    val autoAway = Point(DomainName.autoAway, equipRef)
    val autoForceOccupied = Point(DomainName.autoForceOccupied, equipRef)
    val prePurgeEnable = Point(DomainName.prePurgeEnable, equipRef)
    val prePurgeStatus = Point(DomainName.prePurgeStatus, equipRef)

    val sensorBusAddress0Enable = Point(DomainName.sensorBusAddress0Enable, equipRef)
    val sensorBusPressureEnable = Point(DomainName.sensorBusPressureEnable, equipRef)
    val sensorBusAddress1Enable = Point(DomainName.sensorBusAddress1Enable, equipRef)
    val sensorBusAddress2Enable = Point(DomainName.sensorBusAddress2Enable, equipRef)
    val sensorBusAddress3Enable = Point(DomainName.sensorBusAddress3Enable, equipRef)

    val temperatureSensorBusAdd0 = Point(DomainName.temperatureSensorBusAdd0, equipRef)
    val temperatureSensorBusAdd1 = Point(DomainName.temperatureSensorBusAdd1, equipRef)
    val temperatureSensorBusAdd2 = Point(DomainName.temperatureSensorBusAdd2, equipRef)
    val humiditySensorBusAdd0 = Point(DomainName.humiditySensorBusAdd0, equipRef)
    val humiditySensorBusAdd1 = Point(DomainName.humiditySensorBusAdd1, equipRef)
    val humiditySensorBusAdd2 = Point(DomainName.humiditySensorBusAdd2, equipRef)
    val pressureSensorBusAdd0 = Point(DomainName.pressureSensorBusAdd0, equipRef)

    val relay1OutputEnable = Point(DomainName.relay1OutputEnable, equipRef)
    val relay2OutputEnable = Point(DomainName.relay2OutputEnable, equipRef)
    val relay3OutputEnable = Point(DomainName.relay3OutputEnable, equipRef)
    val relay4OutputEnable = Point(DomainName.relay4OutputEnable, equipRef)
    val relay5OutputEnable = Point(DomainName.relay5OutputEnable, equipRef)
    val relay6OutputEnable = Point(DomainName.relay6OutputEnable, equipRef)
    val relay7OutputEnable = Point(DomainName.relay7OutputEnable, equipRef)
    val relay8OutputEnable = Point(DomainName.relay8OutputEnable, equipRef)

    val relay1OutputAssociation = Point(DomainName.relay1OutputAssociation, equipRef)
    val relay2OutputAssociation = Point(DomainName.relay2OutputAssociation, equipRef)
    val relay3OutputAssociation = Point(DomainName.relay3OutputAssociation, equipRef)
    val relay4OutputAssociation = Point(DomainName.relay4OutputAssociation, equipRef)
    val relay5OutputAssociation = Point(DomainName.relay5OutputAssociation, equipRef)
    val relay6OutputAssociation = Point(DomainName.relay6OutputAssociation, equipRef)
    val relay7OutputAssociation = Point(DomainName.relay7OutputAssociation, equipRef)
    val relay8OutputAssociation = Point(DomainName.relay8OutputAssociation, equipRef)

    val analog1OutputEnable = Point(DomainName.analog1OutputEnable, equipRef)
    val analog2OutputEnable = Point(DomainName.analog2OutputEnable, equipRef)
    val analog3OutputEnable = Point(DomainName.analog3OutputEnable, equipRef)
    val analog4OutputEnable = Point(DomainName.analog4OutputEnable, equipRef)

    val analog1OutputAssociation = Point(DomainName.analog1OutputAssociation, equipRef)
    val analog2OutputAssociation = Point(DomainName.analog2OutputAssociation, equipRef)
    val analog3OutputAssociation = Point(DomainName.analog3OutputAssociation, equipRef)
    val analog4OutputAssociation = Point(DomainName.analog4OutputAssociation, equipRef)

    val universalIn1Enable = Point(DomainName.universalIn1Enable, equipRef)
    val universalIn2Enable = Point(DomainName.universalIn2Enable, equipRef)
    val universalIn3Enable = Point(DomainName.universalIn3Enable, equipRef)
    val universalIn4Enable = Point(DomainName.universalIn4Enable, equipRef)
    val universalIn5Enable = Point(DomainName.universalIn5Enable, equipRef)
    val universalIn6Enable = Point(DomainName.universalIn6Enable, equipRef)
    val universalIn7Enable = Point(DomainName.universalIn7Enable, equipRef)
    val universalIn8Enable = Point(DomainName.universalIn8Enable, equipRef)

    val universalIn1Association = Point(DomainName.universalIn1Association, equipRef)
    val universalIn2Association = Point(DomainName.universalIn2Association, equipRef)
    val universalIn3Association = Point(DomainName.universalIn3Association, equipRef)
    val universalIn4Association = Point(DomainName.universalIn4Association, equipRef)
    val universalIn5Association = Point(DomainName.universalIn5Association, equipRef)
    val universalIn6Association = Point(DomainName.universalIn6Association, equipRef)
    val universalIn7Association = Point(DomainName.universalIn7Association, equipRef)
    val universalIn8Association = Point(DomainName.universalIn8Association, equipRef)

    val analog1AtMinOAODamper = Point(DomainName.analog1MinOAODamper, equipRef)
    val analog1AtMaxOAODamper = Point(DomainName.analog1MaxOAODamper, equipRef)
    val analog2AtMinOAODamper = Point(DomainName.analog2MinOAODamper, equipRef)
    val analog2AtMaxOAODamper = Point(DomainName.analog2MaxOAODamper, equipRef)
    val analog3AtMinOAODamper = Point(DomainName.analog3MinOAODamper, equipRef)
    val analog3AtMaxOAODamper = Point(DomainName.analog3MaxOAODamper, equipRef)
    val analog4AtMinOAODamper = Point(DomainName.analog4MinOAODamper, equipRef)
    val analog4AtMaxOAODamper = Point(DomainName.analog4MaxOAODamper, equipRef)

    val analog1AtMinReturnDamper = Point(DomainName.analog1MinReturnDamper, equipRef)
    val analog1AtMaxReturnDamper = Point(DomainName.analog1MaxReturnDamper, equipRef)
    val analog2AtMinReturnDamper = Point(DomainName.analog2MinReturnDamper, equipRef)
    val analog2AtMaxReturnDamper = Point(DomainName.analog2MaxReturnDamper, equipRef)
    val analog3AtMinReturnDamper = Point(DomainName.analog3MinReturnDamper, equipRef)
    val analog3AtMaxReturnDamper = Point(DomainName.analog3MaxReturnDamper, equipRef)
    val analog4AtMinReturnDamper = Point(DomainName.analog4MinReturnDamper, equipRef)
    val analog4AtMaxReturnDamper = Point(DomainName.analog4MaxReturnDamper, equipRef)

    val analog1AtMinDcvModulation = Point(DomainName.analog1MinDCVDamper, equipRef)
    val analog1AtMaxDcvModulation = Point(DomainName.analog1MaxDCVDamper, equipRef)
    val analog2AtMinDcvModulation = Point(DomainName.analog2MinDCVDamper, equipRef)
    val analog2AtMaxDcvModulation = Point(DomainName.analog2MaxDCVDamper, equipRef)
    val analog3AtMinDcvModulation = Point(DomainName.analog3MinDCVDamper, equipRef)
    val analog3AtMaxDcvModulation = Point(DomainName.analog3MaxDCVDamper, equipRef)
    val analog4AtMinDcvModulation = Point(DomainName.analog4MinDCVDamper, equipRef)
    val analog4AtMaxDcvModulation = Point(DomainName.analog4MaxDCVDamper, equipRef)

    val analog1FanLow = Point(DomainName.analog1FanLow, equipRef)
    val analog1FanMedium = Point(DomainName.analog1FanMedium, equipRef)
    val analog1FanHigh = Point(DomainName.analog1FanHigh, equipRef)
    val analog2FanLow = Point(DomainName.analog2FanLow, equipRef)
    val analog2FanMedium = Point(DomainName.analog2FanMedium, equipRef)
    val analog2FanHigh = Point(DomainName.analog2FanHigh, equipRef)
    val analog3FanLow = Point(DomainName.analog3FanLow, equipRef)
    val analog3FanMedium = Point(DomainName.analog3FanMedium, equipRef)
    val analog3FanHigh = Point(DomainName.analog3FanHigh, equipRef)
    val analog4FanLow = Point(DomainName.analog4FanLow, equipRef)
    val analog4FanMedium = Point(DomainName.analog4FanMedium, equipRef)
    val analog4FanHigh = Point(DomainName.analog4FanHigh, equipRef)

    val fanOutEconomizer = Point(DomainName.fanOutEconomizer, equipRef)
    val fanOutRecirculate = Point(DomainName.fanOutRecirculate, equipRef)

    val outsideDamperMinOpenDuringRecirculation = Point(DomainName.outsideDamperMinOpenDuringRecirculation, equipRef)
    val outsideDamperMinOpenDuringConditioning = Point(DomainName.outsideDamperMinOpenDuringConditioning, equipRef)
    val outsideDamperMinOpenDuringFanLow = Point(DomainName.outsideDamperMinOpenDuringFanLow, equipRef)
    val outsideDamperMinOpenDuringFanMedium = Point(DomainName.outsideDamperMinOpenDuringFanMedium, equipRef)
    val outsideDamperMinOpenDuringFanHigh = Point(DomainName.outsideDamperMinOpenDuringFanHigh, equipRef)

    val co2Threshold = Point(DomainName.co2Threshold, equipRef)
    val pm25Threshold = Point(DomainName.pm25Threshold, equipRef)
    val co2Target = Point(DomainName.co2Target, equipRef)
    val pm25Target = Point(DomainName.pm25Target, equipRef)

    val enableHumidityDisplay = Point(DomainName.enableHumidityDisplay, equipRef)
    val enableCO2Display = Point(DomainName.enableCO2Display, equipRef)
    val enablePm25Display = Point(DomainName.enablePm25Display, equipRef)

    val disableTouch = Point(DomainName.disableTouch, equipRef)
    val enableBrightness = Point(DomainName.enableBrightness, equipRef)
    val enableBacklight = Point(DomainName.enableBacklight, equipRef)

    val occupancyMode = Point(DomainName.occupancyMode, equipRef)
    val fanOpMode = Point(DomainName.fanOpMode, equipRef)
    val operatingMode = Point(DomainName.operatingMode, equipRef)
    val conditioningMode = Point(DomainName.conditioningMode, equipRef)
    val occupancyDetection = Point(DomainName.occupancyDetection, equipRef)
    val desiredTemp = Point(DomainName.desiredTemp, equipRef)
    val desiredTempCooling = Point(DomainName.desiredTempCooling, equipRef)
    val desiredTempHeating = Point(DomainName.desiredTempHeating, equipRef)

    val co2DamperOpeningRate = Point(DomainName.co2DamperOpeningRate, equipRef)
    val exhaustFanStage1Threshold = Point(DomainName.exhaustFanStage1Threshold, equipRef)
    val exhaustFanStage2Threshold = Point(DomainName.exhaustFanStage2Threshold, equipRef)
    val exhaustFanHysteresis = Point(DomainName.exhaustFanHysteresis, equipRef)
    val insideEnthalpy = Point(DomainName.insideEnthalpy, equipRef)
    val outsideEnthalpy = Point(DomainName.outsideEnthalpy, equipRef)
    val economizingAvailable = Point(DomainName.economizingAvailable, equipRef)
    val matThrottle = Point(DomainName.matThrottle, equipRef)

    val dischargeAirTemperature = Point(DomainName.dischargeAirTemperature, equipRef)
    val mixedAirTemperature = Point(DomainName.mixedAirTemperature, equipRef)
    val outsideTemperature = Point(DomainName.outsideTemperature, equipRef)
    val supplyAirHumidity = Point(DomainName.supplyAirHumidity, equipRef)
    val mixedAirHumidity = Point(DomainName.mixedAirHumidity, equipRef)
    val outsideHumidity = Point(DomainName.outsideHumidity, equipRef)
    val ductStaticPressureSensor = Point(DomainName.ductStaticPressureSensor, equipRef)

    val fanEnable = Point(DomainName.fanEnable, equipRef)
    val fanLowSpeed = Point(DomainName.fanLowSpeed, equipRef)
    val fanLowSpeedVentilation = Point(DomainName.fanLowSpeedVentilation, equipRef)
    val fanMediumSpeed = Point(DomainName.fanMediumSpeed, equipRef)
    val fanHighSpeed = Point(DomainName.fanHighSpeed, equipRef)
    val occupiedEnable = Point(DomainName.occupiedEnable, equipRef)

    val humidifierEnable = Point(DomainName.humidifierEnable, equipRef)
    val dehumidifierEnable = Point(DomainName.dehumidifierEnable, equipRef)

    val dcvDamper = Point(DomainName.dcvDamper, equipRef)
    val oaoDamper = Point(DomainName.oaoDamper, equipRef)
    val returnDamperPosition = Point(DomainName.returnDamperPosition, equipRef)

    val currentTx10 = Point(DomainName.currentTx10, equipRef)
    val currentTx20 = Point(DomainName.currentTx20, equipRef)
    val currentTx50 = Point(DomainName.currentTx50, equipRef)
    val currentTx100 = Point(DomainName.currentTx100, equipRef)
    val currentTx150 = Point(DomainName.currentTx150, equipRef)
    val filterStatusNO = Point(DomainName.filterStatusNO, equipRef)
    val filterStatusNC = Point(DomainName.filterStatusNC, equipRef)
    val condensateStatusNO = Point(DomainName.condensateStatusNO, equipRef)
    val condensateStatusNC = Point(DomainName.condensateStatusNC, equipRef)
    val ductStaticPressureSensor1_1 = Point(DomainName.ductStaticPressureSensor1_1, equipRef)
    val ductStaticPressureSensor1_2 = Point(DomainName.ductStaticPressureSensor1_2, equipRef)
    val ductStaticPressureSensor1_10 = Point(DomainName.ductStaticPressureSensor1_10, equipRef)

    val doorWindowSensingEnable = Point(DomainName.doorWindowSensingEnable, equipRef)
    val doorWindowSensorInput = Point(DomainName.doorWindowSensorInput, equipRef)
    val doorWindowSensorNC = Point(DomainName.doorWindowSensorNC, equipRef)
    val doorWindowSensor = Point(DomainName.doorWindowSensor, equipRef)
    val doorWindowSensorNCTitle24 = Point(DomainName.doorWindowSensorNCTitle24, equipRef)
    val doorWindowSensorTitle24 = Point(DomainName.doorWindowSensorTitle24, equipRef)
    val doorWindowSensorNOTitle24 = Point(DomainName.doorWindowSensorNOTitle24, equipRef)
    val doorWindowSensorNO = Point(DomainName.doorWindowSensorNO, equipRef)

    val keyCardSensingEnable = Point(DomainName.keyCardSensingEnable, equipRef)
    val keyCardSensorInput = Point(DomainName.keyCardSensorInput, equipRef)
    val keyCardSensorNO = Point(DomainName.keyCardSensorNO, equipRef)
    val keyCardSensorNC = Point(DomainName.keyCardSensorNC, equipRef)

    val enableOutsideAirOptimization = Point(DomainName.enableOutsideAirOptimization, equipRef)

    val coolingLoopOutput = Point(DomainName.coolingLoopOutput, equipRef)
    val heatingLoopOutput = Point(DomainName.heatingLoopOutput, equipRef)
    val economizingLoopOutput = Point(DomainName.economizingLoopOutput, equipRef)
    val dcvLoopOutput = Point(DomainName.dcvLoopOutput, equipRef)
    val fanLoopOutput = Point(DomainName.fanLoopOutput, equipRef)
    val outsideAirCalculatedMinDamper = Point(DomainName.outsideAirCalculatedMinDamper, equipRef)
    val outsideAirLoopOutput = Point(DomainName.outsideAirLoopOutput, equipRef)
    val outsideAirFinalLoopOutput = Point(DomainName.outsideAirFinalLoopOutput, equipRef)
    val co2WeightedAverage = Point(DomainName.co2WeightedAverage, equipRef)
    val dcvAvailable = Point(DomainName.dcvAvailable, equipRef)
    val weatherOutsideTemp = Point(DomainName.weatherOutsideTemp, equipRef)
    val weatherOutsideHumidity = Point(DomainName.weatherOutsideHumidity, equipRef)

    val targetHumidifier = Point(DomainName.targetHumidifier, equipRef)
    val targetDehumidifier = Point(DomainName.targetDehumidifier, equipRef)

    val equipStatus = Point(DomainName.equipStatus, equipRef)
    val equipStatusMessage = Point(DomainName.equipStatusMessage, equipRef)
    val equipScheduleStatus = Point(DomainName.equipScheduleStatus, equipRef)
    val heartBeat = Point(DomainName.heartBeat, equipRef)
    val scheduleType = Point(DomainName.scheduleType, equipRef)

    val standaloneTemperatureProportionalRange = Point(DomainName.standaloneTemperatureProportionalRange, equipRef)
    val standaloneTemperatureIntegralTime = Point(DomainName.standaloneTemperatureIntegralTime, equipRef)
    val constantTempAlertTime = Point(DomainName.constantTempAlertTime, equipRef)
    val abnormalCurTempRiseTrigger = Point(DomainName.abnormalCurTempRiseTrigger, equipRef)
    val standaloneHumidityHysteresis = Point(DomainName.standaloneHumidityHysteresis, equipRef)
    val standaloneRelayActivationHysteresis = Point(DomainName.standaloneRelayActivationHysteresis, equipRef)
    val standaloneAnalogFanSpeedMultiplier = Point(DomainName.standaloneAnalogFanSpeedMultiplier, equipRef)
    val standaloneCoolingDeadbandMultiplier = Point(DomainName.standaloneCoolingDeadbandMultiplier, equipRef)
    val standaloneHeatingDeadbandMultiplier = Point(DomainName.standaloneHeatingDeadbandMultiplier, equipRef)
    val standaloneProportionalKFactor = Point(DomainName.standaloneProportionalKFactor, equipRef)
    val standaloneIntegralKFactor = Point(DomainName.standaloneIntegralKFactor, equipRef)
    val forcedOccupiedTime = Point(DomainName.forcedOccupiedTime, equipRef)
    val autoAwayTime = Point(DomainName.autoAwayTime, equipRef)
    val autoAwaySetback = Point(DomainName.autoAwaySetback, equipRef)
    val standaloneCoolingPreconditioningRate = Point(DomainName.standaloneCoolingPreconditioningRate, equipRef)
    val standaloneHeatingPreconditioningRate = Point(DomainName.standaloneHeatingPreconditioningRate, equipRef)
    val unoccupiedZoneSetback = Point(DomainName.unoccupiedZoneSetback, equipRef)
    val zoneDeadTime = Point(DomainName.zoneDeadTime, equipRef)
    val coolingDeadband = Point(DomainName.coolingDeadband, equipRef)
    val heatingDeadband = Point(DomainName.heatingDeadband, equipRef)
    val coolingAirflowTemp = Point(DomainName.coolingAirflowTemp, equipRef)
    val heatingAirflowTemp = Point(DomainName.heatingAirflowTemp, equipRef)

    val standaloneEconomizingToMainCoolingLoopMap = Point(DomainName.standaloneEconomizingToMainCoolingLoopMap, equipRef)
    val standaloneEconomizingMinTemperature = Point(DomainName.standaloneEconomizingMinTemperature, equipRef)
    val standaloneEconomizingMaxTemperature = Point(DomainName.standaloneEconomizingMaxTemperature, equipRef)
    val standaloneEconomizingMinHumidity = Point(DomainName.standaloneEconomizingMinHumidity, equipRef)
    val standaloneEconomizingMaxHumidity = Point(DomainName.standaloneEconomizingMaxHumidity, equipRef)
    val standaloneEconomizingDryBulbThreshold = Point(DomainName.standaloneEconomizingDryBulbThreshold, equipRef)
    val standaloneEnthalpyDuctCompensationOffset = Point(DomainName.standaloneEnthalpyDuctCompensationOffset, equipRef)
    val standaloneOutsideDamperMixedAirTarget = Point(DomainName.standaloneOutsideDamperMixedAirTarget, equipRef)
    val standaloneOutsideDamperMixedAirMinimum = Point(DomainName.standaloneOutsideDamperMixedAirMinimum, equipRef)
    val standaloneDuctTemperatureOffset = Point(DomainName.standaloneDuctTemperatureOffset, equipRef)
    val standalonePrePurgeRuntimeTuner = Point(DomainName.standalonePrePurgeRuntimeTuner, equipRef)
    val standalonePrePurgeOccupiedTimeOffsetTuner = Point(DomainName.standalonePrePurgeOccupiedTimeOffsetTuner, equipRef)
    val standalonePrePurgeFanSpeedTuner = Point(DomainName.standalonePrePurgeFanSpeedTuner, equipRef)
    val prePurgeOutsideDamperOpen = Point(DomainName.prePurgeOutsideDamperOpen, equipRef)
    val minFanRuntimePostConditioning = Point(DomainName.minFanRuntimePostConditioning, equipRef)

    val auxHeating1Activate = Point(DomainName.auxHeating1Activate, equipRef)
    val auxHeating2Activate = Point(DomainName.auxHeating2Activate, equipRef)
    val compressorLoopOutput = Point(DomainName.compressorLoopOutput, equipRef)
    val dcvDamperModulating = Point(DomainName.dcvDamperModulating, equipRef)
    val auxHeatingStage1 = Point(DomainName.auxHeatingStage1, equipRef)
    val auxHeatingStage2 = Point(DomainName.auxHeatingStage2, equipRef)
    val otaStatusHyperLite = Point(DomainName.otaStatusHyperlite, equipRef)
    val otaStatusConnectModule = Point(DomainName.otaStatusConnectModule, equipRef)
    val faceBypassDamperRelayActivationHysteresis = Point(DomainName.faceBypassDamperRelayActivationHysteresis, equipRef)
    val hyperstatStageDownTimerCounter = Point(DomainName.hyperstatStageDownTimerCounter, equipRef)
    val hyperstatStageUpTimerCounter = Point(DomainName.hyperstatStageUpTimerCounter, equipRef)
    val relayStages = HashMap<String, Int>()
    val analogOutStages = HashMap<String, Int>()
    // pin password
    val enableConditioningModeFanAccess = Point(DomainName.enableConditioningModeFanAccess, equipRef)
    val pinLockConditioningModeFanAccess = Point(DomainName.pinLockConditioningModeFanAccess, equipRef)
    val pinLockInstallerAccess = Point(DomainName.pinLockInstallerAccess, equipRef)
    val installerPinEnable = Point(DomainName.enableInstallerAccess, equipRef)
    val enableSpaceTempDisplay = Point(DomainName.enableSpaceTempDisplay, equipRef)
    val enableDesiredTempDisplay = Point(DomainName.enableDesiredTempDisplay, equipRef)
    val emergencyShutoffNO = Point(DomainName.emergencyShutoffNO, equipRef)
    val emergencyShutoffNC = Point(DomainName.emergencyShutoffNC, equipRef)
    fun isCondensateTripped(): Boolean = condensateStatusNC.readHisVal() > 0.0 || condensateStatusNO.readHisVal() > 0.0

}